### ISSUE TITLE
System.Fabric.UpgradeService.StreamChannelException: 

### ISSUE THREAD

**Issue by Romiko** [Azure/service-fabric-issues#1024]
Hi,
Service Fabric Version: 6.1.456.9494
Upgrade Domains: 0 to 4

All other services are green and the application is running correctly.

Our Upgrade Service is throwing the following exception.
`Exception encountered: System.Fabric.UpgradeService.StreamChannelException: Exception of type 'System.Fabric.UpgradeService.StreamChannelException' was thrown.`

`Unhealthy event: SourceId='UpgradeService.Primary', Property='SFRPStreamChannel', HealthState='Warning', ConsiderWarningAsError=false.
Exception encountered: System.Fabric.UpgradeService.StreamChannelException: Exception of type 'System.Fabric.UpgradeService.StreamChannelException' was thrown.
   at System.Fabric.UpgradeService.WrpStreamChannel.d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpStreamChannel.d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpStreamChannel.d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.ClusterCoordinator.d__16.MoveNext()`

**Comment by rdurham285** [comment]
We are seeing the same behavior in all of our dev environments as well. Is there any update? Service Type version: 6.1.480.9494

**Comment by vaishnavk** [comment]
@rdurham285 Which region is this? Do you have the list of clusters id which are seeing this exception?

**Comment by twcatron92** [comment]
@vaishnavk we've got two clusters with this issue. One in east us and the other in central us.

east us cluster - `b85ef30f-f25d-4bfd-b7d4-23e5a8ebdeb6`
central us cluster - `0d7964f8-ec86-4695-b474-4dd9d2a21ec0`

**Comment by walima0103** [comment]
+1!!! Central US - e0c4e151-ad47-4780-9e43-374c07fc02ff - Internal-only load balancer

**Comment by TonyGerace** [comment]
Has there been any update on this issue?

**Comment by gparrington** [comment]
And another one. This just started today and hasn't cleared after many hours. I can see the primary for the Upgrade service moving around the nodes periodically but the error persists. Beyond that the fabric seems OK - the apps are running and have been themselves upgraded several times today. My cluster is in WestEurope, on 6.2.301.9494 and id d02fcb8c-9a89-41ad-9ebb-81c6da70af53

**Comment by vaishnavk** [comment]
We found the root of the issue. We were not resetting out error counter which was causing us to prematurely report errors. This will be fixed in the next CU release. This should not affect the functioning of the cluster.

**Comment by jijli** [comment]
How to Manually fix the issue. it block upgrade the application since it has this issue.

**Comment by gparrington** [comment]
This is still an issue for us and is blocking the automatic upgrade to newer SF release. As a consequence we are now being wwarned that our version goes out of support in 1 day
