### ISSUE TITLE
SF Installation Error -The Service Fabric Host Service service terminated unexpectedly.

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#1026]
Hi Team,

While configuring 3 nodes cluster. i am seeing below error.

Service Fabric Host Service is starting fine on two other machines but not on 1 node.

Let me know how can i troubleshoot those error.

Timed out Waiting for the FabricHostSvc to be in Running state on machine xx.xxx.xxx.xx
CreateCluster Error: System.AggregateException: One or more errors occurred. ---> System.ServiceProcess.TimeoutException
: Timed out Waiting for the FabricHostSvc to be in Running state on machine xx.xxx.xxx.xx
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(Str
ing machineName, ServiceController installerSvc, TimeSpan timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndWaitForInstallerService(String machine
Name, Nullable`1 timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass20_0.<RunFabricServices>b__0(
String m)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions par
allelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal,
 Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOption
s, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithE
verything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.RunFabricServices(MachineHealthContainer machi
neHealthContainer, FabricPackageType fabricPackageType, TimeSpan timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
---> (Inner Exception #0) System.ServiceProcess.TimeoutException: Timed out Waiting for the FabricHostSvc to be in Runni
ng state on machine xx.xxx.xxx.xx
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(Str
ing machineName, ServiceController installerSvc, TimeSpan timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndWaitForInstallerService(String machine
Name, Nullable`1 timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass20_0.<RunFabricServices>b__0(
String m)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

Below error is logged in eventvwr.

The Service Fabric Host Service service terminated unexpectedly.  It has done this 2 time(s).  The following corrective action will be taken in 5000 milliseconds: Restart the service.

Thanks,
Naresh Khatri

**Comment by nareshkhatri81** [comment]
When i run testconfiguration.ps1 i see everything green.

PS C:\Users\a-nkhatri\Downloads\Microsoft.Azure.ServiceFabric.WindowsServer.6.1.480.9494> .\TestConfiguration.ps1

cmdlet TestConfiguration.ps1 at command pipeline position 1
Supply values for the following parameters:
ClusterConfigFilePath: ClusterConfig.Unsecure.DevCluster.json
Trace folder already exists. Traces will be written to existing trace folder: C:\Users\a-nkhatri\Downloads\Microsoft.Azu
re.ServiceFabric.WindowsServer.6.1.480.9494\DeploymentTraces
Running Best Practices Analyzer...
Best Practices Analyzer completed successfully.


LocalAdminPrivilege        : True
IsJsonValid                : True
IsCabValid                 :
RequiredPortsOpen          : True
RemoteRegistryAvailable    : True
FirewallAvailable          : True
RpcCheckPassed             : True
NoConflictingInstallations : True
FabricInstallable          : True
DataDrivesAvailable        : True
NoDomainController         : True
Passed                     : True

i tried to deploy 3 nodes in 1vm which has issue and deployment succeeded.
i am not able to understand why this VM has issue when its part of cluster.

Thanks,
Naresh Khatri

**Comment by nareshkhatri81** [comment]
https://github.com/Azure/service-fabric-issues/issues/1030

**Comment by nareshkhatri81** [comment]
@rishirsinha 
i see this entry as warning.
i checked directory is available.
i replaced machine name below with XXXXX.
i tried changing path but it didnt help.

2018/05/03-18:30:48.824,Warning,9628,ImageStoreClient.ManagedFileLock,Failed to acquire writer lock for d:\Data\SF\XXXXXXXX \Fabric\work\UnreliableTransportSettings.ini. Error = System.IO.DirectoryNotFoundException: The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
	   at System.Fabric.Interop.NativeCommon.FabricFileOpen(IntPtr path, FABRIC_FILE_MODE fileMode, FABRIC_FILE_ACCESS fileAccess, FABRIC_FILE_SHARE fileShare, IntPtr& fileHandle)
	   at System.Fabric.Common.FabricFile.OpenHelper(String path, FileMode fileMode, FileAccess fileAccess, FileShare fileShare)
	   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
	   at System.Fabric.Interop.Utility.RunInMTA[TResult](Func`1 func)
	   at System.Fabric.Common.FabricFile.Open(String path, FileMode fileMode, FileAccess fileAccess, FileShare fileShare)
	   at System.Fabric.Management.ImageStore.FileLock.Acquire()

**Comment by nareshkhatri81** [comment]
Fixed...
