### ISSUE TITLE
Method not found: 'Void System.Fabric.Common.Tracing.FabricEvents.LocalStateRecoverCheckpointEnd(System.String)'

### ISSUE THREAD

**Issue by abatishchev** [Azure/service-fabric-issues#1085]
I'm unable to continuously deploy, debug (rinse, repeat) a stateful service on local cluster.

Here's what I have installed on my machine:

```
Azure Service Fabric 6.2.274.9494
Azure Service Fabric SDK 3.1.274.9494
```

NuGet packages used by my application:

```
<PackageReference Include="Microsoft.ServiceFabric" Version="6.2.283" />
<PackageReference Include="Microsoft.ServiceFabric.Data" Version="3.1.283" />
<PackageReference Include="Microsoft.ServiceFabric.Services" Version="3.1.283" />
<PackageReference Include="NETStandard.Library" Version="2.0.3" />
```

Service Fabric Local Cluster Manager shows this error:

```
Error event: SourceId='System.FM', Property='State'.
Partition is in quorum loss.
fabric:/DeploymentAgent/AgentService 1 1 be040b0a-37b2-4cbb-90d2-0f6fc037961b
  N/P Down _Node_0 131721274279788750
```

Visual Studio shows in Debug window:

```
Exception thrown: 'System.MissingMethodException' in System.Fabric.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in Microsoft.ServiceFabric.Data.Impl.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in Microsoft.ServiceFabric.Data.Impl.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Exception thrown: 'System.AggregateException' in mscorlib.dll
```

If I break on MissingMethodException then I'm setting this:

```
Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false.
Replica had multiple failures during open on _Node_0. API call: IStatefulServiceReplica.Open(); Error = System.MissingMethodException (-2146233069)
Method not found: 'Void System.Fabric.Common.Tracing.FabricEvents.LocalStateRecoverCheckpointEnd(System.String)'.
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.d__148.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.LocalStateRecoverCheckpointAsync()
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.d__184.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.d__116.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.TransactionalReplicator.d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.StatefulServiceReplica.d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Data.ReliableStateManagerImpl.d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.d__17.MoveNext()
```

**Comment by ashishnegi** [comment]
@abatishchev 
Cluster runtime version can't be lower than sdk used.
Here you have 6.2.274 runtime and app with 6.2.283. This is not supported. Please install 6.2.283 cluster as well.

**Comment by abatishchev** [comment]
Right, that's the part I've missed somehow.

Interestingly, it works the first time I deploy my app from VS. Then on subsequent attempts I'm getting all these exceptions. Thoughts?

**Comment by ashishnegi** [comment]
In difference in two apps ? Did you uninstall as soon as you deployed during first run ? `MissingMethodException` will be called only if method is called and not found. So, that code path needs to hit.
The good thing is that right behavior (here exceptions) is reproducible.

**Comment by abatishchev** [comment]
No substantial difference: just regular develop, deploy locally, debug flow. It works once after local cluster cleanup and doens't on subsequent attempts.

**Comment by ashishnegi** [comment]
Just guessing from name : `LocalStateRecoverCheckpointEnd` codepath is unlikely to be triggered on a clean setup. May be that does not trigger the issue on clean setup. But, I am not area expert on data recovery in SF.

**Comment by abatishchev** [comment]
Please reopen. I'm getting the same error in the same situation even having .283 installed on machines and used from packages.

**Comment by ashishnegi** [comment]
Can you share the version number of `System.Fabric.dll` present in GAC. This is somewhere at `C:\Windows\Microsoft.NET\assembly\GAC_64\System.Fabric\v4.0_6.0.0.0__31bf3856ad364e35\System.Fabric.dll` ?
and version number of `Microsoft.ServiceFabric.Data.Impl.dll` present at `bin\Fabric\Fabric.Code\NS` in SF installation directory. They should both be 6.2..283
If they are same version, please share the `Microsoft.ServiceFabric.Data.Impl.dll` @ asnegi [at] microsoft.com

**Comment by ashishnegi** [comment]
@abatishchev Any findings ?

**Comment by abatishchev** [comment]
hi @ashishnegi, doing this right now as almost the first thing once I'm back in office.

System.Fabric.dll is 6.2.283.9494

**Comment by Mads-Rasmussen** [comment]
We're seeing the same issue

**Comment by ashishnegi** [comment]
@Mads-Rasmussen Can you share information asked on this [comment](https://github.com/Azure/service-fabric-issues/issues/1085#issuecomment-394072738) ?

**Comment by ashishnegi** [comment]
@Mads-Rasmussen / @abatishchev Is this windows or Linux SF ?
@abatishchev Can you share other information asked on [comment](https://github.com/Azure/service-fabric-issues/issues/1085#issuecomment-394072738) ?

**Comment by abatishchev** [comment]
Sorry, missed your question about another dll. Microsoft.ServiceFabric.Data.Impl.dll has version 6.2.283.9494 as well .

Sen you them both over email.

**Comment by ashishnegi** [comment]
I looked at assembly of dll in ilspy and it seems `LocalStateRecoverCheckpointEnd` is not being used by Data.Impl.dll. So, you should not see this exception.

Can you share a sample project ?
A dump will be very helpful here. Please share dump to asnegi [at] microsoft.com. You can share it via public or private links of any storage service.


![local_state_recovercheckpointendusage](https://user-images.githubusercontent.com/1728946/41021028-990f4eba-6982-11e8-8e5f-f5e7ed83dc7e.PNG)

**Comment by ashishnegi** [comment]
You can use any way to generate dumps. See if [this](https://blogs.msdn.microsoft.com/chaun/2013/11/12/steps-to-catch-a-simple-crash-dump-of-a-crashing-process/) is helpful.

**Comment by abatishchev** [comment]
I'm getting these exception right now but the process doesn't crash so doesn't produce a dump.

**Comment by abatishchev** [comment]
The stack trace for MissingMethodException is this:
```
  at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<LocalStateRecoverCheckpointAsync>d__148.MoveNext()
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
```

or this:
```
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<LocalStateRecoverCheckpointAsync>d__148.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.LocalStateRecoverCheckpointAsync()
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<RecoverStateManagerCheckpointAsync>d__184.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

or this:
```
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<LocalStateRecoverCheckpointAsync>d__148.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.LocalStateRecoverCheckpointAsync()
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<RecoverStateManagerCheckpointAsync>d__184.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<OpenAsync>d__116.MoveNext()
```

or this:
```
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<LocalStateRecoverCheckpointAsync>d__148.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.LocalStateRecoverCheckpointAsync()
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<RecoverStateManagerCheckpointAsync>d__184.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<OpenAsync>d__116.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```
or this:
```
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<LocalStateRecoverCheckpointAsync>d__148.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.LocalStateRecoverCheckpointAsync()
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<RecoverStateManagerCheckpointAsync>d__184.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<OpenAsync>d__116.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.TransactionalReplicator.<OpenAsync>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```
and so on.

TargetSite is `{Void MoveNext()}` in all cases if that matters.

**Comment by ashishnegi** [comment]
It is even easier to get a dump of running process. Can you just use `task manager` and `right-click` on running process and select `create dump file`. Please share with me.

**Comment by ashishnegi** [comment]
Looked at the dump shared by @abatishchev . Microsoft.ServiceFabric.Data.Impl.dll was present in GAC. We don't GAC Microsoft.ServiceFabric.Data.Impl.dll. This was local machine.

@Mads-Rasmussen Can you check if your dev cluster has the same issue ? 
Folder : `C:\WINDOWS\Microsoft.Net\assembly\GAC_64\Microsoft.ServiceFabric.Data.Impl\` should not be present.

If it is present for you as well, this can be a bug from our side. Otherwise, share a dump with me . asnegi [at] microsoft.com .

**Comment by ashishnegi** [comment]
Closing as issue is solved for original OP. please reopen if issue exists for others.
