### ISSUE TITLE
Deploying a Stateful Service in Visual Studio 2017 can't find Service Fabric Powershell commands

### ISSUE THREAD

**Issue by njayinthehouse** [Azure/service-fabric-issues#1089]
I installed the Service Fabric SDK using the [web platform installer](http://www.microsoft.com/web/handlers/webpi.ashx?command=getinstallerredirect&appid=MicrosoftAzure-ServiceFabric-CoreSDK) found on the [installation guide](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started). I also enabled Powershell script execution by running the following as administrator:

```powershell
Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force -Scope CurrentUser
```

Next, I created an application with a stateful service (.NET Core 2.0). I tried running the code template. The deployment fails with this log:

```
1>------ Build started: Project: Application9, Configuration: Debug x64 ------
2>------ Deploy started: Project: Application9, Configuration: Debug x64 ------
2>Started executing script 'GetApplicationExistence'.
2>Finished executing script 'GetApplicationExistence'.
2>Time elapsed: 00:00:00.3095535
2>Started executing script 'Set-LocalClusterReady'.
2>powershell -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -Command "Import-Module 'C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\DefaultLocalClusterSetup.psm1'; Set-LocalClusterReady -createOneNodeCluster $true"
2>--------------------------------------------
2>Local Service Fabric Cluster is not setup...
2>Please wait while we setup the Local Service Fabric Cluster. This may take few minutes...
2>To support container discovery and DNS in Service Fabric, please run the script at %ProgramFiles%\Microsoft SDKs\Service Fabric\ClusterSetup\DevClusterSetup.ps1 with -UseMachineName option. This will open TCP port 19000 and 19080 for incoming traffic to your local cluster. If you don't need access, you can manually remove these firewall rules.
2>WARNING: System.Management.Automation.CommandNotFoundException: The term 'Remove-ServiceFabricNodeConfiguration' is not
2> recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if 
2>a path was included, verify that the path is correct and try again.
2>
2>   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception 
2>exception)
2>
2>   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2>
2>   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2>
2>   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2>WARNING: Remove-ServiceFabricNodeConfiguration throws exceptions
2>
2>Using Cluster Data Root: C:\SfDevCluster\Data
2>Using Cluster Log Root: C:\SfDevCluster\Log
2>
2>The generated json path is C:\Users\t-niraj\AppData\Local\Temp\tmp4254.tmp.json
2>Processing and validating cluster config.
2>Exception calling "GetClusterManifestFromJsonConfig" with "3" argument(s): "Requested value 'PUBLIC' was not found."
2>At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:170 char:2
2>+     $manifestFileTemplate = [Microsoft.ServiceFabric.DeploymentManage ...
2>+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2>    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
2>    + FullyQualifiedErrorId : ArgumentException
2> 
2>Copy-Item : Cannot bind argument to parameter 'Path' because it is an empty string.
2>At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:465 char:15
2>+     Copy-Item $manifestFileTemplate $manifestFile -Force
2>+               ~~~~~~~~~~~~~~~~~~~~~
2>    + CategoryInfo          : InvalidData: (:) [Copy-Item], ParameterBindingValidationException
2>    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Copy 
2>   ItemCommand
2> 
2>Test-ServiceFabricClusterManifest : The term 'Test-ServiceFabricClusterManifest' is not recognized as the name of a 
2>cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
2>that the path is correct and try again.
2>At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:483 char:5
2>+     Test-ServiceFabricClusterManifest -ClusterManifestPath "$manifest ...
2>+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2>    + CategoryInfo          : ObjectNotFound: (Test-ServiceFabricClusterManifest:String) [], CommandNotFoundException
2>    + FullyQualifiedErrorId : CommandNotFoundException
2> 
2>PrepareClusterManifest : Could not validate cluster manifest 
2>'C:\Users\t-niraj\AppData\Local\Temp\T-NIRAJ-Z240-Server-ScaleMin.xml'
2>At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:506 char:21
2>+ ... ifestFile = PrepareClusterManifest $manifestFileTemplate $imageStoreC ...
2>+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2>    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
2>    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,PrepareClusterManifest
2> 
2>ScriptHalted
2>At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:487 char:9
2>+         throw
2>+         ~~~~~
2>    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
2>    + FullyQualifiedErrorId : ScriptHalted
2> 
2>Finished executing script 'Set-LocalClusterReady'.
2>Time elapsed: 00:00:06.4592063
2>The PowerShell script failed to execute.
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
```

I'm not familiar with Powershell, but it seems like it can't find the commands defined by Service Fabric (Test-ServiceFabricClusterManifest, Remove-ServiceFabricClusterManifest). I tried reinstalling Service Fabric and adding C:\Path\to\Service\Fabric\bin to my PATH environment variable. Neither approach worked.

My Service Fabric Local Cluster Manager also fails to reset the cluster. I'm not sure if it's related, but I think that it would be if my Powershell can't find the Service Fabric commands.

I am running Visual Studio 2017 as an administrator on Windows 10. My Powershell is at version 5.1.

**Comment by dbreshears** [comment]
@njayinthehouse , something sure seems corrupt on this machine, perhaps the Service Fabric SDK.  From control panel, what versions do you have of the Service Fabric runtime and Service Fabric SDK.     

I am assuming that this also fails then following these 2 steps,  and will eliminate anything with regards to VS 2017 tooling.

1. Bring up admin command prompt
2. Run powershell


```
PS C:\Windows\System32> Import-Module 'C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\DefaultLocalCluster
Setup.psm1'
PS C:\Windows\System32> Set-LocalClusterReady
```

The SDK scripts and PSModules should be found here -> C:\Program Files\Microsoft SDKs\Service Fabric\Tools,  make sure you have access to these. 

I would remove both the runtime and SDK from add/remove programs in control panel and attempt to install again (unlesss you have tried both already).

**Comment by njayinthehouse** [comment]
On further debugging that day, I found that I don't have the runtime installed at all. When I search my apps and features for service fabric, I only have the SDK, at version 3.1.283.9494.

I did try removing, restarting and reinstalling, and it failed. I also began to suspect that it was an issue with my machine; sure enough, the installation proceeded smoothly with the Windows 10 VM that I set up on my machine.

**Comment by njayinthehouse** [comment]
Here's the output of the commands you suggested I run:

```Local Service Fabric Cluster is not setup...
Please wait while we setup the Local Service Fabric Cluster. This may take few minutes...
To support container discovery and DNS in Service Fabric, please run the script at %ProgramFiles%\Microsoft SDKs\Service
 Fabric\ClusterSetup\DevClusterSetup.ps1 with -UseMachineName option. This will open TCP port 19000 and 19080 for incomi
ng traffic to your local cluster. If you don't need access, you can manually remove these firewall rules.
Stop-Service : Cannot find any service with service name 'FabricHostSvc'.
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:143 char:5
+     Stop-Service FabricHostSvc -WarningAction SilentlyContinue
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (FabricHostSvc:String) [Stop-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.StopServiceCommand

WARNING: System.Management.Automation.CommandNotFoundException: The term 'Remove-ServiceFabricNodeConfiguration' is not
 recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception
exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
WARNING: Remove-ServiceFabricNodeConfiguration throws exceptions

Using Cluster Data Root: C:\SfDevCluster\Data
Using Cluster Log Root: C:\SfDevCluster\Log

The generated json path is C:\Users\t-niraj\AppData\Local\Temp\tmp3A81.tmp.json
Processing and validating cluster config.
Test-ServiceFabricClusterManifest : The term 'Test-ServiceFabricClusterManifest' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:483 char:5
+     Test-ServiceFabricClusterManifest -ClusterManifestPath "$manifest ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Test-ServiceFabricClusterManifest:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PrepareClusterManifest : Could not validate cluster manifest
'C:\Users\t-niraj\AppData\Local\Temp\T-NIRAJ-Z240-Server-ScaleMin.xml'
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:506 char:21
+ ... ifestFile = PrepareClusterManifest $manifestFileTemplate $imageStoreC ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,PrepareClusterManifest

ScriptHalted
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:487 char:9
+         throw
+         ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
```

**Comment by shudv** [comment]
@njayinthehouse Did you find the solution to your problem? If yes, can you please share it. I am facing the exact same issue.

**Comment by njayinthehouse** [comment]
Unfortunately, no. However, it was most likely an issue with the system I was using; I installed a VM and tried the installation on that, and it went smoothly. Not the most elegant solution, but I was under tight time constraints.

**Comment by shudv** [comment]
Well that's bad. Thanks anyway!

**Comment by ohwellwhatever** [comment]
Same problem here.
PS C:\windows\system32> Import-Module 'C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\DefaultLocalClusterSetup.psm1'

PS C:\windows\system32> Set-LocalClusterReady
--------------------------------------------
Local Service Fabric Cluster is not setup...
Please wait while we setup the Local Service Fabric Cluster. This may take few minutes...
Stop-Service : Cannot find any service with service name 'FabricHostSvc'.
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:144 char:5
+     Stop-Service FabricHostSvc -WarningAction SilentlyContinue
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (FabricHostSvc:String) [Stop-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.StopServiceCommand
 
WARNING: System.Management.Automation.CommandNotFoundException: The term 'Remove-ServiceFabricNodeConfiguration' is not recognized as the name of a cmdlet, function, scri
pt file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
WARNING: Remove-ServiceFabricNodeConfiguration throws exceptions

Using Cluster Data Root: C:\SfDevCluster\Data
Using Cluster Log Root: C:\SfDevCluster\Log

The generated json path is C:\Users\jamha\AppData\Local\Temp\tmpDC19.tmp.json
Processing and validating cluster config.
Failed to open base key for machine ComputerFullName to check if machine is IOT Core.
Test-ServiceFabricClusterManifest : The term 'Test-ServiceFabricClusterManifest' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:504 char:5
+     Test-ServiceFabricClusterManifest -ClusterManifestPath "$manifest ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Test-ServiceFabricClusterManifest:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PrepareClusterManifest : Could not validate cluster manifest 'C:\Users\jamha\AppData\Local\Temp\JHZ230-Server-ScaleMin.xml'
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:530 char:21
+ ... ifestFile = PrepareClusterManifest $manifestFileTemplate $imageStoreC ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,PrepareClusterManifest
 
ScriptHalted
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:508 char:9
+         throw
+         ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted

**Comment by thucnguyen77** [comment]
I am also having the same issue with setting up the local cluster.

The errors in my case are as below.
```
PS C:\> Set-LocalClusterReady
--------------------------------------------
Local Service Fabric Cluster is not setup...
Please wait while we setup the Local Service Fabric Cluster. This may take few minutes...
Performing Stop-Service on: FabricHostSvc . This may take a few minutes...
WARNING: System.Management.Automation.CommandNotFoundException: The term 'Remove-ServiceFabricNodeConfiguration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
WARNING: Remove-ServiceFabricNodeConfiguration throws exceptions

Using Cluster Data Root: C:\SfDevCluster\Data
Using Cluster Log Root: C:\SfDevCluster\Log

The generated json path is C:\Users\Thuc\AppData\Local\Temp\tmpD544.tmp.json
Processing and validating cluster config.
Exception calling "GetClusterManifestFromJsonConfig" with "3" argument(s): "Requested value 'PUBLIC' was not found."
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:205 char:5
+     $manifestFileTemplate = [Microsoft.ServiceFabric.DeploymentManage ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException

Copy-Item : Cannot bind argument to parameter 'Path' because it is an empty string.
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:778 char:15
+     Copy-Item $manifestFileTemplate $manifestFile -Force
+               ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Copy-Item], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.CopyItemCommand

Get-Content : Cannot find path 'C:\Users\Thuc\AppData\Local\Temp\DESKTOP-C7R7UCB-Server-ScaleMin.xml' because it does not exist.
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:493 char:6
+     (Get-Content $filePath) | ForEach-Object {$_ -replace $toReplace, ...
+      ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Thuc\A...er-ScaleMin.xml:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Cannot find path 'C:\Users\Thuc\AppData\Local\Temp\DESKTOP-C7R7UCB-Server-ScaleMin.xml' because it does not exist.
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:493 char:6
+     (Get-Content $filePath) | ForEach-Object {$_ -replace $toReplace, ...
+      ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Thuc\A...er-ScaleMin.xml:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Test-ServiceFabricClusterManifest : The term 'Test-ServiceFabricClusterManifest' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:804 char:5
+     Test-ServiceFabricClusterManifest -ClusterManifestPath "$manifest ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Test-ServiceFabricClusterManifest:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PrepareClusterManifest : Could not validate cluster manifest 'C:\Users\Thuc\AppData\Local\Temp\DESKTOP-C7R7UCB-Server-ScaleMin.xml'
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:840 char:21
+ ... ifestFile = PrepareClusterManifest $manifestFileTemplate $imageStoreC ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,PrepareClusterManifest

ScriptHalted
At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:808 char:9
+         throw
+         ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
```

By looking further in the PowerShell scripts, I could find the starting point of the problem in this function.
```
function ConstructManifestFileTemplate([string]$jsonTemplate)
{
    $runtimeInstallPath = (Get-ItemProperty 'HKLM:\Software\Microsoft\Service Fabric').FabricCodePath
    $deploymentmangager= Join-Path -Path $runtimeInstallPath -ChildPath "Microsoft.ServiceFabric.DeploymentManager.dll"

    [Reflection.Assembly]::LoadFrom($deploymentmangager) > $null
    $manifestFileTemplate = [Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility]::GetClusterManifestFromJsonConfig($jsonTemplate, "", "")

    return $manifestFileTemplate
}
```

The call to `GetClusterManifestFromJsonConfig` failed with error message `Requested value 'PUBLIC' was not found.` Thus it returned an empty string.

And from there things failed miserably.

Now I am looking to understand what this function does/needs `[Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility]::GetClusterManifestFromJsonConfig`.

Could anyone have any ideas, or direct me to the source code of this please?

Thanks.

**Comment by anantshankar17** [comment]
@thucnguyen77 the failures in your script indicate the missing powershell module.
Did you try rebooting your machine ? If yes, can you check if the runtime and sdk are installed in the control panel ? Can you try removing and reinstalling both ?

**Comment by ravipal** [comment]
Please try @anantshankar17 suggestion. If still didn't work, please repon this issue.
