### ISSUE TITLE
CompositionFailedException: ILaunchSettingsProvider not exported by Service Fabric Projects in Common Project System

### ISSUE THREAD

**Issue by 13thirteen** [Azure/service-fabric-issues#1095]
Hi, I'm the author of a [Visual Studio extension ](https://marketplace.visualstudio.com/items?itemName=vs-publisher-141975.SwitchStartupProjectforVS2017) which allows to switch between multiple startup project configurations. That extension uses the Visual Studio SDK and the [Common Project System ](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/Index.md) to read and modify startup properties of Visual Studio projects.

Unfortunately, with Azure Service Fabric projects that extension has a problem:
After successfully [detecting that they are CPS projects](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/automation/detect_whether_a_project_is_a_CPS_project.md), and after successfully [getting the unconfigured CPS project](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/automation/finding_CPS_in_a_VS_project.md), it tries to get the `ILaunchSettingsProvider` from the project as follows:
```
IVsBrowseObjectContext context = ... ;
var launchSettingsProvider = context.UnconfiguredProject.Services.ExportProvider.GetExportedValue<ILaunchSettingsProvider>();
```
(as is being done [here ](https://github.com/dotnet/project-system/blob/b3b6ea07cd088926ac7973e1f916ec5be9df55e6/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageViewModel.cs#L1024) for example.)

However, this call raises the following exception:
```
Microsoft.VisualStudio.Composition.CompositionFailedException
  HResult=0x80131500
  Message=Expected 1 export(s) with contract name "Microsoft.VisualStudio.ProjectSystem.Debug.ILaunchSettingsProvider" but found 0 after applying applicable constraints.
  Source=Microsoft.VisualStudio.Composition
  StackTrace:
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.DelegatingExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.ProjectSystem.ServicesBase.FilteringExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at LucidConcepts.SwitchStartupProject.StartupProjectSwitcher.<_GetCurrentlyActiveConfiguration>b__25_0(String projectPath)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LucidConcepts.SwitchStartupProject.StartupProjectSwitcher._GetCurrentlyActiveConfiguration(IEnumerable`1 newStartupProjectPaths)
   at LucidConcepts.SwitchStartupProject.StartupProjectSwitcher.UpdateStartupProject()
   at LucidConcepts.SwitchStartupProject.StartupProjectSwitcher.AfterOpenSolution()
   at LucidConcepts.SwitchStartupProject.SwitchStartupProjectPackage.OnAfterBackgroundSolutionLoadComplete()
```
This call succeeds with other kinds of CPS projects such as .NET Core projects but fails with Azure Service Fabric projects.

Any idea how to access the launch settings of Service Fabric projects?

Environment information:

Visual Studio Professional 2017 15.7.2
Microsoft Azure Service Fabric Tools for Visual Studio 2.1
Microsoft Azure Tools 2.9
Switch Startup Project 3.5.39

Microsoft Azure Service Fabric 6.2.283.9494
Microsoft Azure Service Fabric SDK 3.1.283.9494

**Comment by NCarlsonMSFT** [comment]
@13thirteen not all implementations of CPS support ILaunchSettingsProvider. I believe you can check for the Project Capability [LaunchProfiles](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/project_capabilities.md) to check a particular project.

Is there a particular thing you are trying to change for Service Fabric projects?

**Comment by 13thirteen** [comment]
Ah, I wasn't aware that support for `ILaunchSettingsProvider` was optional. Checking for the `LaunchProfiles` capability seems to work.
Thanks for the hint!
