### ISSUE TITLE
new build of web api will no longer deploy to cluster

### ISSUE THREAD

**Issue by macawman** [Azure/service-fabric-issues#1099]
I have a web service that was compile a couple of months ago and deploys and works without any issues. I took the exact same code and recompiled it (without issues) but it will not deploy to the service machine. 
The compiled version from a couple of months ago will still deploy to the cluster.
 The newly compiled version  will deploy on my local machine. Other newly compiled Web services still deploy without issues. 
Any thoughts on what could be causing this or how to solve it would be greatly appreciated.
Changes to servers during this time:
On Service fabric cluster: 
Upgrade Service Fabric Cluster to 6.2.274.9494
On Build server:
	Upgrade to Service Fabric SDK – 3.1.274
	Visual Studio 2017 update to 15.7.1
	Upgrade .NET to 4.7.2 (code is targeting net461)

Versions:
IdentityServer4 Version=1.5.1
Microsoft.ApplicationInsights.AspNetCore Version=2.3.0 
Microsoft.AspNetCore Version=1.1.2
Microsoft.AspNetCore.Mvc Version=1.1.3 
Microsoft.AspNetCore.StaticFilesEx Version=1.0.0.4 
Microsoft.EntityFrameworkCore.SqlServer Version=1.1.2 
Microsoft.EntityFrameworkCore.Tools Version=1.1.1
Microsoft.ServiceFabric.AspNetCore.Abstractions Version=3.1.283 
 Microsoft.ServiceFabric.AspNetCore.Kestrel Version=3.1.283
 Microsoft.ServiceFabric Version=6.2.283
Microsoft.ServiceFabric.AspNetCore.WebListener Version=3.1.283 
Microsoft.ServiceFabric.Data Version=3.1.283
Microsoft.ServiceFabric.Services Version=3.1.283
The error is service fabric explorer is :
Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false.
Replica had multiple failures during open on sever1. API call: IStatelessServiceInstance.Open(); Error = System.Collections.Generic.KeyNotFoundException (-2146232969)
The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.CandidateResolver.ComputeClassification(String dependency)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.CandidateResolver.ComputeClassification(String dependency)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.CandidateResolver.ComputeClassification(String dependency)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.CandidateResolver.d__4.MoveNext()
   at System.Linq.Enumerable.d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at methodcall1.<>c__DisplayClass1_0.b__1(String url, AspNetCoreCommunicationListener listener)
   at Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__13.MoveNext()

**Comment by masnider** [comment]
There is a known issue with ASP.NET Core SDK which looks very similar to what you're experiencing. There's some additional dependencies and the older Mvc 1.0 \ 1.1 have a bug where they do not ignore these and it causes the exception. 

More details see https://github.com/aspnet/Home/issues/3132#issuecomment-388082725

Known work-arounds are also listed in that reference
•	Upgrading to ASP.NET Core 2.0 should fix this. 
•	To add a global.json to your solution and specify an older Sdk
•	You could manually do Mvc's assembly part discovery and add an ApplicationPartManager instance before calling AddMvc(). Might look like:

var manager = new ApplicationPartManager();
manager.ApplicationParts.Add(new AssemblyPart(typeof(Startup).Assembly));
manager.ApplicationParts.Add(new AssemblyPart(typeof(Project1.Project1Type).Assembly));

services.AddSingleton(manager);
services.AddMvc();

**Comment by MedAnd** [comment]
Hi @masnider, started getting an exception very similar to above in multiple clusters in various geos as per:

Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false.
Replica had multiple failures during open on _nt1vm_3. API call: IStatelessServiceInstance.Open(); Error = System.IO.IOException (-2146232800)
Failed to bind to address http://+:80: address already in use.
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Web.Program.WebHostingService.Microsoft.ServiceFabric.Services.Communication.Runtime.ICommunicationListener.OpenAsync(CancellationToken cancellationToken) in C:\Agents\_work\22\s\Main\xxxxxxxxxxxx\src\Web\Program.cs:line 87
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__13.MoveNext()

- Project TargetFramework net461
- OS .Net Version = 4.7.0
- Microsoft.AspNetCore.Server.Kestrel Version="1.1.1"
- Microsoft.AspNetCore.Hosting  Version="1.1.1"
- Microsoft.ServiceFabric Version="6.2.301"
- Microsoft.ServiceFabric.Services Version="6.2.301"
- Microsoft.ServiceFabric.Services.Remoting Version="3.1.301"

**Comment by masnider** [comment]
@MedAnd @macawman - looks like this should be resolved in more recent versions of .NET Core, and we haven't heard more recent reports of this. I'm going to close this down for now. If you're still having this issue with recent ASP Net Core, .Net Core, and SF builds, please either reopen this here or open a new issue with the repro and we can take a look. Thanks!
