### ISSUE TITLE
System.ArgumentException: failed to deserialize and get remote exception Parameter name: remoteExceptionInformation

### ISSUE THREAD

**Issue by batwad** [Azure/service-fabric-issues#11]
I have a problem with exception propagation in my service fabric application.  The call chain looks like this:

```
Stateless web API -> actor -> stateful service -> external WCF service
```

When the WCF service external to my application throws an `FaultException` my stateful service handles it in some cases, and in others wraps it in a custom exception of mine.  The custom exception is `[Serializable]` and is propagated to the actor in an `AggregateException` perfectly in tact, which I have verified in the debugger.  The actor does not handle the exception so I expect it to propagate to the web API, however in the web API I receive the following exception instead:

```
System.ArgumentException: failed to deserialize and get remote exception
Parameter name: remoteExceptionInformation
   at Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient`1.<InvokeWithRetryAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.Client.ServiceRemotingPartitionClient.<InvokeAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.<InvokeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.<ContinueWith>d__b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MyWebApi.MyController.<Post>d__0.MoveNext() in MyController.cs:line 40
```

It seems strange the exception can propagate one level (service to actor) but not two (actor to service).

**Comment by aelij** [comment]
Where is the class that defines the custom exception? Is its assembly available on the client side?

This error happens when the deserializer is unable to load the exception's type. So exceptions should be defined in some common assembly, shared by the caller and the callee.

**Comment by batwad** [comment]
You're quite right; the exception was defined in the project that contains the actor and stateful service but the web API is in a separate project. I moved the exception to the interface project and it all worked a treat.

It would have been helpful to throw the traditional `System.TypeLoadException` and tell me that it couldn't load the exception, then I would have tracked down the problem more quickly.

**Comment by mlr-msft** [comment]
I've run into a this same exception with Service Fabric attempting to deserialize a `Microsoft.Azure.Documents.DocumentClientException` thrown by an actor method. 

Clearly, I cannot move the definition of the exception to a different place. I've attempted to add the DocumentDB nuget package to the project in hopes that this would make the type available to the deserializer but this hasn't fixed the issue. 

How can I address this issue? I am not certain what to try next.

**Comment by masnider** [comment]
You would have to catch the exception and return a different exception that was deserializable on the client side.

**Comment by VipulM-MSFT** [comment]
@mlr-msft We will be closing this issue. If you have further questions, please feel free to open the issue.
