### ISSUE TITLE
Transaction 131735864350639769 is committing or rolling back or has already committed or rolled back

### ISSUE THREAD

**Issue by somesh84** [Azure/service-fabric-issues#1115]
636647096370639506, 83, 93, 1, 0, #437, E:\bt\937679\repo\src\Services\RouteCollectorBaseService\RouteCollectorBaseService.cs#AddUpdateOrRemovePrefix failed with exception System.InvalidOperationException: Transaction 131735864350639769 is committing or rolling back or has already committed or rolled back
   at Microsoft.ServiceFabric.Replicator.TransactionBase.ThrowIfTransactionIsNotActive()
   at System.Fabric.Store.TStore`5.<AddOrUpdateAsync>d__223.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Data.Collections.DistributedDictionary`2.<AddOrUpdateAsync>d__98.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Windows.Azure.WANDP.RouteCollectorBaseService.RouteCollectorBaseService.<AddUpdateOrRemovePrefix>d__31.MoveNext() in E:\bt\937679\repo\src\Services\RouteCollectorBaseService\RouteCollectorBaseService.cs:line 388 return error

**Comment by somesh84** [comment]
This turned out to be issue in the code,
