### ISSUE TITLE
Service fabric API cannot run in azure SF cluster

### ISSUE THREAD

**Issue by datha2703** [Azure/service-fabric-issues#1190]
Hi,
I had my build successfully built + deployed in Azure cluster. 
[VSTS Build Tasks][1]

  [1]: https://i.stack.imgur.com/Mfith.png

I was successfully building and deploying from past several months. Now since from last 5 days, code that is build from VSTS build is unable to deploy to cluster. My API service fails to start and i get below error. Please suggest how I can debug. Code successfully deploying and launching in my local cluster. 
I have no code changes. I compared working and not working build artifacts. I have new entries in my MyCompany.MyService.Api.deps.json file. Below entries came new.
```

...
"compilationOptions": {
    "defines": [
...
      "NETFRAMEWORK",
...
    ],
...
          "Microsoft.Bcl.Build": "1.0.21",
          "System.IdentityModel": "4.0.0.0",
          "System.ServiceModel.Web": "4.0.0.0",
          "System.Web.Services": "4.0.0.0",
          "System.Runtime.Caching": "4.0.0.0",
          "System.ServiceModel.Activation": "4.0.0.0"
        },
...
          "System.Transactions": "4.0.0.0",
          "System.Web": "4.0.0.0",
          "System.Diagnostics.Tracing.Reference1": "4.0.20.0",
          "System.Runtime.Serialization.Primitives.Reference": "4.0.10.0",
          "System.Runtime.Serialization.Xml.Reference": "4.0.10.0"
        },
...
          "System.Runtime.Reference1": "4.0.20.0",
          "System.Threading.Tasks.Reference1": "4.0.10.0",
          "System.Resources.ResourceManager.Reference1": "4.0.0.0",
          "System.Globalization.Reference1": "4.0.10.0",
          "System.Diagnostics.Tools.Reference1": "4.0.0.0",
          "System.Diagnostics.Debug.Reference1": "4.0.10.0",
          "System.Linq.Reference1": "4.0.0.0",
          "System.Collections.Reference1": "4.0.10.0",
          "System.Threading.Reference1": "4.0.10.0",
          "System.Runtime.Extensions.Reference1": "4.0.10.0",
          "System.IO.Reference1": "4.0.10.0",
          "System.Runtime.InteropServices.Reference1": "4.0.20.0",
          "System.Text.Encoding.Reference1": "4.0.10.0",
          "System.Reflection.Primitives.Reference1": "4.0.0.0",
          "System.Reflection.Reference1": "4.0.10.0",
          "System.Text.Encoding.Extensions.Reference1": "4.0.10.0",
          "System.ComponentModel.Reference": "4.0.0.0",
          "System.Reflection.Extensions.Reference1": "4.0.0.0"
...
```

```
Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false.
Replica had multiple failures during open on _ntsfmain_0. API call: IStatelessServiceInstance.Open(); Error = System.Collections.Generic.KeyNotFoundException (-2146232969)
The given key was not present in the dictionary.
at System.ThrowHelper.ThrowKeyNotFoundException()
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.CandidateResolver.ComputeClassification(String dependency)
at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.CandidateResolver.ComputeClassification(String dependency)
at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.CandidateResolver.ComputeClassification(String dependency)
at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.CandidateResolver.d__4.MoveNext()
at System.Linq.Enumerable.d__17`2.MoveNext()
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
at MyCompany.MyService.Api.Startup.ConfigureDevelopmentServices(IServiceCollection services) in C:\agent_C\_work\19\s\Source\MyCompany.MyService.Api\Startup.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at MyCompany.MyService.Api.Api.<>c__DisplayClass4_0.b__1(String url, AspNetCoreCommunicationListener listener) in C:\agent_C\_work\19\s\Source\MyCompany.MyService.Api\Api.cs:line 91
at Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener.OpenAsync(CancellationToken cancellationToken)
at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__13.MoveNext()
For more information see: http://aka.ms/sfhealth
```

**Comment by raunakpandya** [comment]
Please reopen if the above doesn't solve your problem.

**Comment by datha2703** [comment]
Sorry to leave comment late. My PR just approved, latest change is in cluster running happily. Tests are passing. Thanks for your help.

My change is as below in my csproj.

```
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="1.1.3" />
```
Changed to:
```
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.4" />
<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.0.3" />
```
