### ISSUE TITLE
TypeLoadException calling ActorProxy.Create method

### ISSUE THREAD

**Issue by UnProgrammatore** [Azure/service-fabric-issues#1195]
I'm trying to call a service fabric actor from a client inside another service fabric service. If versions 3.2.162 of both Microsoft.ServiceFabric.Actors and Microsoft.ServiceFabric.Services.Remoting are installed, the `ActorProxy.Create` call throws a System.TypeLoadException. Downgrading to the previous version of both packages (3.1.306) fixes the issue.
Here's the minimal steps to reproduce it:

- Create a new console application
- Add the Microsoft.ServiceFabric.Actors v3.2.162 nuget and let it install the correct dependencies
- Reference a dll with an actor interface of your choice
- Write the following line of code: `Microsoft.ServiceFabric.Actors.Client.ActorProxy.Create<IPersonActor>(new Microsoft.ServiceFabric.Actors.ActorId("MyActorID"), new Uri("fabric:/MyApplicationName/MyServiceName"));` where `IPersonActor` is the actor interface.
- Execute the code.

You will get a `System.TypeLoadException` with the following message
```
Could not load type 'Microsoft.ServiceFabric.Services.Remoting.RemotingListener' from assembly 'Microsoft.ServiceFabric.Services.Remoting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```
and the following stack trace
```
   at System.Reflection.CustomAttribute._GetPropertyOrFieldData(RuntimeModule pModule, Byte** ppBlobStart, Byte* pBlobEnd, String& name, Boolean& bIsProperty, RuntimeType& type, Object& value)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
   at Microsoft.ServiceFabric.Actors.Remoting.ActorRemotingProviderAttribute.GetProvider(IEnumerable`1 types)
   at Microsoft.ServiceFabric.Actors.Client.ActorProxyFactory.GetOrSetProxyFactory(Type actorInterfaceType)
   at Microsoft.ServiceFabric.Actors.Client.ActorProxyFactory.CreateActorProxy[TActorInterface](Uri serviceUri, ActorId actorId, String listenerName)
   at Microsoft.ServiceFabric.Actors.Client.ActorProxy.Create[TActorInterface](ActorId actorId, Uri serviceUri, String listenerName)
   at MinimalTypeLoadExceptionTest.Program.Main(String[] args) in D:\Tests\MinimalTypeLoadExceptionTest\MinimalTypeLoadExceptionTest\Program.cs:line 16
```
The exact same problem arises by doing this from a service fabric service.

**Comment by suchiagicha** [comment]
@UnProgrammatore 
Make sure you upgrade all your projects to the 3.2 version include Actor Interface project.

Did you check this thread?
https://github.com/Microsoft/service-fabric-services-and-actors-dotnet/issues/141#issuecomment-407471186

**Comment by UnProgrammatore** [comment]
No, i did not see that issue.
This fixed the problem, i didn't realize the interface was on a different version of the package.

Thank you

**Comment by UnProgrammatore** [comment]
Assuming I understand the issue properly, it won't affect the upgrade. My problem was simply that a DLL that referred to a type in the 3.1.306 version (the type of the attribute and the enums that are automatically put on actor interfaces and specify the version of remoting) was used in a project with a reference to the 3.2.162 version, in which the name of said type changed. The runtime just couldn't find the file. Publishing your services independently shouldn't be a problem. You just need to make sure that you update the packages in your interface's project before you upgrade the packages of the calling service.

**Comment by suchiagicha** [comment]
@gparrington 
If you follow this article , you should be fine with upgrade from V1 to V2 (InterfaceCompatible)
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#how-to-upgrade-from-remoting-v1-to-remoting-v2interfacecompatible.

without impacting your service availability

**Comment by gparrington** [comment]
@suchiagicha That's not my problem - my services already run V2. Consider this scenario: I have two separately deployed applications - a client app and a server (with the server component built by a different team (or indeed a different company)). The client accesses the server via an interface provided in a dll supplied by the other team. I upgrade my client to 3.2.162 and my calls to the server will fail with a TypeLoadException because the dll I import was built with effectively an incompatible version. Requiring both client and server to use the same version is not realistic in a microservice world with content from multiple teams

**Comment by suchiagicha** [comment]
@gparrington . 
Problem is not client and server in same version. Instead Client and Interfaces packages should be in the same version. . You should first upgrade the service (which in turn will upgrade your interface packages) and then update client.

**Comment by gparrington** [comment]
@suchiagicha I'm sorry but that's madness - and it didn't used to work that way. What you are saying is that I cannot use a newer version of the SDK in **my** code for services I do control simply because a 3rd part dll/interface **over which I have no control** is on a different earlier version. Until this change we frequently had different components (applications/services) on different SDK versions as their release cycles differed - indeed if the interface doesn't change services can go unchanged for months while the client evolves as required. This rename is a fundamental breaking change and will likely lock us to an old SDK version until we can guarantee the update the interface dlls
