### ISSUE TITLE
Backup and Restore feature error FABRIC_E_BACKUP_NOT_ENABLED

### ISSUE THREAD

**Issue by qmarc** [Azure/service-fabric-issues#1230]
We noticed after a short time of using the ASF backup and restore feature that warnings started appearing in the Microsoft-Service Fabric/Admin EventLog for example:

```
BAP on node 0xCA787072C62C9150x8A2DF3A55A41571C/apphost {50c4b5d3-4208-4487-b483-8ce0ba28e3a6}: End send request with ActivityId {56065bb0-3463-45f0-ac2f-1de5c3dd8319}:0 failure FABRIC_E_BACKUP_NOT_ENABLED.
```
and
```
BA on ca787072c62c9158a2df3a55a41571c:131783423845622947: Sending IPC failure message with activity id {56065bb0-3463-45f0-ac2f-1de5c3dd8319}:0 error FABRIC_E_BACKUP_NOT_ENABLED.
```

Here is the stack from beginning to end for the particular attempted backup task from the Fabric Traces file:
```
2018-8-16 23:54:59.749,Informational,3840,4420,BAP.BeginSend_BeginSend,BAP on node ca787072c62c9158a2df3a55a41571c/apphost 50c4b5d3-4208-4487-b483-8ce0ba28e3a6: Begin send request with ActivityId: ff75bdd3-4253-4245-9602-0cbbc490caf0:0 Actor BRS and Action GetBackupPolicyAction.

2018-8-16 23:54:59.749,Informational,3840,4420,BAP.BeginSend_BeginSend,BAP on node ca787072c62c9158a2df3a55a41571c/apphost 50c4b5d3-4208-4487-b483-8ce0ba28e3a6: Begin send request with ActivityId: ff75bdd3-4253-4245-9602-0cbbc490caf0:0 Actor BA and Action ForwardToBRSAction.

2018-8-16 23:54:59.749,Informational,3840,4420,Transport.Enqueue@2c622ed7070,1c4ec308-79c4-4e12-8149-b1c00a311cc1:43020 False  548B @ qsize 0/0B

2018-8-16 23:54:59.749,Informational,6560,416,Transport.Msg_Dispatch@1e786c96b30,1c4ec308-79c4-4e12-8149-b1c00a311cc1:43020 False 1 548B

2018-8-16 23:54:59.749,Informational,6560,416,BA.ProcessTransportIpcRequest_ProcessTransportIpcRequest,BA on ca787072c62c9158a2df3a55a41571c:131783423845622947: Received IPC message with activityid: ff75bdd3-4253-4245-9602-0cbbc490caf0:0 and messageid:1c4ec308-79c4-4e12-8149-b1c00a311cc1:43020.

2018-8-16 23:54:59.749,Informational,6560,416,BA.NodeToNodeAsyncOperation,ff75bdd3-4253-4245-9602-0cbbc490caf0:0 Routing message to node 48ff4c69978ac536f4ab07020b52a49c:131776393366038362

2018-8-16 23:54:59.749,Informational,6560,416,LeaseLayer.GetContainerLeasingTTL,Get TTL for Leasing application 131783423846422971 with request TTL 1000

2018-8-16 23:54:59.749,Informational,6560,416,LeaseAgent.TTL,ca787072c62c9158a2df3a55a41571c:131783423845622947@madeup-server-name.mydomain.local:19002 lease valid for 1000ms

2018-8-16 23:54:59.749,Informational,6560,416,P2P.Send@ForwardToBRSAction,ca787072c62c9158a2df3a55a41571c send message ForwardToBRSAction to 48ff4c69978ac536f4ab07020b52a49c:131776393366038362 id 1c4ec308-79c4-4e12-8149-b1c00a311cc1:43020 False (0)

2018-8-16 23:54:59.749,Informational,6560,416,Transport.Enqueue@1e78628ae30,1c4ec308-79c4-4e12-8149-b1c00a311cc1:43020 False  1160B @ qsize 0/0B

2018-8-16 23:54:59.753,Informational,1368,416,Transport.Msg_Dispatch@1e78628ae30,1c4ec308-79c4-4e12-8149-b1c00a311cc1:43020 True 1 2830B

2018-8-16 23:54:59.753,Informational,1368,416,P2P.Receive@RejectFault,ca787072c62c9158a2df3a55a41571c receive message RejectFault from 48ff4c69978ac536f4ab07020b52a49c:131776393366038362 id 1c4ec308-79c4-4e12-8149-b1c00a311cc1:43020 True (0)

2018-8-16 23:54:59.753,Warning,1368,416,BA.IpcSendFailure_IpcSendFailure,BA on ca787072c62c9158a2df3a55a41571c:131783423845622947: Sending IPC failure message with activity id ff75bdd3-4253-4245-9602-0cbbc490caf0:0 error FABRIC_E_BACKUP_NOT_ENABLED.

2018-8-16 23:54:59.753,Informational,1368,416,Transport.Enqueue@1e786c96b30,1c4ec308-79c4-4e12-8149-b1c00a311cc1:43020 True  170B @ qsize 0/0B

2018-8-16 23:54:59.754,Informational,1368,416,Routing.Complete,Routing of message 1c4ec308-79c4-4e12-8149-b1c00a311cc1:43020(1) header [From: ca787072c62c9158a2df3a55a41571c:131783423845622947, To: 48ff4c69978ac536f4ab07020b52a49c:131776393366038362, MessageId: 1c4ec308-79c4-4e12-8149-b1c00a311cc1:43020, Expiration: 59.999, RetryTimeout: 59.999, UseExactRouting: true, ExpectsReply: true] failed with FABRIC_E_BACKUP_NOT_ENABLED

2018-8-16 23:54:59.754,Informational,4700,4420,Transport.Msg_Dispatch@2c622ed7070,1c4ec308-79c4-4e12-8149-b1c00a311cc1:43020 True 1 170B

2018-8-16 23:54:59.754,Warning,2016,4420,BAP.EndSendFailure_SendFailure,BAP on node ca787072c62c9158a2df3a55a41571c/apphost 50c4b5d3-4208-4487-b483-8ce0ba28e3a6: End send request with ActivityId ff75bdd3-4253-4245-9602-0cbbc490caf0:0 failure FABRIC_E_BACKUP_NOT_ENABLED.

2018-8-16 23:54:59.754,Informational,2016,4420,SystemFabric.BackupRestoreWorker.GetBackupSchedulingPolicyAsync,AsyncCalloutAdapter-52766062: end delegate threw an exception
	System.Fabric.FabricTransientException: Indicates that the partition does not have read access. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C73
	   at System.Fabric.BackupRestore.Interop.NativeBackupRestoreRuntime.IFabricBackupRestoreAgent.EndGetBackupSchedulingPolicy(IFabricAsyncOperationContext context)
	   at System.Fabric.BackupRestore.BackupRestoreManager.GetBackupSchedulingPolicyEndWrapper(IFabricAsyncOperationContext context)
	   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
	   --- End of inner exception stack trace ---

2018-8-16 23:54:59.755,Error,2016,4420,SystemFabric.BackupRestoreManager,51f6bb78-3660-45c2-bf08-7ed339b5c5f3 Error encountered in BackupRestoreWorker InitializeAsync System.Fabric.FabricTransientException: Indicates that the partition does not have read access. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C73
	   at System.Fabric.BackupRestore.Interop.NativeBackupRestoreRuntime.IFabricBackupRestoreAgent.EndGetBackupSchedulingPolicy(IFabricAsyncOperationContext context)
	   at System.Fabric.BackupRestore.BackupRestoreManager.GetBackupSchedulingPolicyEndWrapper(IFabricAsyncOperationContext context)
	   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
	   --- End of inner exception stack trace ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Fabric.BackupRestore.BackupRestoreManager.<InitializeAsync>d__63.MoveNext()
```
This looks like an issue with the feature and is logging 2-3 times per minute, it would be great to stop the logs getting flooded with this error.

**Comment by hrushib** [comment]
@qmarc, please share the Service Fabric cluster version where you saw above error.
Is it standalone cluster or the one created in Azure (using SFRP - Service Fabric Resource Provider)

**Comment by qmarc** [comment]
Hi @hrushib, we are currently at v6.3.162.9494 and running an on-prem cluster. However after diving into the logs across all the cluster nodes across all our environments I do not see any entries for the above error at the moment, so I think we can close this one.
