### ISSUE TITLE
Cannot connect to the cluster using secondary certificate

### ISSUE THREAD

**Issue by uditjh** [Azure/service-fabric-issues#1232]
PS C:\Users\!accenadmin!> Connect-ServiceFabricCluster $clusterConnectionString -X509Credential -ServerCertThumbprint XXXX -FindType FindByThumbprint -FindValue XXXX -StoreLocation CurrentUser -StoreName My -Verbose
WARNING: Failed to contact Naming Service. Attempting to contact Failover Manager Service...
WARNING: Failed to contact Failover Manager Service, Attempting to contact FMM...
False
VERBOSE: System.Fabric.FabricServerAuthenticationFailedException: FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80
071C44
   at System.Fabric.Interop.NativeClient.IFabricQueryClient10.EndGetPartitionList2(IFabricAsyncOperationContext context)
   at System.Fabric.FabricClient.QueryClient.GetPartitionListAsyncEndWrapper(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
VERBOSE: System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   at System.Management.Automation.Cmdlet.ThrowTerminatingError(ErrorRecord errorRecord)
   at Microsoft.ServiceFabric.Powershell.CommonCmdletBase.TestClusterConnection(IClusterConnection clusterConnection, Boolean testNetwork)
   at Microsoft.ServiceFabric.Powershell.ConnectCluster.ProcessRecord()
VERBOSE: System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   at System.Management.Automation.Cmdlet.ThrowTerminatingError(ErrorRecord errorRecord)
   at Microsoft.ServiceFabric.Powershell.ConnectCluster.ProcessRecord()
Connect-ServiceFabricCluster : FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched
At line:1 char:1
+ Connect-ServiceFabricCluster $clusterConnectionString -X509Credential ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Connect-ServiceFabricCluster], FabricServerAuthenticationFailedException
    + FullyQualifiedErrorId : TestClusterConnectionErrorId,Microsoft.ServiceFabric.Powershell.ConnectCluster

**Comment by gkhanna79** [comment]
@uditjh I presume you have taken a look at https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-security#node-to-node-certificate-security and followed the instructions?

**Comment by dragav** [comment]
@uditjh the error code indicates that the client could not authenticate the server according to the parameters you supplied. A few things to check/questions:
- is this a Windows or Linux cluster? is the cluster functional/up and running?
- is it a secure cluster? if so, is the server certificate declared by thumbprint or common name? is the certificate installed on every node of the cluster, in the Local machine\My store?
- is the server certificate valid?

You can take a look at the cluster's manifest to confirm the configured certificates match the command line input you are providing. 

Hope this helps, please let us know if it doesn't. Thanks.

**Comment by uditjh** [comment]
* is this a Windows or Linux cluster? is the cluster functional/up and running? - Windows and Yes its running
* is it a secure cluster? if so, is the server certificate declared by thumbprint or common name? is the certificate installed on every node of the cluster, in the Local machine\My store? - Yes its a secured cluster with a digicert issued certificate
* is the server certificate valid? - Yes its very much valid
We are still running into this issue. We cannot use secondary certificates to authenticate using service fabric powershell. We just tested this against the latest service fabric runtime.

**Comment by mchiaramonte** [comment]
I know this is from over a year ago but did you ever find a solution to this? I'm seeing the same behavior.

**Comment by dragav** [comment]
I don't believe we have a problem here, except perhaps that it may not be clear what each of parameters of the cmdlet represent, or the cluster's expected behavior. 

-X509Credential : self-evident
-ServerCertThumbprint: this is the thumbprint of the certificate expected to be presented by the cluster as a server. Note that:
    - If the cluster is configured with different certificates for its 'cluster' and 'server' roles, this will be the latter. 
    - If the cluster is configured with multiple certificates (primary and secondary, or with a common name-based certificate), the certificate presented by the server depends on the available certificates on the node you happen to be routed to. That is, if the primary expires farther into the future than the secondary, it will present the primary (even if it is older). If the secondary expires later (higher NotAfter) but it is not installed on that node, the server will present the primary. If the cert is declared by CN, the server will present the farthest-expiring matching cert found on the node you're routed to.

The gist is that you may not always be able to make an assertion "server cert TP == X".

The remainder of the parameters refer to the client certificate, and I assume they were/are specified correctly (-FindType FindByThumbprint -FindValue XXXX -StoreLocation CurrentUser -StoreName My).

**Comment by mchiaramonte** [comment]
Oh! You're right. Thanks so much for explaining this.
