### ISSUE TITLE
FabActUtil.exe fail with MSBuild 15.8 and Service Fabric SDK 3.2

### ISSUE THREAD

**Issue by rnilsark** [Azure/service-fabric-issues#1248]
FabActUtil.exe fails when running 
msbuild.exe "C:\git\XXX\src\YYY\Y.sfproj" /t:Package /p:PackageLocation=QQQ /p:platform="x64" /p:configuration="Debug" /p:VisualStudioVersion="15.0"

According to log, FabActUtil tries to find `.nuget/packages/microsoft.servicefabric.actors/3.2.176/build/net45/Microsoft.ServiceFabric.Actors/Microsoft.ServiceFabric.Actors.DLL` but it does not exist. (it does in .nuget\packages\microsoft.servicefabric.actors\3.2.176\build\netcoreapp2.0).

**Service Fabric SDK**: 3.2.176
**MsBuild** 158.168.64424

**Target framework** is 4.6.1

Any idea? Error message below

```
"C:\Users\XXX\.nuget\packages\microsoft.servicefabric.actors\3.2.176\build\net45\\FabActUtil.exe" /app:"C:\git\YYY\src\ZZZ\ApplicationPackageRoot" /spp:"PackageRoot" /t:manifest /ap:"ZZZ
  " /sp:"WWW" /in:"bin\Debug\net461\win7-x64\\WWW.Exe" /arp:"C:\git\YYY\src\WWW\bin\Debug\net461\win7-x64\\" /local5nodeappparamfile:"C:\git\YYY\src\ZZZ\ApplicationParameters\Local.5Node.xml" /local1nodeappparamfile:"C:\git\YYY\src\ZZZ\ApplicationParameters\Local.1Node.xml"
  System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ServiceFabric.Actors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
  File name: 'Microsoft.ServiceFabric.Actors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
     at FabActUtil.ToolContext..ctor()
     at FabActUtil.Tool.Run(ToolArguments arguments)
     at FabActUtil.Program.Main(String[] args)

  === Pre-bind state information ===
  LOG: DisplayName = Microsoft.ServiceFabric.Actors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
   (Fully-specified)
  LOG: Appbase = file:///C:/Users/XXX/.nuget/packages/microsoft.servicefabric.actors/3.2.176/build/net45/
  LOG: Initial PrivatePath = NULL
  Calling assembly : FabActUtil, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
  ===
  LOG: This bind starts in default load context.
  LOG: No application configuration file found.
  LOG: Using host configuration file:
  LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
  LOG: Post-policy reference: Microsoft.ServiceFabric.Actors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  LOG: Attempting download of new URL file:///C:/Users/XXX/.nuget/packages/microsoft.servicefabric.actors/3.2.176/build/net45/Microsoft.ServiceFabric.Actors.DLL.
  LOG: Attempting download of new URL file:///C:/Users/XXX/.nuget/packages/microsoft.servicefabric.actors/3.2.176/build/net45/Microsoft.ServiceFabric.Actors/Microsoft.ServiceFabric.Actors.DLL.
  LOG: Attempting download of new URL file:///C:/Users/XXX/.nuget/packages/microsoft.servicefabric.actors/3.2.176/build/net45/Microsoft.ServiceFabric.Actors.EXE.
  LOG: Attempting download of new URL file:///C:/Users/XXX/.nuget/packages/microsoft.servicefabric.actors/3.2.176/build/net45/Microsoft.ServiceFabric.Actors/Microsoft.ServiceFabric.Actors.EXE.
```

**Comment by rnilsark** [comment]
I finally managed to package the app by simply omitting /p:Platform="x64". On the other hand, without that setting I have trouble building a solution based on SDK 2.8. 

So Im still interested in any clues why this suddely became a problem...

**Comment by amanbha** [comment]
@rnilsark  Is it a .net core project? +@ravipal for help as well.
