### ISSUE TITLE
F5 fails with ASP.NET Core 2.1 and "https" endpoint

### ISSUE THREAD

**Issue by inech** [Azure/service-fabric-issues#1285]
**Service Fabric SDK:** 3.2.176.9494
**Visual Studio 2017:** 15.8.5 / 15.9.0 Preview 2.0 (tried both)
**Reproduction instruction:**
1. Run VS as an Admin
2. Create a new SF project `Stateless ASP.NET Core`
3. Select ASP.NET Core 2.1 (in the top) then choose API project and check "Configure for HTTPS"
4. Press 'F5' 
5. It asks
![image](https://user-images.githubusercontent.com/17814060/45947158-e8e7c500-bffb-11e8-98bf-ee711beeccf6.png)
6. Click "OK" (because clicking Cancel just stops deployment)
7. Deployment fails and I see error in log
> Adding the certificate to the Trusted Root Certficates store failed with the following error: Failed with a critical error.

I was able to attach to Visual Studio and catch this exception:
>    at Microsoft.VisualStudio.Containers.Tools.Common.Services.SSL.AspNetCoreDeveloperCertificatesTool.ProcessExitCode(CertToolStatusCodes exitCode)
   at Microsoft.VisualStudio.Containers.Tools.Common.Services.SSL.AspNetCoreDeveloperCertificatesTool.<ExecuteTimedOperationAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Containers.Tools.Common.Services.SSL.AspNetCoreDeveloperCertificatesTool.<ExportCertficateAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.ProjectSystem.AspNetSSLCertificateManager.<EnsureAspNetSSLCertificateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.ProjectSystem.ApplicationProvider.<EnsureSSLCertForSecureASPCore21VS150Async>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.ProjectSystem.ApplicationProvider.<EnsureSSLCertForSecureASPCore21Async>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.ProjectSystem.ApplicationProvider.<PublishAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.ProjectSystem.ApplicationProvider.<PublishAsync>d__68.MoveNext()

**Workarounds:**
1. I can deploy and debug ASP.NET Core 2.1 when I change an endpoint from "https" to "http" in ServiceManifest.
2. It's still possible to "Publish" ASP.NET Core 2.1 application to a cluster (though as described in this issue you can't use with 'F5' and debug it).
3. F5 works well when I use ASP.NET Core 2.0 either with http or https in ServiceManifest.

**Comment by guibirow** [comment]
Seems like a permission issue!
Are you running VS as Administrator?
if yes, are you able to run the application with HTTPs without deploying to SF?

**Comment by inech** [comment]
Yes, I run Visual Studio from Admin when I work with SF.
If I create new ASP.NET Core 2.1 application with HTTPS but without SF it works well and I can make a request to this HTTPS localhost endpoint and get a response without any HTTPS errors.

**Comment by Quass1m** [comment]
Same issue here. Started after upgrading from 15.7.6 to 15.8.5. I tried cleaning self-issues development certificate using "dotnet dev-certs https --clean" but nothing changed. My app is on ASP.NET Core 2.1 and I am not able to revert to 2.0.

**Comment by dbreshears** [comment]
This appears to be what is failing.   Can you try to run this from the command line?  

dev-certs https -ep <path> -p <password>

**Comment by Quass1m** [comment]
I've tried it. The result was "The HTTPS developer certificate was generated successfully.". Still getting same error while trying to debug with HTTPS.

**Comment by ravipal** [comment]
@Quass1m do you see the same error "Adding the certificate to the Trusted Root Certficates store failed with the following error: Failed with a critical error." and the call stack mentioned by @inech ?
During debug, VS runs the same "dotnet dev-certs https -ep <path> -p <password>" command.

**Comment by Quass1m** [comment]
Yes, that is exactly the error message. Runnig "dotnet dev-certs https -c" returns "A valid HTTPS certificate is already present."

**Comment by ravipal** [comment]
@Quass1m Can you please try the exact cmd used by VS `dotnet dev-certs https -ep <path> -p <password>` and see if the export works?

**Comment by Quass1m** [comment]
Using "Developer Command Prompt for VS 2017" gives me the same, correct result.

**Comment by inech** [comment]
When I run `dotnet dev-certs https -ep C:\temp\cert.pfx -p 123456` from VS Developer command prompt I see: `A valid HTTPS certificate is already present. and valid certificate is created at _C:\temp\cert.pfx,_ but I still have this problem.

**Comment by inech** [comment]
I've found a workaround.

1. Export certificate `dotnet dev-certs https -ep C:\temp\cert.pfx -p 123456` (at this point certificate is only installed to User certificates store).
2. Install `cert.pfx` to Local machine certificate store (to Personal and to Trusted Root Certification Authrotities).
3. Run Service Fabric - now the prompt is not displayed and everything works smooth!

**Comment by Quass1m** [comment]
@inech that very simple procedure fixed it for me as well. Thank you!

**Comment by dbreshears** [comment]
Closing older issue.  Haven't been able to reproduce with asp.net core 3 with https on F5 and appears there are workaround steps to resolve if it does
