### ISSUE TITLE
VSTS SF PowerShell task fails to determine Admin role

### ISSUE THREAD

**Issue by mikanyg** [Azure/service-fabric-issues#1325]
We have a VSTS deployment pipeline that uses the Service Fabric Powershell task to deploy the PatchOrchestrationApplication (POA) to our cluster in order to streamline upgrades to POA.

Wanted to upgrade to the latest 1.22.0 version of POA but the deployment currently fails with the following message: 
```
IsAdminRole failed: issuer=https://sts.windows.net/<some-guid>/ audience=<some-guid> roleClaim=http://schemas.microsoft.com/ws/2008/06/identity/claims/role cert=https://login.microsoftonline.com/<some-guid>/federationmetadata/2007-06/federationmetadata.xml error=System.ArgumentException: IDX10708: 'System.IdentityModel.Tokens.JwtSecurityTokenHandler' cannot read this string: '_Invalid_'.
The string needs to be in compact JSON format, which is of the form: '<Base64UrlEncodedHeader>.<Base64UrlEncodedPayload>.<OPTIONAL, Base64UrlEncodedSignature>'.
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ReadToken(String tokenString)
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateToken(String securityToken, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at System.Fabric.AzureActiveDirectory.Server.ServerUtility.ValidateJwt(String expectedIssuer, String expectedAudience, String certEndpoint, String jwt)
   at System.Fabric.AzureActiveDirectory.Server.ServerUtility.Validate(String expectedIssuer, String expectedAudience, String expectedRoleClaimKey, String expectedAdminRoleValue, String expectedUserRoleValue, String certEndpoint, Int64 certRolloverIntervalTicks, String jwt)
   at IsAdminRole(Char* expectedIssuer, Char* expectedAudience, Char* expectedRoleClaimKey, Char* expectedAdminRoleValue, Char* expectedUserRoleValue, Char* certEndpoint, Int64 certRolloverCheckIntervalTicks, Char* jwt, Boolean* isAdmin, Int32* expirationSeconds, Char* errorMessageBuffer, Int32 errorMessageBufferSize)
```

We use AAD auth against the cluster and the service account used by the VSTS SF connection is valid and in the Cluster Admin role. We are using a private VSTS agent that has latest SF SDK installed (3.2.187). This used to work just fine. 

Looking at the VSTS logs when executing the Upgrade.ps1 script in the POA package, it appears to be the `Start-ServiceFabricApplicationUpgrade` cmdlet that fails. The `Copy-ServiceFabricApplicationPackage` and `Register-ServiceFabricApplicationType` cmdlets authenticates just fine and executes without errors.

Any known issues with either `Start-ServiceFabricApplicationUpgrade` cmdlet or the VSTS SF PowerShell task that we need to be aware of?

**Comment by mikanyg** [comment]
Appeared to be a misconfigured application version number passed to the `Start-ServiceFabricApplicationUpgrade` cmdlet so I'm closing the issue. But the exception does not indicate that this was the issue which is quite confusing.
