### ISSUE TITLE
Cluster node stuck in reboot loop

### ISSUE THREAD

**Issue by CodedBeard** [Azure/service-fabric-issues#1360]
Yesterday, we noticed an error in SF explorer for a container application, where it was failing to deploy to node 0 in the cluster. We logged into the node and discovered that some sort of bug in docker had resulted in loads of 8GB layers being created that had used all the space on the drive.

After discovering this, we tried running "docker image prune --all" to clear up some space, but this only freed up a tiny amount of space, even though docker reported no running/stopped containers, and no longer having any images. Whilst trying to figure out what was going on, the node suddenly stopped responding. when we checked it appears the node had crashed and was now failing to even boot at all.

At this point i decided to just tell the portal to re-provision the VMSS instance for node 0, which did bring up a new instance shortly afterwards, however, SF does not come up properly (explorer shows the node as down) with the following warning being repeatedly logged on the node:
```
ERROR: Microsoft.Azure.ServiceFabric.Extension.Core.AgentException: The device is not ready.

   at Microsoft.Azure.ServiceFabric.Extension.Core.Common.RetryHelper.ExecuteGenericFunc[T,TException](Func`1 func)
   at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.<RunOnce>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.<RunAsync>d__92.MoveNext()
```
Any tips on how to get the node to come back online? as far as i can tell everything is in place, but the node keeps restarting every 30 mins and never comes online.

**Comment by CodedBeard** [comment]
Figured this out yesterday. Turns out when the node was re-imaged, it booted with the drives mapped to different letters, with the virtual dvd drive getting the letter of the service fabric data drive. After switching the drive letters back to the correct order, the bootstrap agent kicked in and repaired the node. The cluster is now back up and running as normal.
