### ISSUE TITLE
service always failed after upgrading to 6.1.467

### ISSUE THREAD

**Issue by aiguang** [Azure/service-fabric-issues#1381]
I have 15 services in my project. After upgrading from 5.x to 6.1.467, most services were normal, but 5 services always failed. found following errors from Diagnostics Event, but didn't got more useful information. Anyone know why this happened?

Message": "Partition=e83c329a-e6b9-4f24-81fc-206b27d277fc StatelessInstance=131887540647055179 SourceId=System.RA Property=ReplicaOpenStatus HealthState=Warning TTL=922337203685477ms SequenceNumber=131887543927338594 Description='Replica had multiple failures during open on _Node_0. API call: IStatelessServiceInstance.Open(); Error = System.TypeInitializationException (-2146233036)
    The type initializer for 'Microsoft.ServiceFabric.Services.ServiceTrace' threw an exception.
       at Microsoft.ServiceFabric.Services.ServiceTrace.GetTraceIdForReplica(Guid partitionId, Int64 replicaId)
       at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter..ctor(StatelessServiceContext context, IStatelessUserServiceInstance userServiceInstance)
       at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceFactory.System.Fabric.IStatelessServiceFactory.CreateInstance(String serviceTypeName, Uri serviceName, Byte[] initializationData, Guid partitionId, Int64 instanceId)
       at System.Fabric.ServiceFactoryBroker.<>c__DisplayClass9_0.<CreateInstance>b__0(IStatelessServiceFactory factory, ServiceInitializationParameters initParams)
       at System.Fabric.ServiceFactoryBroker.CreateHelper[TFactory,TReturnValue](IntPtr nativeServiceType, IntPtr nativeServiceName, UInt32 initializationDataLength, IntPtr nativeInitializationData, Guid partitionId, Func`3 creationFunc, Action`2 initializationFunc, ServiceInitializationParameters initializationParameters)
    For more information see: http://aka.ms/sfhealth' RemoveWhenExpired=False SourceUTCTimestamp=12/08/2018 14:53:12 ",

**Comment by aiguang** [comment]
@nrandell , what's the version you are using now?

**Comment by nrandell** [comment]
So I'm using nuget 3.2.187 for `Microsoft.Servicefabric.Services` which pulls in 6.3.187 of `Microsoft.ServiceFabric`.

My cluster was 6.3.187.9494 - but checking this morning it has been upgraded :-)

I've seen this before when the latest release of the nuget libraries is not compatible with an earlier version of the cluster. It's frustrating, but I would rather see things move forwards and improve with a bit of pain, than do backwards compatability forever which slows down innovation!

**Comment by raunakpandya** [comment]
The guidance is to upgrade the cluster first before you upgrade your services to consume the new SDK. Can you clarify that the version of cluster and apps when you upgraded from 5.x?

**Comment by masnider** [comment]
@nrandell Did you update the nuget package and installed all the package dependencies? that should have pulled in required dependencies.

Starting with 5.7 Microsoft.ServiceFabric.Services , Microsoft.ServiceFabric.Services.Remoting & Microsoft.ServiceFabric.Actors nuget package depends on Microsoft.ServiceFabric.Diagnostics.Internal nuget package also.

**Comment by nrandell** [comment]
It's all working for me now. I'm pretty sure the problem was the latest nuget packages not being compatible with the earlier cluster version. I had already sorted out the problem myself, but just commented on this thread in case it would help someone.
