### ISSUE TITLE
AggregateException on Start-ServiceFabricClusterConfigurationUpgrade

### ISSUE THREAD

**Issue by mispencer** [Azure/service-fabric-issues#1411]
I attempted to run `Start-ServiceFabricClusterConfigurationUpgrade` on in-premise production cluster today and received the error below. I then downloaded the current cluster configuration (using ` Get-ServiceFabricClusterConfiguration`), updated the config version, and attempted `Start-ServiceFabricClusterConfigurationUpgrade` with that current configuration but I received the same error.

I have been able to run `Start-ServiceFabricClusterConfigurationUpgrade` in past as recently as the last few days. We just upgraded to SF version 6.4.622.9590 as of today. We also added new two nodes to cluster today (thus the attempted configuration update). 

As this error message is generic, I am unsure what to attempt from here. Is there any way to receive more information on what is failing or any known resolution to this issue we are experiencing?

```
VERBOSE: System.Fabric.FabricException: System.Runtime.InteropServices.COMException (-2147017627)
AggregateException: One or more errors occurred.
 ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C65
   at
System.Fabric.Interop.NativeClient.IFabricClusterManagementClient10.EndUpgradeConfiguration(IFabricAsyn
cOperationContext context)
   at
System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationCo
ntext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean
 expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
Start-ServiceFabricClusterConfigurationUpgrade : System.Runtime.InteropServices.COMException (-2147017627)
AggregateException: One or more errors occurred.
At line:1 char:1
+ Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath C:\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Start-ServiceFa
   ...gurationUpgrade], FabricException
    + FullyQualifiedErrorId : StartClusterConfigurationUpgradeErrorId,Microsoft.ServiceFabric.Powershell.StartClusterC
   onfigurationUpgrade
```

**Comment by b47on** [comment]
Last week, I've been trying to upgrade a configuration on 4 standalone clusters (on premises), 2 x 1 node, 2 x  3 node cluster. They were either freshly installed as 6.4.622 or installed as 6.4.617 and upgraded to 6.4.622. 
To my best knowledge, the only thing I was trying to change was the range of ports reserved for applications (and ephemeral ports)
Every time I've started the upgrade ("Start-ServiceFabricClusterConfigurationUpgrade") I had got either Timeout exception or internal exception thrown.

The results vary:
1st single node cluster did not survive, it did not start. (I had reinstalled a new one)
2nd single node cluster showed up, the ports are new in the manifest, but it logged a health warning, stating that manifest versions vary and that I should start a configuration upgrade to fix it :-)
The 3 node clusters upgraded the configuration (despite the exception thrown by Start-ServiceFabricClusterConfigurationUpgrade) 

All the problems seem to have started with 6.4 version, I've made many configuration upgrades with 6.3 without any problems or exceptions thrown.

**Comment by b47on** [comment]
The 3 node cluster I upgraded, started to log a warning today too:
`Unhealthy event: SourceId='System.UpgradeOrchestrationService', Property='ManifestVersionMismatch', HealthState='Warning', ConsiderWarningAsError=false.
Mismatched cluster manifest versions: 1 0. Please perform a config upgrade to sync manifest state.`

`Get-ServiceFabricClusterConfigurationUpgradeStatus` returns
'           UpgradeState ProgressStatus ConfigVersion Details
           ------------ -------------- ------------- -------
RollingForwardCompleted              1 1.2.0'

**Comment by mispencer** [comment]
After testing, I only get this error when attempting to add a new node in the configuration. I was able to get pass this error by supplying the DNS name for the new node, instead of the IP address. I assume whatever SF is doing to connect to the new node (Powershell remoting?) works on the dns name, but not on the IP address.

**Comment by Adebeer** [comment]
I'm stuck with a similar issue and desperately need help - I can't do config upgrade after adding new nodes on an existing on-premise cluster. 

Essentially:
- Cluster running 6.4.637.9590, using gMSA
- I've followed in MSDOC instructions to add 5 new nodes (run .AddNode.ps). 
- Add node worked just fine and no errors reported in SF Explorer. 
- Get-ServiceFabricClusterConfiguration returns correct info with all new nodes in place
- Cluster Manifest is however still out of date showing only the original 6 nodes. I presume this is why one has to run a config upgrade as per [MSDOC](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-windows-server-add-remove-nodes)
- As such, exported json from the Get cluster config ps script, updated version number and ran `Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath updated.json -Verbose -Debug
- ApiVersion in json file is "06-2018"

Unfortunately getting same error as above:
```
VERBOSE: System.Fabric.FabricException: System.Runtime.InteropServices.COMException (-2147017627)
AggregateException: One or more errors occurred.
 ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C65
   at System.Fabric.Interop.NativeClient.IFabricClusterManagementClient10.EndUpgradeConfiguration(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
Start-ServiceFabricClusterConfigurationUpgrade : System.Runtime.InteropServices.COMException (-2147017627)
AggregateException: One or more errors occurred.
At line:1 char:1
+ Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath "AL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Start-ServiceFa...gurationUpgrade], FabricException
    + FullyQualifiedErrorId : StartClusterConfigurationUpgradeErrorId,Microsoft.ServiceFabric.Powershell.StartClusterConfigurationUpgrade
```

Other notes:
- This is a production cluster - so can't re-create it
- existing 6 nodes are in DC1
- new 6 nodes are in DC2
- Once I get above working, will be adding 6 more nodes in DC3
- all nodes using FQDN format - no IP addresses. We're using gMSA windows security

How can I obtain more info regarding root cause of this error?

**Comment by mispencer** [comment]
@Adebeer If I recall correctly, AddNode.ps1 doesn't add nodes properly on a cluster using gMSA. You need to remove any nodes you added using AddNode.ps1, and add them properly by adding them to the cluster json, and running a config update. If that fails, check that you can connect using PS remoting from an existing node to the new node (using the same ip address/dns name as in the cluster json), and that the cluster user is an administrator on the new node. I had to add it to the local administrator group, but I am not sure this is a requirement.

**Comment by Adebeer** [comment]
Thanks for your input @mispencer 

The issue of not using AddNode is that you still need some way of installing the runtime on the node as I doubt that a config update alone would be enough to install service fabric on the newly added nodes. Any ideas?

The [MSDOCs](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-windows-server-add-remove-nodes) do say you must initiate a config update after using AddNode - and as far as I can tell, the AddNode.ps1 script worked just fine. There is a RemoveNode.ps1 and looking at it's parameters, I don't think this supports gMSA - but this script is also not mentioned in the MSDOCs - so likely this is the one you were thinking of??

It would be good if one of the MS Service Fabric folk can comment on this issue.

As far as I know, gMSA is the [recommended](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-windows-cluster-windows-security#configure-windows-security-using-gmsa) windows security choice and , to quote MS: 

> We strongly recommend using the Group Managed Service Account (gMSA) approach, particularly for larger clusters (more than 10 nodes) or for clusters that are likely to grow or shrink.

As such - I would expect MS to have a documented approach to adding/removing nodes - afterall, this is such a fundamental and critical requirement for a microservices cluster... otherwise I think SF should be labelled alpha/technical preview, at best.

I suspect/hope it's merely a bug/environmental issue that prevents the config upgrade!

**Comment by Adebeer** [comment]
@mispencer I'm just looking at the feedback section of the aforementioned MSDOCs and I can see some related discussions in there. It *seems* like what one has to do is install the Fabric SDK on the node first and then use a config upgrade. So, it looks like your memory has served you well, indeed!

I will try this...although not sure how to go about deleting the nodes I've already added to the cluster as one is to do a "config" upgrade for this. There is a suggested solution involving some [hackery](https://github.com/Azure/service-fabric-issues/issues/772) - so I may try this if I get desperate

I hope though we can get better/official clarity/support from MS on this critical workflow

**Comment by Adebeer** [comment]
@mispencer:
 Ok - I have this working just fine now! The [MSDOC](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-windows-server-add-remove-nodes) do actually contain a specific section on how to add gMSA nodes for gMSA secured clusters - not sure how I missed this section! It's actually much simpler - don't use AddNode.ps1 - simply do a configuration upgrade - but do one node at a time.

In my case though, I had to do a bit of extra work to undo the damage I did via the AddNode script. I couldn't remove the newly added nodes via a config upgrade. However, for each node I simply:

- Used Add/Remove programs to uninstall service fabric
- In SF explorer (which now should show node as being Down), simply remove node state.

**Comment by NArnott** [comment]
I'm having the same vague AggregateException when trying to add a new node to an existing gMSA on-prem cluster. Per the docs, I just add the node to the config file (not using the AddNode.ps1). Once I add the new node and run Start-ServiceFabricClusterConfigurationUpgrade, I get the exception. 

I've confirmed that if I get the latest config for the cluster ServiceFabricClusterConfiguration, and only update the version number, it does the rolling upgrade just fine, so my cluster is in a good state. However, once I add the new node to the nodes section, no go.

I'm playing with a test cluster, so I am able to rebuild on demand to help figure this out. I've attached both the original cluster config, and the updated one with the new node.

[ClusterConfigs.zip](https://github.com/Azure/service-fabric-issues/files/3188738/ClusterConfigs.zip)

**Comment by chenzuo** [comment]
PS C:\sf> .\TestConfiguration.ps1 -ClusterConfigFilePath .\update.json -OldClusterConfigFilePath .\current.json -Verbose -FabricRuntimePackagePath C:\MicrosoftAzureServiceFabric.6.5.639.9590.cab
详细信息: 执行带有以下参数的操作“查询 CimInstance”:“'queryExpression' = SELECT * FROM Win32_LogicalDisk WHERE DeviceId='C:','queryDialect' =
WQL,'namespaceName' = root\cimv2”。
详细信息: 完成操作“查询 CimInstance”。
详细信息: 执行带有以下参数的操作“查询 CimInstance”:“'queryExpression' = SELECT * FROM Win32_LogicalDisk WHERE DeviceId='C:','queryDialect' =
WQL,'namespaceName' = root\cimv2”。
详细信息: 完成操作“查询 CimInstance”。
Trace folder already exists. Traces will be written to existing trace folder: C:\sf\DeploymentTraces
Running Best Practices Analyzer...
Diagnostics Store is not a file share. Please consider using a file share accessible from all cluster machines, collecting logs in a local folder is inconvenient.
Running Best Practices Upgrade Analyzer. Please make sure you are validating against the current cluster json config in your cluster. Cluster configuration in the system may change after you add or remove node which means the original cluster json config can't represent the cluster state anymore. You can get the latest configuration by Get-ServiceFabricClusterConfiguration in Powershell.
Best Practices Analyzer completed successfully.


LocalAdminPrivilege        : True
IsJsonValid                : True
IsCabValid                 : True
RequiredPortsOpen          : True
RemoteRegistryAvailable    : True
FirewallAvailable          : True
RpcCheckPassed             : True
NoDomainController         : True
NoConflictingInstallations : True
FabricInstallable          :
DataDrivesAvailable        : True
DrivesEnoughAvailableSpace : True
Passed                     : True



PS C:\sf> Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath .\update.json -Verbose
详细信息: System.Fabric.FabricException: System.Runtime.InteropServices.COMException (-2147017627)
ValidationException: Authentication type cannot be changed from unsecured to Windows.
 ---> System.Runtime.InteropServices.COMException: 异常来自 HRESULT:0x80071C65
   在 System.Fabric.Interop.NativeClient.IFabricClusterManagementClient10.EndUpgradeConfiguration(IFabricAsyncOperationContext context)
   在 System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context)
   在 System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
   --- 内部异常堆栈跟踪的结尾 ---
Start-ServiceFabricClusterConfigurationUpgrade : System.Runtime.InteropServices.COMException (-2147017627)
ValidationException: Authentication type cannot be changed from unsecured to Windows.
所在位置 行:1 字符: 1
+ Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath .\u ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Start-ServiceFa...gurationUpgrade]，FabricExcep
    tion
    + FullyQualifiedErrorId : StartClusterConfigurationUpgradeErrorId,Microsoft.ServiceFabric.Powershell.StartClusterConfigurationUpgrade

**Comment by antone405** [comment]
For me. I had neglected to add the gMSA account to the Local Administrators group on all the boxes already in the cluster as well as those that I planned to add. The nodes added as expected.

`Add-LocalGroupMember -Group Administrators -Member DOMAIN\gMSA-ACCOUNT$`

Note the **$** at the end.
