### ISSUE TITLE
Add-AzureRmServiceFabricApplicationCertificate got Azure KeyVault BadRequest Exception

### ISSUE THREAD

**Issue by shiweiwei114** [Azure/service-fabric-issues#1484]
Trying to follow the [doc ](https://docs.microsoft.com/en-us/powershell/module/azurerm.servicefabric/add-azurermservicefabricapplicationcertificate?view=azurermps-6.13.0#code-try-4)to create a self-signed certificate in the Azure key vault with the key vault resource group name and key vault Name, installs to all node types of the cluster, and downloads the certificate under folder 'c:\test', but got the Azure KeyVault BadRequest error.

**PS:**
$pwd = ConvertTo-SecureString -String '1234' -AsPlainText -Force
>> Add-AzureRmServiceFabricApplicationCertificate -ResourceGroupName 'NonProd-XXXX' -Name 'xxxx-dev' -KeyVaultName 'xxxx-dev' -KeyVaultResouceGroupName 'NonProd-XXXX' -CertificateSubjectName 'cn=test.cert.test' -CertificateOutputFolder 'c:\Cert' -CertificatePassword $pwd

**Error:**
Add-AzureRmServiceFabricApplicationCertificate : 7:32:42 PM - System.AggregateException: One or more errors occurred. ---> Microsoft.Azure.KeyVault.Models.KeyVaultErrorException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.KeyVault.KeyVaultClient.<CreateCertificateWithHttpMessagesAsync>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.<CreateCertificateAsync>d__68.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Commands.ServiceFabric.Commands.ServiceFabricClusterCertificateCmdlet.CreateSelfSignedCertificate(String subjectName, String keyVaultUrl, String& thumbprint, CertificateBundle& certificateBundle, String& outputFilePath)
---> (Inner Exception #0) Microsoft.Azure.KeyVault.Models.KeyVaultErrorException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.KeyVault.KeyVaultClient.<CreateCertificateWithHttpMessagesAsync>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.<CreateCertificateAsync>d__68.MoveNext()<---
At line:2 char:1
+ Add-AzureRmServiceFabricApplicationCertificate -ResourceGroupName 'No ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AzureRmServ...tionCertificate], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ServiceFabric.Commands.AddAzureRmServiceFabricApplicationCertificate

It seems like it's complaining the Bad input, but I am not quite sure which param cause the problem:
Microsoft.Azure.Commands.ServiceFabric.Commands.ServiceFabricClusterCertificateCmdlet.CreateSelfSignedCertificate(String subjectName, String keyVaultUrl, String& thumbprint, CertificateBundle& certificateBundle, String& outputFilePath)

**Comment by shiweiwei114** [comment]
I found the issue is **CertificateSubjectName 'cn=test.cert.test'**. Shouldn't put "cn" in front of the subject name, it will automatically add "cn" for you after you run this command.
