### ISSUE TITLE
Unable to start FabricHostSvc in standalone cluster

### ISSUE THREAD

**Issue by suvamM** [Azure/service-fabric-issues#1528]
I am trying to setup a 5-node stand-alone Service Fabric cluster. All my machines are running Windows Server 2016. My cluster configuration is ClusterConfig.Unsecure.MultiMachine, with the IP addresses of the nodes filled in. The testing phase runs fine. When I try to create the cluster, FabricHostSvc starts up on all nodes except the one from which I am running the script (also defined to be node0). For this node, there is a timeout exception.

I tried making node0 a different machine, and the exact same thing occurs. FabricHostSvc installs for all nodes, but fails to start up for node0.

The nodes have been carefully setup as instructed. The necessary ports are open, and the required services (Remote Registry, for example) are running.

The error I am receiving is:

```
Timed out waiting for Installer Service to complete for machine 10.150.42.86. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
CreateCluster Error: System.AggregateException: One or more errors occurred. ---> System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete for machine 10.150.42.86. Investigation order: FabricInstallerS
ervice -> FabricSetup -> FabricDeployer -> Fabric
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(String machineName, ServiceController installerSvc, TimeSpan timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndWaitForInstallerService(String machineName, Nullable`1 timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass20_0.<RunFabricServices>b__0(String m)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLoc
al, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWi
thEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.RunFabricServices(MachineHealthContainer machineHealthContainer, FabricPackageType fabricPackageType, TimeSpan timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
---> (Inner Exception #0) System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete for machine 10.150.42.86. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(String machineName, ServiceController installerSvc, TimeSpan timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndWaitForInstallerService(String machineName, Nullable`1 timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass20_0.<RunFabricServices>b__0(String m)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
```

What is the issue here?

**Comment by maburlik** [comment]
Are you deploying from node0? Try looking at the Service Fabric event traces through Event Viewer.

**Comment by masnider** [comment]
Hi @suvamM, we haven't heard back from you in a while so I'm going to close this issue down. If you're still experiencing this issue with a more recent release, please either reopen this issue or create a new one. Thanks!
