### ISSUE TITLE
File system limitation error when adding new Nodes

### ISSUE THREAD

**Issue by Adebeer** [Azure/service-fabric-issues#1530]
I'm adding new nodes to an existing cluster via the configuration upgrade approach, but getting cluster warning: `The requested operation could not be completed due to a file system limitation (Exception from HRESULT: 0x80070299)` .

I've been able to add non-primary (i.e. non-seed) nodes just fine, however when trying to add new nodes as primary node type I get this warning - reported by the FaultAnalysisService and UpgradeOrchestrationService components against the newly added node. The node remains in InBuild status as IdleSecondary.

Other info:

- Version of SF: 6.4.664.9590
- Existing nodes are all Windows Server Windows Server 2016. 
- Cluster secured via GMSA
- New nodes I'm adding are Windows Server 2019 Core _(this may not be related to issue; also, these new nodes are hosted in different Data centre and hardware to other/existing nodes)_. 
- Note: SF Team Blog has confirmed “We now support Windows Server 2019 and Windows Server 1809 for Azure and Standalone Service Fabric Clusters starting from 6.4.654.9590. “ 
- I've have dived into some of the .etl trace files via the PerfView.exe tool, but I can't identify any additional information other than what's already reported on SF Explorer. 
- SMB 2/3 is enabled on these VMs - couldn't identify any other issues from [MSDocs](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation#environment-setup) that may indicate incorrect environment setup 

Any help will be greatly appreciated. 

Full details of the warning:
```
	'System.RA' reported Warning for property 'ReplicaOpenStatus'.
Replica had multiple failures during open on apsyd_120. API call: IStatefulServiceReplica.Open(); Error = System.Fabric.FabricException (-2147024231)
An error occurred during this operation.  Please check the trace logs for more details.
System.Runtime.InteropServices.COMException (-2147024231)
The requested operation could not be completed due to a file system limitation (Exception from HRESULT: 0x80070299)
   at System.Fabric.Data.Log.Interop.NativeLog.IKPhysicalLogManager.EndCreateLogContainer(IFabricAsyncOperationContext Context, IKPhysicalLogContainer& Result)
   at System.Fabric.Data.Log.Interop.PhysicalLogManager.b__10_1(IFabricAsyncOperationContext Context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
--- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.Data.Log.LogManager.d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.KtlLogManager.d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.KtlLogManager.d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.LoggingReplicator.d__139.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.LoggingReplicator.d__138.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.d__118.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.TransactionalReplicator.d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.StatefulServiceReplica.d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Data.ReliableStateManagerImpl.d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices. [Truncated]
```

**Comment by Adebeer** [comment]
It's a while since I looked at C++, but I dived into the Service Fabric code to try and figure out where this error comes from.

**So...it looks like SF only supports NTFS file system.** This will explain it as the data drive containing the SF code is on ReFS. 

If this is indeed the case, shouldn't this be added to [MSDOCs](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation)?

```
 //
    // Next, validate that this is an NTFS file since we can't do this
    // kind of direct IO on just any file system.  The file system needs to
    // give meaningful values for retrieval pointers and bytes per cluster.
    // Also, the file system should not re-direct IO.
    //

    status = IsNtfs(&isNtfs);

    if (!NT_SUCCESS(status)) {
        KTraceFailedAsyncRequest(status, NULL, (ULONGLONG)this, 0);
        goto Finish;
    }

    if (!isNtfs) {
        status = STATUS_FILE_SYSTEM_LIMITATION;
        KTraceFailedAsyncRequest(status, NULL, (ULONGLONG)this, 0);
        goto Finish;
    }
```

**Comment by Adebeer** [comment]
I can confirm switching the Data drive of our Nodes from ReFS to NTFS solved the issue
