### ISSUE TITLE
Explorer issue: Cannot read property 'selectTreeNode' of undefined

### ISSUE THREAD

**Issue by primez** [Azure/service-fabric-issues#1532]
It appears as a very frequent and annoying issue, which prevents the explorer view from being rendered. Only multiple page reloads help
Here is a stack trace from angular
```
lib.min.js:7 TypeError: Cannot read property 'selectTreeNode' of undefined
    at t.selectTreeNode (https://<deploymentdomain>.northeurope.cloudapp.azure.com:19080/Explorer/js/app.min.js:6:18604)
    at n.selectTreeNode (https://<deploymentdomain>.northeurope.cloudapp.azure.com:19080/Explorer/js/app.min.js:7:31603)
    at new n (https://<deploymentdomain>.northeurope.cloudapp.azure.com:19080/Explorer/js/app.min.js:8:10856)
    at Object.s [as instantiate] (https://<deploymentdomain>.northeurope.cloudapp.azure.com:19080/Explorer/js/lib.min.js:6:18590)
    at https://<deploymentdomain>.northeurope.cloudapp.azure.com:19080/Explorer/js/lib.min.js:7:10989
    at link (https://<deploymentdomain>.northeurope.cloudapp.azure.com:19080/Explorer/js/lib.min.js:31:4007)
    at at (https://<deploymentdomain>.northeurope.cloudapp.azure.com:19080/Explorer/js/lib.min.js:7:6599)
    at y (https://<deploymentdomain>.northeurope.cloudapp.azure.com:19080/Explorer/js/lib.min.js:6:31837)
    at s (https://<deploymentdomain>.northeurope.cloudapp.azure.com:19080/Explorer/js/lib.min.js:6:27362)
    at https://<deploymentdomain>.northeurope.cloudapp.azure.com:19080/Explorer/js/lib.min.js:6:26893 <div id="view-container" ng-view="" class="ng-scope" data-ng-animate="1">
```

**Comment by dolifer** [comment]
Removing `adal.idtoken` from Local Storage solved problem, but re-login is required after that.

**Comment by johncrim** [comment]
@dolifer - Thank you for the workaround! This is a very frustrating issue, previously the only workaround was clearing all browser data or using private browsing.

**Comment by VivekanandaPrakash** [comment]
Service Fabric Explorer (SFX) issue is observed specially for clusters enabled with AAD. This has been fixed in 6.5 CU2(6.5.658.9590) Refresh Release. You may find more details including release notes at https://techcommunity.microsoft.com/t5/Azure-Service-Fabric/Azure-Service-Fabric-6-5-Second-Refresh-Release/ba-p/800523.

You may also find the issue discussed in other thread https://github.com/microsoft/service-fabric-explorer/issues/194.

**Comment by primez** [comment]
I have now 6.5.664.9590 and still the issue reproducing, though it's frequency is much less than it was before.

**Comment by johncrim** [comment]
I haven't seen this issue in a while now. There may still be a problem eg when the local token has expired - as I recall, the last time I had to clear my local storage was probably after a relatively long wait.

**Comment by masnider** [comment]
@primez if you are still experiencing this can you share a repro?

**Comment by primez** [comment]
> I haven't seen this issue in a while now. There may still be a problem eg when the local token has expired - as I recall, the last time I had to clear my local storage was probably after a relatively long wait.
I see it reproducing only under these circumstances.
