### ISSUE TITLE
I want to update the service fabric cluster config settings, but when I test the config ,it runs error.

### ISSUE THREAD

**Issue by sall84993356** [Azure/service-fabric-issues#1536]
Stand alone cluster ,three nodes vm . I used gmsa to access the sql server by domain account.

I used this commond :
.\TestConfiguration.ps1 -ClusterConfigFilePath .\ClusterConfig.Unsecure.MultiMachinenew.json -OldClusterConfigFilePath .\ClusterConfig.Unsecure.MultiMachine.json

Trace folder already exists. Traces will be written to existing trace folder: D:\Microsoft.Azure.ServiceFabric.WindowsServer-new\DeploymentTraces
Running Best Practices Analyzer...
Test Config failed with exception: System.AggregateException: One or more errors occurred. ---> System.TypeInitializationException: The type initializer for 'System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility' threw an exception. ---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Net.IPHostEntry> System.Fabric.Common.Helpers.GetHostEntryFromName(System.String)'.
   at System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility.GetCurrentMachineNames()
   at System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility..cctor()
   --- End of inner exception stack trace ---
   at System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility.IsValidIPAddressOrFQDN(String ipAddressOrFQDN)
   at Microsoft.ServiceFabric.DeploymentManager.Model.NodeDescriptionGA.Verify()
   at Microsoft.ServiceFabric.DeploymentManager.Model.StandAloneInstallerJsonModelBase.ValidateNodeList()
   at Microsoft.ServiceFabric.DeploymentManager.Model.StandAloneInstallerJSONModelOctober2017.ValidateModel()
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.IsJsonConfigModelValid(StandAloneInstallerJsonModelBase config, StandAloneInstallerJsonModelBase oldConfig, Boolean validateDownNodes, Boolean throwIfError)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.AnalyzeClusterSetup(String configPath, String oldConfigPath, String cabPath, Boolean usingClusterManifest, FabricPackageType fabricPackageType, Boolean isForcedRun, Int32 maxPercentFailedNodes)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.<>c__DisplayClass1_0.<AnalyzeClusterSetupAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.BpaAnalyzeClusterSetup(String clusterConfigPath, String oldClusterConfigPath, String fabricPackagePath, Int32 maxPercentFailedNodes)
   at Microsoft.ServiceFabric.Powershell.ClusterCmdletBase.TestConfig(String clusterConfigPath, String oldClusterConfigPath, String fabricPackagePath, Int32 maxPercentFailedNodes)
   at Microsoft.ServiceFabric.Powershell.TestConfig.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
---> (Inner Exception #0) System.TypeInitializationException: The type initializer for 'System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility' threw an exception. ---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Net.IPHostEntry> System.Fabric.Common.Helpers.GetHostEntryFromName(System.String)'.
   at System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility.GetCurrentMachineNames()
   at System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility..cctor()
   --- End of inner exception stack trace ---
   at System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility.IsValidIPAddressOrFQDN(String ipAddressOrFQDN)
   at Microsoft.ServiceFabric.DeploymentManager.Model.NodeDescriptionGA.Verify()
   at Microsoft.ServiceFabric.DeploymentManager.Model.StandAloneInstallerJsonModelBase.ValidateNodeList()
   at Microsoft.ServiceFabric.DeploymentManager.Model.StandAloneInstallerJSONModelOctober2017.ValidateModel()
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.IsJsonConfigModelValid(StandAloneInstallerJsonModelBase config, StandAloneInstallerJsonModelBase oldConfig, Boolean validateDownNodes, Boolean throwIfError)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.AnalyzeClusterSetup(String configPath, String oldConfigPath, String cabPath, Boolean usingClusterManifest, FabricPackageType fabricPackageType, Boolean isForcedRun, Int32 maxPercentFailedNodes)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.<>c__DisplayClass1_0.<AnalyzeClusterSetupAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

When I tested this commond : 
.\TestConfiguration.ps1 -ClusterConfigFilePath .\ClusterConfig.Unsecure.MultiMachine.json
It showed the same error

**Comment by sall84993356** [comment]
BTW.
{
    "name": "263Cluster",
    "clusterConfigurationVersion": "1.0.0",
    "apiVersion": "10-2017",
    "nodes": [
      {
        "nodeName": "vm1",
        "iPAddress": "sf1.italkbb.com",
        "nodeTypeRef": "NodeType0",
        "faultDomain": "fd:/dc1/r0",
        "upgradeDomain": "UD0"
      },
      {
        "nodeName": "vm2",
        "iPAddress": "sf2.italkbb.com",
        "nodeTypeRef": "NodeType0",
        "faultDomain": "fd:/dc2/r0",
        "upgradeDomain": "UD1"
      },
      {
        "nodeName": "vm3",
        "iPAddress": "sf3.italkbb.com",
        "nodeTypeRef": "NodeType0",
        "faultDomain": "fd:/dc3/r0",
        "upgradeDomain": "UD2"
      }
    ],
    "properties": {
        "diagnosticsStore": 
        {
            "metadata":  "Please replace the diagnostics file share with an actual file share accessible from all cluster machines. For example, \\\\machine1\\DiagnosticsStore.",
            "dataDeletionAgeInDays": "21",
            "storeType": "FileShare",
            "connectionstring": "\\\\sf1.italkbb.com\\SF\\DiagnosticsStore"
        },
        "nodeTypes": [
          {
            "name": "NodeType0",
            "clientConnectionEndpointPort": "19000",
            "clusterConnectionEndpointPort": "19001",
            "leaseDriverEndpointPort": "19002",
            "serviceConnectionEndpointPort": "19003",
            "httpGatewayEndpointPort": "19080",
            "reverseProxyEndpointPort": "19081",
            "applicationPorts": {
                "startPort": "20001",
                "endPort": "20031"
            },
            "ephemeralPorts": {
              "startPort": "49152",
              "endPort": "65535"
            },
            "isPrimary": true
          },
{
            "name": "NodeType1",
            "clientConnectionEndpointPort": "19000",
            "clusterConnectionEndpointPort": "19001",
            "leaseDriverEndpointPort": "19002",
            "serviceConnectionEndpointPort": "19003",
            "httpGatewayEndpointPort": "19080",
            "reverseProxyEndpointPort": "19081",
            "applicationPorts": {
                "startPort": "20001",
                "endPort": "20031"
            },
            "ephemeralPorts": {
              "startPort": "49152",
              "endPort": "65535"
            },
            "isPrimary": false
          },
{
            "name": "NodeType2",
            "clientConnectionEndpointPort": "19000",
            "clusterConnectionEndpointPort": "19001",
            "leaseDriverEndpointPort": "19002",
            "serviceConnectionEndpointPort": "19003",
            "httpGatewayEndpointPort": "19080",
            "reverseProxyEndpointPort": "19081",
            "applicationPorts": {
                "startPort": "20001",
                "endPort": "20031"
            },
            "ephemeralPorts": {
              "startPort": "49152",
              "endPort": "65535"
            },
            "isPrimary": false
          }
      ],
      "fabricSettings": [
        {
          "name": "Setup",
          "parameters": [
            {
                "name": "FabricDataRoot",
                "value": "D:\\SF"
            },
            {
                "name": "FabricLogRoot",
                "value": "D:\\SF\\Log"
            }
          ]
        }
      ],
"addOnFeatures": [
        "EventStoreService"
    ]
    }
}

**Comment by JustinKaffenberger** [comment]
#1512 documents similar problems with the configuration upgrade scripts. I have yet to get any feedback.

**Comment by rmsryu** [comment]
I was getting the same error after installing runtime version 6.5.639.9590. On my Jump Box computer, I wasn't able to deploy the cluster, getting the same error as above.

$command = "$PSScriptRoot\CreateServiceFabricCluster.ps1 -ClusterConfigFilePath $configurationFile -FabricRuntimePackagePath $runtimeFile -AcceptEULA -verbose"

After uninstalling latest runtime version 6.5.639.9590, and install previous version 6.4.658.9590 it all worked fine again. I hope this can be fixed soon.

Regards

**Comment by sebbrochet** [comment]
@sall84993356 , @rmsryu 

I had no issue to deploy a new SF Cluster from scratch with either Windows Server 2012R2 or 2016 nodes. And later add an additional node (with AddNode.ps1) while using SF Runtime 6.**5**.664.9590

But I get the exact same error message than you (System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Net.IPHostEntry> System.Fabric.Common.Helpers.GetHostEntryFromName(System.String)') when trying to add new node (**Windows Server 2012R2**) into an existing SF Cluster running SF Runtime 6.**4**.664.9590.

So I've just upgraded this existing SF Cluster to 6.**5**.664.9590 and it has fixed the issue.

**Comment by masnider** [comment]
@rmsryu @JustinKaffenberger @sall84993356 are you folks still seeing this with a more recent version of the runtime?

**Comment by rmsryu** [comment]
@maburlik I fixed it after deleting manually the DeploymentComponents folder. The folder was present already from previous executions of different versions. Seems that there was some dll conflict because of that. Deleting it and let the script to create it again has worked for me.
