### ISSUE TITLE
Mounting a host folder inside a container

### ISSUE THREAD

**Issue by gheibia** [Azure/service-fabric-issues#1598]
I'm trying to mount a host folder to a containerized application deployed on Service Fabric. In the "ApplicationManifest.xml" I have something like this:

```
<ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="MyAppPkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides />
    <Policies>
      <ContainerHostPolicies CodePackageRef="Code">
        <PortBinding ContainerPort="80" EndpointRef="MyAppTypeEndpoint" />
        <HealthConfig IncludeDockerHealthStatusInSystemHealthReport="true" RestartContainerOnUnhealthyDockerHealthStatus="false" />
        <Volume Source="d:\hostfolder" Destination="c:\container" IsReadOnly="false" />
      </ContainerHostPolicies>
    </Policies>
  </ServiceManifestImport>
```

I'm testing this with a local cluster on my dev machine.

If I don't create `d:\hostfolder`, I get a `FABRIC_E_DIRECTORY_NOT_FOUND` deployment error. If do, the deployment fails with `'System.RAP' reported Warning for property 'IStatelessServiceInstance.OpenDuration'. The api IStatelessServiceInstance.Open on node _Node_0 is stuck.`

Running `docker ps -a` I can see the container is created, but never activated.
And looking at the cluster's logs, I see the following entries:

```
Finish IStatelessServiceInstance.Open() on node bf865279ba277deb864a976fbf4c200e:132176268775856915(_Node_0) on partition {0aefe61a-635b-4541-816e-5634bbc94972} replica 132176272992839885. ServiceType = MyAppType. Elapsed = 240000.8918ms. Error = FABRIC_E_TIMEOUT. Message = 
```

AND

```
Failed to start Container. ContainerName=sf-0-340cf41f-8966-4f5f-9c32-0229f8296466_2a8b0780-f616-47c0-a00d-7e8aa871239d, ApplicationId=MyApp_SFCType_App0, ApplicationName=fabric:/myapp.System.Fabric.FabricException: Docker operation timed out. RequestUri=http://docker_engine/containers/sf-0-340cf41f-8966-4f5f-9c32-0229f8296466_2a8b0780-f616-47c0-a00d-7e8aa871239d/start
   at Microsoft.ServiceFabric.ContainerServiceClient.ContainerServiceClient.<MakeRequestPrivateAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.ContainerServiceClient.ContainerServiceClient.<MakeRequestAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.ContainerServiceClient.ContainerOperation.<StartContainerAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hosting.ContainerActivatorService.Utility.<>c__DisplayClass14_0.<<ExecuteWithRetryOnTimeoutAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hosting.ContainerActivatorService.Utility.<ExecuteWithRetryOnTimeoutAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hosting.ContainerActivatorService.ActivateContainerOperation.<StartContainerAsync>d__20.MoveNext()

```

I've restarted docker followed by removing and recreating the cluster. I'm not sure why would docker time out. To be sure, I tested deployment without the new volume entry in the manifest and the container is created successfully.

**Comment by gheibia** [comment]
Actually, Service Fabric fails to deploy the application even without attaching volumes. The applications that I've been successfully deployed recently also fail with the same error.

**Comment by gheibia** [comment]
I started noticing this after I upgraded docker desktop for Windows to 2.1.0.4 which comes with Docker 19.03.4 (https://docs.docker.com/docker-for-windows/release-notes/). Downgrading to 2.1.0.2 (and consequently Docker 19.03.2) seems to have resolved the issue for now.

**Comment by gheibia** [comment]
Actually, the docker version seems to be a false positive. If I have docker desktop running and start the cluster manager and create a cluster, this problem shows up again.

**Comment by gkhanna79** [comment]
@gheibia How many Docker instances are concurrently running? Prior to installing the local SF cluster, please ensure that Docker is up and running and that you can execute the HelloWorld container from Docker Hub. 

Post that, deploy the SF cluster and confirm if you still see the issue. If you do, please do share the Docker and OS versions.
