### ISSUE TITLE
Service Fabric Application deployment stuck at "Waiting for upgrade..."

### ISSUE THREAD

**Issue by wangxianglei** [Azure/service-fabric-issues#188]
Hi, I am encounter this "waiting for upgrade" issue when i deploy my service fabric app to azure using VSTS release, for fresh deployment, there is no issue, i can deploy it successfully, but for subsequence deployment, the deployment stuck at "waiting for upgrade".
1) VSTS build definition, i have included "Upgrade Service Fabric App Versions"
2) release definition, i have tried both check "Upgrade Setting" and uncheck it, both are not working.

This is log for deployment, i have turned on debug in VSTS:
2017-03-06T01:41:38.9173123Z Copying application to image store...
2017-03-06T01:43:31.7636256Z Copy application package succeeded
2017-03-06T01:43:31.7693874Z Registering application type...
2017-03-06T01:45:13.4614173Z Register application type succeeded
2017-03-06T01:45:13.4764173Z Start upgrading application...
2017-03-06T01:45:19.5164177Z 
2017-03-06T01:45:19.5164177Z ApplicationParameters                   : {AlertManagerService_TargetReplicaSetSize, 
2017-03-06T01:45:19.5164177Z                                           MaintenanceReportActorService_MinReplicaSetSize, 
2017-03-06T01:45:19.5164177Z                                           MaintenanceReportActorService_TargetReplicaSetSize, 
2017-03-06T01:45:19.5174184Z                                           isEventHubReceiverEnabled...}
2017-03-06T01:45:19.5174184Z UpgradeKind                             : Rolling
2017-03-06T01:45:19.5174184Z ForceRestart                            : False
2017-03-06T01:45:19.5174184Z UpgradeMode                             : Monitored
2017-03-06T01:45:19.5174184Z UpgradeReplicaSetCheckTimeout           : 49710.06:28:15
2017-03-06T01:45:19.5174184Z FailureAction                           : Rollback
2017-03-06T01:45:19.5174184Z HealthCheckWaitDuration                 : 00:00:00
2017-03-06T01:45:19.5174184Z HealthCheckStableDuration               : 00:00:00
2017-03-06T01:45:19.5174184Z HealthCheckRetryTimeout                 : 00:10:00
2017-03-06T01:45:19.5174184Z UpgradeDomainTimeout                    : 10675199.02:48:05.4775807
2017-03-06T01:45:19.5174184Z UpgradeTimeout                          : 10675199.02:48:05.4775807
2017-03-06T01:45:19.5174184Z ConsiderWarningAsError                  : False
2017-03-06T01:45:19.5174184Z MaxPercentUnhealthyDeployedApplications : 0
2017-03-06T01:45:19.5184186Z ServiceTypeHealthPolicyMap              : {}
2017-03-06T01:45:19.5184186Z ApplicationName                         : fabric:/TPMS.Speedlayer.App
2017-03-06T01:45:19.5184186Z TargetApplicationTypeVersion            : 2.0.0.20170302.5
2017-03-06T01:45:19.5184186Z UpgradePolicyDescription                : System.Fabric.Description.MonitoredRollingApplicationUpgradePolicyDescription
2017-03-06T01:45:19.5184186Z 
2017-03-06T01:45:19.5184186Z Waiting for upgrade...
2017-03-06T01:45:22.6974183Z Waiting for upgrade...
.
.
.
2017-03-06T02:10:19.3791044Z Waiting for upgrade...
2017-03-06T02:10:20.4572344Z ##[debug]Leaving D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.3.6\deploy.ps1.
2017-03-06T02:10:20.8166142Z ##[error]The operation was canceled.
2017-03-06T02:10:20.8322395Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.<ExecuteAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
2017-03-06T02:10:20.8322395Z ##[section]Finishing: Deploy Service Fabric Application

**Comment by dbreshears** [comment]
Did you specify a timeout in the VSTS Deploy task by chance?   One thought is the task itself is timing out and being told to shutdown.    If not,  do you hit the same issue deploying an Upgrade from Visual Studio (assuming that is something you can test)

**Comment by wangxianglei** [comment]
Hi Devin, thanks for the replied, I didn't specify any timeout in VSTS deploy task. so far we haven't encounter this issue using visual studio, only encounter when uses VSTS.

**Comment by dbreshears** [comment]
It seems from the log it is nearly exactly 25 minutes.  Have you noticed if this consistently repro's once the upgrade takes longer than 25 minutes from VSTS?  From VS, when choosing to upgrade does it take longer than 25 minutes?  The same code for both VS and VSTS s executing which is located in  C:\Program Files\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricSDK\Publish-UpgradedServiceFabricApplication.ps1 locally.      Will see if we can setup a repro in VSTS.

**Comment by Langwang** [comment]
I have run into the same error.   I thought the upgrade is stuck so i canceled it in VSTS.
Then I suspect it is just very slow, so i retried and  took 11 minutes to upgrade 5 update domains on my local.   

 **So I think it is a performance issue.**

here is my log:

4>Copying application package to image store...
4>Copy application package succeeded
4>Registering application type...
4>Register application type succeeded
4>Start upgrading application...
4>
4>
4>ApplicationName                         : fabric:/AlphabetPartitions
4>ApplicationParameters                   : {}
4>TargetApplicationTypeVersion            : 1.5.0
4>UpgradeKind                             : Rolling
4>ForceRestart                            : False
4>UpgradeMode                             : Monitored
4>UpgradeReplicaSetCheckTimeout           : 00:00:01
4>FailureAction                           : Rollback
4>HealthCheckRetryTimeout                 : 00:10:00
4>HealthCheckWaitDuration                 : 00:00:00
4>UpgradeDomainTimeout                    : 10675199.02:48:05.4775807
4>UpgradeTimeout                          : 10675199.02:48:05.4775807
4>ConsiderWarningAsError                  : 
4>MaxPercentUnhealthyPartitionsPerService : 
4>MaxPercentUnhealthyReplicasPerPartition : 
4>MaxPercentUnhealthyServices             : 
4>MaxPercentUnhealthyDeployedApplications : 
4>ServiceTypeHealthPolicyMap              : 
4>
4>Waiting for upgrade...
 ...............
4>Waiting for upgrade...
4>Waiting for upgrade...
4>Upgrade completed successfully.
4>
4>
4>Finished executing script 'Deploy-FabricApplication.ps1'.
4>**Time elapsed: 00:11:11.2174120**
4>Started executing script 'Get-ServiceFabricApplicationStatus'.
4>[void](Connect-ServiceFabricCluster -TimeoutSec:10 -WarningAction:'SilentlyContinue'); Import-Module 'C:\Program Files\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricSDK\ServiceFabricSDK.psm1'; Get-ServiceFabricApplicationStatus -ApplicationName 'fabric:/AlphabetPartitions' -ErrorAction Stop
4>The application has started.
4>Service Status:
4>fabric:/AlphabetPartitions/Processing is ready.
4>fabric:/AlphabetPartitions/Web is ready.
4>
4>The application is ready.
4>Finished executing script 'Get-ServiceFabricApplicationStatus'.
4>Time elapsed: 00:00:00.9955451
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by Langwang** [comment]
I run into the same issue.  it turned out that it was not being stuck, it was very slow.

when perform a regular deployment to local, it took  less than 30 seconds. 
when perform an upgrade deployment to local, it took 11 minutes.  (my application has 5 update domains)

So i think it is VSTS  Service fabric tool performance issue.

=================Logs======================
4>Copying application package to image store...
4>Copy application package succeeded
4>Registering application type...
4>Register application type succeeded
4>Start upgrading application...
4>
4>
4>ApplicationName                         : fabric:/AlphabetPartitions
4>ApplicationParameters                   : {}
4>TargetApplicationTypeVersion            : 1.5.0
4>UpgradeKind                             : Rolling
4>ForceRestart                            : False
4>UpgradeMode                             : Monitored
4>UpgradeReplicaSetCheckTimeout           : 00:00:01
4>FailureAction                           : Rollback
4>HealthCheckRetryTimeout                 : 00:10:00
4>HealthCheckWaitDuration                 : 00:00:00
4>UpgradeDomainTimeout                    : 10675199.02:48:05.4775807
4>UpgradeTimeout                          : 10675199.02:48:05.4775807
4>ConsiderWarningAsError                  : 
4>MaxPercentUnhealthyPartitionsPerService : 
4>MaxPercentUnhealthyReplicasPerPartition : 
4>MaxPercentUnhealthyServices             : 
4>MaxPercentUnhealthyDeployedApplications : 
4>ServiceTypeHealthPolicyMap              : 
4>
4>Waiting for upgrade...
 ...............
4>Waiting for upgrade...
4>Waiting for upgrade...
4>Upgrade completed successfully.
4>
4>
4>Finished executing script 'Deploy-FabricApplication.ps1'.
4>Time elapsed: 00:11:11.2174120
4>Started executing script 'Get-ServiceFabricApplicationStatus'.
4>[void](Connect-ServiceFabricCluster -TimeoutSec:10 -WarningAction:'SilentlyContinue'); Import-Module 'C:\Program Files\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricSDK\ServiceFabricSDK.psm1'; Get-ServiceFabricApplicationStatus -ApplicationName 'fabric:/AlphabetPartitions' -ErrorAction Stop
4>The application has started.
4>Service Status:
4>fabric:/AlphabetPartitions/Processing is ready.
4>fabric:/AlphabetPartitions/Web is ready.
4>
4>The application is ready.
4>Finished executing script 'Get-ServiceFabricApplicationStatus'.
4>Time elapsed: 00:00:00.9955451

**Comment by oanapl** [comment]
Are you overriding HealthCheckStableDuration value when starting the upgrade? By default is 2 minutes, so we always wait for 2 minutes after an UD completes, to make sure things are stable. Read more about it [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade).

**Comment by robgonfer** [comment]
Hi @oanapl what is the right way to override this parameter and HealthCheckWaitDuration? I know is possible to set these 2 at the cluster level (in Azure portal) but have not found a way to do it at the application level. Is it something that can be configured in the service manifest or app manifest? Our deployment takes sometimes more than 1 hour and I am trying to bring that down. 

Thanks.

**Comment by oanapl** [comment]
You can pass the parameters when [starting the upgrade](https://docs.microsoft.com/en-us/powershell/module/servicefabric/start-servicefabricapplicationupgrade?view=azureservicefabricps). 
For example, to set both stable and wait durations to 0, use:
```powershell
Start-ServiceFabricApplicationUpgrade -ApplicationName fabric:/myapp/persistenttodolist -ApplicationTypeVersion "2.0" -Monitored -HealthCheckWaitDurationSec 0 -HealthCheckStableDurationSec 0
```

@dbreshears , what is the right way to pass the parameters in VSTS?

**Comment by dbreshears** [comment]
@oanapl,  @robgonfer ,  So you can either save it to the Cloud.xml publish profile  (we have UI in the publish dialog to help with this) or if you don't want to use the publish profile for these settings,  you can open the Deploy Service Fabric Application Release definition on VSTS,  click on Upgrade Settings -> (check) Override all Publish Profile Upgrade Settings in which you can find text boxes for the 2 parameters.

**Comment by oanapl** [comment]
Thank you, @dbreshears!
@robgonfer , there are no more open questions at this time. I will close the issue, feel free to re-open if needed.
