### ISSUE TITLE
Error on nodes after New-AzureRmResourceGroupDeployment 

### ISSUE THREAD

**Issue by Eneuman** [Azure/service-fabric-issues#198]
I have a newly created ARM template (created by the Portal).
I added a new certificate to it and run New-AzureRmResourceGroupDeployment

I'm now receive this error in my cluster manager on the First nodes in each scaleset:

Error event: SourceId='FabricDCA', Property='DataCollectionAgent.AzureBlobServiceFabricEtw'.
Exception occured while creating an object of type FabricDCA.AzureBlobEtwCsvUploader (assembly AzureFileUploader, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) for creating consumer AzureBlobServiceFabricEtw. Exception information: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: AzureFileUploader could not be constructed. ---> System.InvalidOperationException: Error creating container fabriclogs-135fb24d-8c0b-41cc-a504-fc3747a2eadd, account sflogseclinic5070. ---> Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExists(BlobContainerPublicAccessType accessType, BlobRequestOptions requestOptions, OperationContext operationContext)
   at FabricDCA.AzureFileUploader.CreateContainer(Object context)
   at System.Fabric.Dca.Utility.PerformWithRetries[T](Action`1 worker, T context, RetriableOperationExceptionHandler exceptionHandler, Int32 initialRetryIntervalMs, Int32 maxRetryCount, Int32 maxRetryIntervalMs)
   at FabricDCA.AzureFileUploader..ctor(ExtensionsEvents traceSource, String logSourceId, String folderName, String destinationPath, String workFolder, StorageConnection storageConnection, String containerName, TimeSpan uploadIntervalMinutes, TimeSpan fileSyncIntervalInMinutes, TimeSpan blobDeletionAgeMinutes, String fabricNodeInstanceName, String deploymentId)
   --- End of inner exception stack trace ---
   at FabricDCA.AzureFileUploader..ctor(ExtensionsEvents traceSource, String logSourceId, String folderName, String destinationPath, String workFolder, StorageConnection storageConnection, String containerName, TimeSpan uploadIntervalMinutes, TimeSpan fileSyncIntervalInMinutes, TimeSpan blobDeletionAgeMinutes, String fabricNodeInstanceName, String deploymentId)
   at FabricDCA.EtwCsvUploadWorker..ctor(EtwCsvUploadWorkerParameters initParam)
   --- End of inner exception stack trace ---
   at FabricDCA.EtwCsvUploadWorker..ctor(EtwCsvUploadWorkerParameters initParam)
   at FabricDCA.AzureBlobEtwCsvUploader..ctor(ConsumerInitializationParameters initParam)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at FabricDCA.ConsumerFactory.CreateConsumer(String consumerInstance, ConsumerInitializationParameters initParam, String moduleName, String typeName).

Any idea what's going on here and how I can fix it ?

Regards
Per

**Comment by Eneuman** [comment]
I removed the resource group and all the resource created by the portal and deployment the template using PS and it worked. I take it this was just a glitch.
