### ISSUE TITLE
Deploy from VSTS fails with XML validation on CorrelationId

### ISSUE THREAD

**Issue by nrandell** [Azure/service-fabric-issues#209]
I'm trying to deploy from VSTS to a cluster. All the packages have been upgraded to the latest 5.5 versions, including the 1.5.0 build package.

All builds ok, but when it goes to deploy from VSTS, it fails with 

```
2017-03-24T08:31:50.0967786Z ##[error]Exception while parsing XML file: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4061205834\ajdd2jeh.w2g\applicationpackage\ApplicationManifest.xml
FileName: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4061205834\ajdd2jeh.w2g\applicationpackage\ApplicationManifest.xml
```

Setting the System.Debug variable to true, the build shows a bit more information. It looks like the ___CorrelationId___ attribute in the ApplicationManifest is not supported and the validation fails.

```
2017-03-24T08:31:45.1368606Z ##[debug]INPUT_OVERRIDEPUBLISHPROFILESETTINGS: 'false'
2017-03-24T08:31:47.1808124Z ##[debug]Join-Path "C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code" "ServiceFabricServiceModel.xsd"
2017-03-24T08:31:47.1858127Z ##[debug]C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code\ServiceFabricServiceModel.xsd
2017-03-24T08:31:47.1868135Z ##[debug]Length: 94
2017-03-24T08:31:47.1888262Z ##[debug]
2017-03-24T08:31:47.1908137Z ##[debug]Test-Path "C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code\ServiceFabricServiceModel.xsd"
2017-03-24T08:31:47.1948132Z ##[debug]True
2017-03-24T08:31:47.1958137Z ##[debug]
2017-03-24T08:31:49.5072893Z ##[debug]System.Fabric.Management.ImageBuilder.FabricImageBuilderValidationException: Exception while parsing XML file: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4061205834\ajdd2jeh.w2g\applicationpackage\ApplicationManifest.xml
2017-03-24T08:31:49.5082973Z ##[debug]FileName: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4061205834\ajdd2jeh.w2g\applicationpackage\ApplicationManifest.xml ---> System.InvalidOperationException: There is an error in XML document (2, 260). ---> System.Xml.Schema.XmlSchemaValidationException: The '___CorrelationId___' attribute is not declared.
2017-03-24T08:31:49.5092968Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(XmlSchemaValidationException e, XmlSeverityType severity)
2017-03-24T08:31:49.5102968Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(String code, String arg)
2017-03-24T08:31:49.5112964Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String lName, String ns, XmlValueGetter attributeValueGetter, String attributeStringValue, XmlSchemaInfo schemaInfo)
2017-03-24T08:31:49.5122964Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String localName, String namespaceUri, XmlValueGetter attributeValue, XmlSchemaInfo schemaInfo)
2017-03-24T08:31:49.5162947Z ##[debug]   at System.Xml.XsdValidatingReader.ValidateAttributes()
2017-03-24T08:31:49.5212932Z ##[debug]   at System.Xml.XsdValidatingReader.ProcessElementEvent()
2017-03-24T08:31:49.5212932Z ##[debug]   at System.Xml.XsdValidatingReader.Read()
2017-03-24T08:31:49.5212932Z ##[debug]   at System.Xml.XmlReader.MoveToContent()
2017-03-24T08:31:49.5212932Z ##[debug]   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read395_ApplicationManifest()
2017-03-24T08:31:49.5212932Z ##[debug]   --- End of inner exception stack trace ---
2017-03-24T08:31:49.5212932Z ##[debug]   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
2017-03-24T08:31:49.5212932Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReader reader)
2017-03-24T08:31:49.5212932Z ##[debug]   --- End of inner exception stack trace ---
2017-03-24T08:31:49.5222954Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.TraceAndThrowValidationErrorWithFileName(Exception innerException, String type, String fileName, String format, Object[] args)
2017-03-24T08:31:49.5242938Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReader reader)
2017-03-24T08:31:49.5252939Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReaderSettings validatingXmlReaderSettings)
2017-03-24T08:31:49.5273161Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ParseApplicationPackageAsync>d__8.MoveNext()
2017-03-24T08:31:49.5282941Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2017-03-24T08:31:49.5292957Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T08:31:49.5312939Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T08:31:49.5322950Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ProvisionApplicationAsync>d__0.MoveNext()
2017-03-24T08:31:49.9291685Z ##[debug]Leaving C:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.3.6\deploy.ps1.
2017-03-24T08:31:49.9391691Z ##[debug]Caught exception from task script.
2017-03-24T08:31:49.9421708Z ##[debug]Error record:
2017-03-24T08:31:50.0137132Z ##[debug]Test-ServiceFabricApplicationPackage : Exception while parsing XML file: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4061205834\ajdd2jeh.w2g\applicationpackage\ApplicationManifest.xml
2017-03-24T08:31:50.0147131Z ##[debug]FileName: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4061205834\ajdd2jeh.w2g\applicationpackage\ApplicationManifest.xml
2017-03-24T08:31:50.0167137Z ##[debug]At C:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.3.6\ServiceFabricSDK\Publish-UpgradedServiceFabricApplication.ps1:142 char:38
2017-03-24T08:31:50.0177136Z ##[debug]+ ... nSuccess = (Test-ServiceFabricApplicationPackage $AppPkgPathToUse -Im ...
2017-03-24T08:31:50.0187831Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2017-03-24T08:31:50.0197137Z ##[debug]    + CategoryInfo          : InvalidOperation: (:) [Test-ServiceFabricApplicationPackage], FabricImageBuilderValidati    onException
2017-03-24T08:31:50.0217122Z ##[debug]    + FullyQualifiedErrorId : TestApplicationPackageErrorId,Microsoft.ServiceFabric.Powershell.TestApplicationPackage
2017-03-24T08:31:50.0227127Z ##[debug] 
2017-03-24T08:31:50.0247121Z ##[debug]Script stack trace:
2017-03-24T08:31:50.0277132Z ##[debug]at Publish-UpgradedServiceFabricApplication, C:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.3.6\ServiceFabricSDK\Publish-UpgradedServiceFabricApplication.ps1: line 142
2017-03-24T08:31:50.0297243Z ##[debug]at <ScriptBlock>, C:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.3.6\deploy.ps1: line 135
```

**Comment by nrandell** [comment]
I've just re-read the release notes!

Application Correlation ID
When packaging applications using Visual Studio or MSbuild, a correlation ID will be added to the application manifest file.
You can change this default behavior by adding ```<AddCorrelationIds>false</AddCorrelationIds>``` in the <PropertyGroup Label="Globals"> element in the .sfproj file. Or running MSBuild using /p:AddCorrelationIds=false.

**Comment by MikkelHegn** [comment]
We're investigating. For now the workaround is to disable the generation of the correlation.

**Comment by kcwinner** [comment]
To be clear for others here are the release notes: https://blogs.msdn.microsoft.com/azureservicefabric/2017/03/23/release-of-sdk-2-5-216-and-runtime-5-5-216-for-windows/

And here is where you add the element

"You can change this default behavior by adding <AddCorrelationIds>false</AddCorrelationIds> in the <PropertyGroup Label="Globals"> element in the .sfproj file. Or running MSBuild using /p:AddCorrelationIds=false."

**Comment by aloneguid** [comment]
This worked like a charm for me, after adding AddCorrelationIds deployment started working again

![image](https://cloud.githubusercontent.com/assets/3155189/24766794/941fda88-1af4-11e7-8266-96a18a07072e.png)

**Comment by pksorensen** [comment]
i just updated a few projects, and found this issue. What i dont understand is, why did some of my projects rebuild and deploy just fine, while some of my projects failed with the same issue described here?

What is the cause of the problem? what side effects do it have when adding AddCorrelationIds =false?

**Comment by jahmai** [comment]
I'd like to know under what conditions this _doesn't_ break out of the box. Seems like a major bug.

**Comment by MikkelHegn** [comment]
@jahmai: It doesn't break if you build agent has the updated schema with the 5.5 release. The hosted build agents in VSTS has some lead time to get the updated SDK.
We are working on a way to enable building with specific SDK versions in VSTS, which should remove the lead time between SDK releases and updating VSTS.

**Comment by Fluwit** [comment]
@MikkelHegn I'm experiencing the same problem when building and publishing directly from VS2015? Though, this is an application updated to version 2.6 and has to be published using a 2.5 installation due to issues with the latest release.

**Comment by Izzmo** [comment]
I'm also running into this, only in VSTS though.

**Comment by justinpatten** [comment]
@MikkelHegn Is there any way to get the build engine to utilize the packages that are included? I used this fix to get around the deploy error, but we utilize ServiceFabric.Mocks for unit testing, which is trying to use the new versions of the DLLs and failiing. The proper NuGet versions of the SDK are with the test project, but it seems like the hosted agents are using the ones installed on the agent instead of the DLLS within the solution,

**Comment by MikkelHegn** [comment]
@Fluwit - If you are using the 2.5 SDK - there is no known issue with the schema. Also your cluster has to run at least 5.5, otherwise you would see the error when deploying the application.

**Comment by MikkelHegn** [comment]
@Izzmo: The Hosted agent queue in VSTS is still on 5.4, but the Hosted VS2017 agent is on a newer supported SDK.
Once I have the lead time to get the hosted agent updated I'll post it here.

**Comment by MikkelHegn** [comment]
@justinpatten: the failing command is Test-ApplicationPackage, which you cannot control. Only option would be to not use the deploy task, but use the Service Fabric PowerShell task and provide your own script and avoiding using Test-ApplicationPackage

**Comment by Izzmo** [comment]
@MikkelHegn I am using the new 2017 build agent, same issue, let me know if I can be of any further help in debugging with logs.

**Comment by MikkelHegn** [comment]
@Izzmo what version is your SF cluster running? If 5.5 or newer this is another issue.

**Comment by Izzmo** [comment]
@MikkelHegn 5.6.210.x

**Comment by MikkelHegn** [comment]
@Izzmo Can you share a release log output with debug enabled, just to be sure we see the same error. If you don't want to share it here, then mikhegn@microsoft.com - Thanks.

**Comment by nrandell** [comment]
I'm seeing an issue as well. Brand new cluster running 5.6.210.9494, services built and deployed using hosted VS2017 on VSTS. All the latest tooling.

Without adding `    <AddCorrelationIds>false</AddCorrelationIds>` I get
```
2017-06-01T06:51:37.4553735Z ##[error]Exception while parsing XML file: d:\a\_temp\TestApplicationPackage_2776374910\vpcwdqqs.v2o\applicationpackage\ApplicationManifest.xml
```

When I don't generate Correlation Ids it works ok

**Comment by Vhab** [comment]
On a very likely related issue, `ServicePackageActivationMode="ExclusiveProcess"` triggers the same error.
This is using the VS2017 Hosted Agents on VSTS, 1.6 SF tooling and 2.6.210 SF SDK.

```
2017-06-01T10:16:07.5228481Z ##[debug]Test-Path "C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code\ServiceFabricServiceModel.xsd"
2017-06-01T10:16:07.5268494Z ##[debug]True
2017-06-01T10:16:07.5278493Z ##[debug]
2017-06-01T10:16:10.6922733Z ##[debug]System.Fabric.Management.ImageBuilder.FabricImageBuilderValidationException: Exception while parsing XML file: d:\a\_temp\TestApplicationPackage_3421057138\e5w0szva.abv\AppPkg\ApplicationManifest.xml
2017-06-01T10:16:10.6932777Z ##[debug]FileName: d:\a\_temp\TestApplicationPackage_3421057138\e5w0szva.abv\AppPkg\ApplicationManifest.xml ---> System.InvalidOperationException: There is an error in XML document (367, 40). ---> System.Xml.Schema.XmlSchemaValidationException: The 'ServicePackageActivationMode' attribute is not declared.
```

I'm assuming the install on the VS2017 hosted agent is out of date.

Are there any plans to synchronize these versions and releases across different Microsoft services more consistently?

**Comment by Izzmo** [comment]
Just got this on a new Service Fabric project, on Visual Studio 2017 Preview 3, so it's still happening.

Had to add the `<AddCorrelationIds>false</AddCorrelationIds>` in my sfproj to get it to work.

@MikkelHegn I just sent you some logs.

**Comment by fgauna12** [comment]
@Vhab I'm getting the same issue after I added the `<AddCorrelationIds>false</AddCorrelationIds>`. I'm also using VS2017 hosted agents. Did you work around it?

**Comment by Vhab** [comment]
No workaround unfortunately. We opted to not use these features until MS updates the hosted agents.
Should our needs become more dire, we will start running our own agents.

**Comment by rasmuscl** [comment]
"/p:AddCorrelationIds=false" works fine, but is there a corresponding way of preventing the ServicePackageActivationMode attribute from being generated in the manifest file as well?

**Comment by MikkelHegn** [comment]
@rasmuscl Our next tooling update will introduce a way to prevent any changes to the manifest files on build. There are special cases where this is useful (https://github.com/Azure/service-fabric-issues/issues/53), but it will also leave some work in the hands of the develop.

**Comment by rasmuscl** [comment]
Ok, thanks for the update. I solved it temporarily by adding a powershell script task that removes the ServicePackageActivationMode="ExclusiveProcess" attribute from the application manifest file after build. A bit hacky, bit it works :-)

**Comment by MikkelHegn** [comment]
@rasmuscl circling back to this one. We add this attribute during add service in VS. But if this attribute is removed, then build wouldn’t add it back. Is this not what you see in this case? IS it getting added back in on build?
