### ISSUE TITLE
VS 2017 Service Fabric solution upgrade failure

### ISSUE THREAD

**Issue by MedAnd** [Azure/service-fabric-issues#236]
sfproj:

`<ProjectVersion>1.5</ProjectVersion>`
`<MinToolsVersion>1.5</MinToolsVersion>`

VS2017 Logs:

Recoverable
System.ArgumentException: Cannot access a disposed object.
Object name: 'Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesScope'.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)
   at Microsoft.VisualStudio.Azure.Fabric.Shared.Hierarchy.UnloadAndReloadProject(IServiceProvider serviceProvider, Guid projectId, Boolean reopenDocuments)
   at Microsoft.VisualStudio.Azure.Fabric.ApplicationProject.ProjectSystem.PackageRestoreManager.<InitializeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.AutoLoadMethodStateMachine.<<StartExecution>b__8_0>d.MoveNext()

**Comment by dbreshears** [comment]
Thanks for the feedback.  Sorry for this issue.    I'll log a bug in our DB and look into a  fix in our next release.  Are you able to get past this currently with manually updates to the .sfproj?  You will need tomanually restore the Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.5.0 Nuget package to the solution,  an perhaps update the .sfproj to 1.5 in 4 places if the upgrade failed.   Let me know if you are able  to get your solution loaded or not.

**Comment by MedAnd** [comment]
Think this is a duplicate of this issue? https://github.com/Azure/service-fabric-issues/issues/206

**Comment by MedAnd** [comment]
@dbreshears replacing all references to Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.4.0 with Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.5.0 in the .sfproj resolved the issue.

**Comment by dbreshears** [comment]
@MedAnd. Ok I'll close, thanks for the confirmation.   We will investigate to see if we can find the root cause of the upgrade issue you encountered.
