### ISSUE TITLE
Setting ServicePackageActivationMode leads to XML error

### ISSUE THREAD

**Issue by negberts** [Azure/service-fabric-issues#270]
The SDK is updated and the correct XSD is in place in C:\Program Files\Microsoft SDKs\Service Fabric\schemas.
Visual Studio 2017 is updated as well. Nuget packages updated. Local cluster is running the new SDK: 
![image](https://cloud.githubusercontent.com/assets/20299260/25985374/84df1c16-36ea-11e7-99e6-a95b4313b87e.png)

But when hitting F5 in Visual Studio and trying to deploy we get an error: 

22>------ Deploy started: Project: Pim.ServiceFabric, Configuration: Debug x64 ------
22>There is an error in XML document (65, 42).

This corresponds to the first line that contains the new setting:
`<Service Name="MengselServiceIlionx" ServicePackageActivationMode="ExclusiveProcess">`

What are we doing wrong?

**Comment by VipulM-MSFT** [comment]
@dbreshears can you please take a look?

**Comment by negberts** [comment]
To be sure the msbuild nuget package is updated to 1.6 in the project:

`<Import Project="..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets" Condition="Exists('..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets')" />`

**Comment by negberts** [comment]
Could tools version be the problem? 

![image](https://cloud.githubusercontent.com/assets/20299260/25986601/e8d31de8-36f0-11e7-8d71-8908f76fdfbe.png)

**Comment by VipulM-MSFT** [comment]
The tooling version should be 1.6. I will be closing the issue as we verified that this works with the latest tooling. If it still is an issue after upgrading tooling, please feel free to reopen the issue.

**Comment by negberts** [comment]
How can I update the tooling then? It's part of VS2017 isn't? No longer a standalone executable.. And Visual Studio was updated to latest version...

**Comment by negberts** [comment]
![image](https://cloud.githubusercontent.com/assets/20299260/25987541/c2da2074-36f4-11e7-82f9-fad5e6b23732.png)

**Comment by VipulM-MSFT** [comment]
Are you using VS 2017 or VS 2015?

If you are using the VS 2017 I suggest you uninstall existing Service Fabric tooling and the try installing the SDK again. The page https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started has needed versions.

@dbreshears - any other options?

**Comment by negberts** [comment]
VS 2017. I will give uninstalling a try

**Comment by negberts** [comment]
Reinstalling SDK did not work. Tools version still at 1.5. But aren't tools part of Visual Studio in 2017?

**Comment by negberts** [comment]
It shouldn't be required to install the preview version of Visual Studio 2017 right?

**Comment by ravipal** [comment]
1.6 tooling is not yet available in VS 2017. It is available in preview of VS 2017. Please install the VS 2017 preview from https://www.visualstudio.com/vs/preview/, if you would like to use 1.6 tooling.

**Comment by negberts** [comment]
Thank you, the release notes were not pretty clear about it. My understanding was that I needed the preview version of Visual Studio for the 5.7 version with docker support, not for the 5.6 version.

**Comment by kieronlanning** [comment]
@ravipal Sorry, I'm a little confused - are you saying that to use Docker with Service Fabric we _must_ use the 15.3 Preview of VS 2017, regardless of any WebPI based Tooling and SDK made available over the next few days (re: https://blogs.msdn.microsoft.com/azureservicefabric/2017/05/10/release-of-sdk-2-6-204-and-runtime-5-6-204-for-windows-and-a-preview-of-whats-next/).

We're looking at using Docker to host our ASP.NET Core microservices inside of SF, and a preview of VS 2017 might be a step too far for the team (I've already tried it, and our .NET Core solution no-longer builds), so I'm hesitent to role that out to the team.

**Comment by VipulM-MSFT** [comment]
You will need to use the VS2017 preview if you would like to use the existing compose file to do deploy to Service Fabric cluster. Optionally you can use ContainerHost in the service manifest instead to deploy the docker image that you have built outside of the Service Fabric project. 

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-deploy-container#manually-package-and-deploy-a-container-image

**Comment by MikkelHegn** [comment]
I think we can close this one, feel free to reopen.

**Comment by Eneuman** [comment]
This issue still exists when deploying from VSTS.
Is the tooling on the build clients in VSTS updated ?

```
2018-02-13T12:09:11.7619418Z ##[debug]Test-Path "C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code\ServiceFabricServiceModel.xsd"
2018-02-13T12:09:11.7792599Z ##[debug]True
2018-02-13T12:09:11.8038914Z ##[debug]
2018-02-13T12:09:13.1751573Z ##[debug]System.Fabric.Management.ImageBuilder.FabricImageBuilderValidationException: Exception while parsing XML file: D:\a\_temp\TestApplicationPackage_37380540240\s5oxn2qt.hpa\Journal\ApplicationManifest.xml
2018-02-13T12:09:13.1769525Z ##[debug]FileName: D:\a\_temp\TestApplicationPackage_37380540240\s5oxn2qt.hpa\Journal\ApplicationManifest.xml ---> System.InvalidOperationException: There is an error in XML document (33, 36). ---> System.Xml.Schema.XmlSchemaValidationException: The 'ServicePackageActivationMode' attribute is not declared.
2018-02-13T12:09:13.1783539Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(XmlSchemaValidationException e, XmlSeverityType severity)
2018-02-13T12:09:13.1799877Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(String code, String arg)
2018-02-13T12:09:13.1813992Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String lName, String ns, XmlValueGetter attributeValueGetter, String attributeStringValue, XmlSchemaInfo schemaInfo)
2018-02-13T12:09:13.1829112Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String localName, String namespaceUri, XmlValueGetter attributeValue, XmlSchemaInfo schemaInfo)
2018-02-13T12:09:13.1844727Z ##[debug]   at System.Xml.XsdValidatingReader.ValidateAttributes()
2018-02-13T12:09:13.1858821Z ##[debug]   at System.Xml.XsdValidatingReader.ProcessElementEvent()
2018-02-13T12:09:13.1874530Z ##[debug]   at System.Xml.XsdValidatingReader.Read()
2018-02-13T12:09:13.1889048Z ##[debug]   at System.Xml.XmlReader.MoveToContent()
2018-02-13T12:09:13.1903482Z ##[debug]   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read170_DefaultServicesType(Boolean isNullable, Boolean checkType)
2018-02-13T12:09:13.1918063Z ##[debug]   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read212_ApplicationManifestType(Boolean isNullable, Boolean checkType)
2018-02-13T12:09:13.1933622Z ##[debug]   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read395_ApplicationManifest()
2018-02-13T12:09:13.1950380Z ##[debug]   --- End of inner exception stack trace ---
2018-02-13T12:09:13.1965129Z ##[debug]   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
2018-02-13T12:09:13.1981690Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReader reader)
2018-02-13T12:09:13.1995877Z ##[debug]   --- End of inner exception stack trace ---
2018-02-13T12:09:13.2011822Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.TraceAndThrowValidationErrorWithFileName(Exception innerException, String type, String fileName, String format, Object[] args)
2018-02-13T12:09:13.2026392Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReader reader)
2018-02-13T12:09:13.2041230Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReaderSettings validatingXmlReaderSettings)
2018-02-13T12:09:13.2056742Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ParseApplicationPackageAsync>d__8.MoveNext()
2018-02-13T12:09:13.2071337Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2018-02-13T12:09:13.2085487Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-02-13T12:09:13.2101905Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-02-13T12:09:13.2117708Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ProvisionApplicationAsync>d__0.MoveNext()
```
