### ISSUE TITLE
Install cluster in AWS cloud:: Timed out waiting for Installer Service to complete for machine. Investigation order: FabricInstallerService -> FabricSetup

### ISSUE THREAD

**Issue by prinupmathew** [Azure/service-fabric-issues#277]
I am trying to **create unsecure standalone 3 VM service fabric cluster in AWS cloud**. Below are the errors i am getting. I have spent considerable amount of time (3 days) trying to figure out what the underlying issue(s) are. Any help is highly appreciated...

Notes: I have opened all ports as per the cluster prerequisites both from AWS VM instances and Security groups.

.\CreateServiceFabricCluster.ps 1 -ClusterConfigFilePath .\ClusterConfig.Unsecure.MultiMachine.json -FabricRuntimePackagePath .\DeploymentRuntimePackage s\MicrosoftAzureServiceFabric.5.5.216.0.cab Do you accept the license terms for using Microsoft Azure Service Fabric located in the root of your package download? I f you do not accept the license terms you may not use the software. [Y] Yes [N] No [?] Help (default is "N"): y Creating Service Fabric Cluster... If it's taking too long, please check in Task Manager details and see if Fabric.exe for each node is running. If not, pl ease look at: 1. traces in DeploymentTraces directory and 2. traces in FabricLogRoot configured in ClusterConfig.json. Trace folder already exists. Traces will be written to existing trace folder: D:\ServiceFabric_Cluster_Setup\Microsoft.A zure.ServiceFabric.WindowsServer.5.5.216.0\DeploymentTraces Running Best Practices Analyzer... Best Practices Analyzer completed successfully. Creating Service Fabric Cluster... Processing and validating cluster config. Configuring nodes. Default installation directory chosen based on system drive of machine 'XXXX'. Copying installer to all machines. Configuring machine 'XXXX'. Configuring machine 'XXXX'. Configuring machine 'XXXX'. Machine XXXX configured. Machine XXXX configured. Machine XXX configured. Running Fabric service installation. Successfully started FabricInstallerSvc on machine XXXX Successfully started FabricInstallerSvc on machine XXXX Successfully started FabricInstallerSvc on machine XXXX Timed out waiting for Installer Service to complete for machine XXXX. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric Timed out waiting for Installer Service to complete for machine XXXX. Investigation order: FabricInstallerServic e -> FabricSetup -> FabricDeployer -> Fabric Timed out waiting for Installer Service to complete for machine XXXX. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric CreateCluster Error: System.AggregateException: One or more errors occurred. ---> **System.ServiceProcess.TimeoutException : Timed out waiting for Installer Service to complete for machine XXXX. Investigation order: FabricInstallerServi ce -> FabricSetup -> FabricDeployer -> Fabric at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(Str ing machineName, ServiceController installerSvc) at System.Threading.Tasks.Parallel.<>c__DisplayClass17_01.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallel**
Options, Action1 body, Action2 bodyWithState, Func4 bodyWithLocal, Func1 localInit, Action1 localFinally) at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable1 source, ParallelOptions parallelOption
s, Action1 body, Action2 bodyWithState, Action3 bodyWithStateAndIndex, Func4 bodyWithStateAndLocal, Func5 bodyWithE verything, Func1 localInit, Action1 localFinally) at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable1 source, Action1 body) at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.RunFabricServices(List1 machines, FabricPacka
geType fabricPackageType)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__7.MoveNext()
---> (Inner Exception #0) System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete fo
r machine XXXX. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(Str
ing machineName, ServiceController installerSvc)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_01.b__1() at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) at System.Threading.Tasks.Task.<>c__DisplayClass176_0.b__0(Object )<---

---> (Inner Exception #1) System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete fo r machine XXXX. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(Str ing machineName, ServiceController installerSvc) at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.b__1() at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) at System.Threading.Tasks.Task.<>c__DisplayClass176_0.b__0(Object )<---

---> (Inner Exception #2) System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete fo r machine XXXX. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(Str ing machineName, ServiceController installerSvc) at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.b__1() at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) at System.Threading.Tasks.Task.<>c__DisplayClass176_0.b__0(Object )<---

Here is the details i could find from trace logs

2017-05-14 03:40:11.489,Info ,4640,FabricInstallerService.FabricUpgradeManager,Flushing volume file buffer for drive 'C'. 2017-05-14 03:40:11.674,Info ,4640,FabricInstallerService.FabricUpgradeManager,Calling upgrade entry point 2017-05-14 03:40:11.674,Info ,4640,FabricInstallerService.FabricUpgradeManager,Upgrade executing: C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code\FabricSetup.exe /operation:Install 2017-05-14 03:40:11.677,Info ,4640,Common.ProcessUtility,CreateProcess Successful for CommandLine:C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code\FabricSetup.exe /operation:Install. ProcessId:648 MainThreadId:4616 ProcessHandle:1b4 2017-05-14 03:40:14.759,Info ,4640,FabricInstallerService.FabricUpgradeManager,starting fabric host service **2017-05-14 03:40:24.837,Info ,4640,FabricInstallerService.FabricUpgradeManager,Waiting for the upgrade or FabricSetup to complete, at which time target information file is expected to get deleted 2017-05-14 03:40:24.837,Noise ,4640,Timer.Created,178d50b3b20 tag='FabricInstallerService::FabricUpgradeManager::UpgradeAsyncOperation::DoUpgrade', count=1 2017-05-14 03:40:24.837,Noise ,4640,Timer.Scheduled,178d50b3b20 scheduled = true, dueTime = 00.000, period = 02.000 2017-05-14 03:40:24.838,Noise ,4640,Timer.EnterCallback,178d50b3b20 enter callback 2017-05-14 03:40:24.838,Noise ,4640,FabricInstallerService.FabricUpgradeManager,OnTimerCallback invoked 2017-05-14 03:40:24.838,Noise ,4640,Timer.LeaveCallback,178d50b3b20 leave callback 2017-05-14 03:40:26.838,Noise ,4640,Timer.EnterCallback,178d50b3b20 enter callback** ......................................................................................................... ......................................................................................................... ......................................................................................................... ......................................................................................................... 2017-05-14 03:45:22.839,Noise ,4640,FabricInstallerService.FabricUpgradeManager,OnTimerCallback invoked 2017-05-14 03:45:22.839,Noise ,4640,Timer.LeaveCallback,178d50b3b20 leave callback 2017-05-14 03:45:24.839,Noise ,4640,Timer.EnterCallback,178d50b3b20 enter callback 2017-05-14 03:45:24.839,Noise ,4640,FabricInstallerService.FabricUpgradeManager,OnTimerCallback invoked 2017-05-14 03:45:24.839,Error ,4640,FabricInstallerService.FabricUpgradeManager,Target information file exists. This would indicate that Fabric node open or Fabric uninstall didn't happen successfully. Rolling back.. 2017-05-14 03:45:24.839,Noise ,4640,Timer.CancelCalled,178d50b3b20 cancel called, waitForCallbackOnCancel = false 2017-05-14 03:45:24.839,Noise ,4640,Timer.CancelWait,178d50b3b20 wait for cancel completion 2017-05-14 03:45:24.839,Info ,4640,FabricInstallerService.FabricUpgradeManager,Rollback started with FabricDataRoot:D:\ProgramData\SF, FabricLogRoot:D:\ProgramData\SF\Log, FabricCodePath:C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code, FabricRoot:C:\Program Files\Microsoft Service Fabric, TargetInformationFilePath:D:\ProgramData\SF\TargetInformation.xml, TargetInformationDescription:TargetInformationFileDescription { CurrentInstallation = WindowsFabricDeploymentDescription { IsValid = false, InstanceId = , MSILocation = , ClusterManifestLocation = , InfrastructureManifestLocation = , NodeName = , UpgradeEntryPointExe = , UpgradeEntryPointExeParameters = , UndoUpgradeEntryPointExe = , UndoUpgradeEntryPointExeParameters = , }TargetInstallation = WindowsFabricDeploymentDescription { IsValid = true, InstanceId = 0, MSILocation = D:\ProgramData\SF\ServiceFabric.cab, ClusterManifestLocation = D:\ProgramData\SF\clusterManifest.xml, InfrastructureManifestLocation = , NodeName = , UpgradeEntryPointExe = FabricSetup.exe, UpgradeEntryPointExeParameters = /operation:Install, UndoUpgradeEntryPointExe = , UndoUpgradeEntryPointExeParameters = , }} 2017-05-14 03:45:24.839,Warning ,4640,FabricInstallerService.FabricUpgradeManager,Rollback cannot be performed since the current installation is not present or invalid 2017-05-14 03:45:24.839,Noise ,4640,General.AsyncOperation@178d5095f40,**FinishComplete called with FABRIC_E_UPGRADE_FAILED 2017-05-14 03:45:24.839,Warning** ,4640,FabricInstallerService.FabricUpgradeManager,Upgrade finished with error FABRIC_E_UPGRADE_FAILED 2017-05-14 03:45:24.839,Info ,2652,General.FabricInstallerServiceImpl,service stopping (shutdown = false) ... 2017-05-14 03:45:24.839,Info ,2652,General.FabricInstallerServiceImpl,Stop FabricUpgradeManager called 2017-05-14 03:45:24.839,Info ,3152,General.FabricInstallerServiceImpl,Close FabricUpgradeManager, with timeout 5:00.000 2017-05-14 03:45:24.839,Noise ,3152,General.AsyncOperation@178d5095a10,Attempting to attach child AsyncOperation 178d50902b0. 2017-05-14 03:45:24.839,Noise ,3152,General.AsyncOperation@178d50902b0,Calling OnStart 2017-05-14 03:45:24.839,Noise ,3152,General.AsyncOperation@178d50902b0,Attempting to attach child AsyncOperation 178d50903b0. 2017-05-14 03:45:24.839,Noise ,3152,General.AsyncOperation@178d50903b0,Calling OnStart 2017-05-14 03:45:24.839,Noise ,3152,General.AsyncOperation@178d50903b0,FinishComplete called with S_OK 2017-05-14 03:45:24.839,Noise ,3152,General.AsyncOperation@178d50902b0,FinishComplete called with S_OK 2017-05-14 03:45:24.839,Noise ,3152,General.FabricInstallerServiceImpl,Close FabricUpgradeManager returned S_OK 2017-05-14 03:45:24.839,Noise ,3152,General.AsyncOperation@178d5095a10,Detaching child AsyncOperation 178d50902b0. 2017-05-14 03:45:24.839,Noise ,3152,General.AsyncOperation@178d50902b0,Detaching child AsyncOperation 178d50903b0.

**Comment by chrissiechi** [comment]
I worked on another thread https://github.com/Azure/service-fabric-issues/issues/226 with Prinup. This is resolved.

**Comment by masnider** [comment]
@chrissiechi @prinupmathew Great!
