### ISSUE TITLE
UpgradeService going unhealthy a lot

### ISSUE THREAD

**Issue by nrandell** [Azure/service-fabric-issues#301]
I've just deployed a brand new azure cluster, and have noticed that I seem to have a lot of issues with the upgrade service often becoming unhealthy. 

The cluster was deployed using an ARM template and is reasonably standard apart from the addition of an application gateway.

Quite often I see these warnings.
```
Unhealthy event: SourceId='UpgradeService.Primary', Property='SFRPStreamChannel', HealthState='Warning', ConsiderWarningAsError=false.
Exception encountered: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpStreamChannel.d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.PaasCoordinator.d__17.MoveNext() 
```
Is this a known problem, or something I've managed to muck up?

**Comment by vaishnavk** [comment]
Can you provide the ResourceId and region? These are typically benign unless this warning persists for a long time.

**Comment by nrandell** [comment]
It's UK South
Resource id is /subscriptions/2a1c29e4-e7d7-44ac-947f-7dd6f475d10a/resourcegroups/sk-sflive-uksouth/providers/Microsoft.ServiceFabric/clusters/sk-sflive

It only seems to happen when I update the ARM template. I'm currently migrating services from an older cluster and periodically update the template to add a new entry to the app gateway. So at the moment there are no problems, but this afternoon when making changes there were.

I only raised it because I wasn't expecting errors in the core system code - my code is full of errors so I'm used to seeing problems, but not in the system side of things.

**Comment by vaishnavk** [comment]
ARM template deployment which results in cluster upgrade can result in this warning where the replicas failover.

We will look into not reporting the warning on such transient issues.

**Comment by coderocks** [comment]
I have this same warning after deploying a new cluster to Central US
Event	
 Warning
 Unhealthy event: SourceId='UpgradeService.Primary', Property='SFRPStreamChannel', HealthState='Warning', ConsiderWarningAsError=false.
Exception encountered: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.get_EndOfStream()
   at System.Fabric.UpgradeService.WrpStreamReader.b__5_0()
   at System.Fabric.UpgradeService.WrpStreamReader.d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpStreamReader.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpStreamChannel.d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpStreamChannel.d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.PaasCoordinator.d__17.MoveNext()

**Comment by vaishnavk** [comment]
Thanks for reporting. These are transient issues that are expected when the service fails over. In the next release we will not report health on such transient issues unless it persists on retry.

**Comment by matterai** [comment]
I have the same issue.
Resource ID: `/subscriptions/db5646d5-7c72-4a24-8c84-dfb275cd3fb8/resourcegroups/LIST101-internal/providers/Microsoft.ServiceFabric/clusters/list101-internal`
Stack:
```
Unhealthy event: SourceId='UpgradeService.Primary', Property='SFRPStreamChannel', HealthState='Warning', ConsiderWarningAsError=false.
Exception encountered: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpStreamChannel.d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.PaasCoordinator.d__17.MoveNext()
```
System service `fabric:/System/UpgradeService` is still with yellow marked and could not start to be a green. I suppose in close time he does. But anyway, how can I upgrade my app with this issue? I could not do it because of this error. Or should I just try to upgrade one more time?

**Comment by vabgujral** [comment]
Any updates on this one? It says "fix coming", but, we have seen the warning recently. Also, we have noticed that our cluster has not upgraded since last 3 SDK releases which has started breaking our deployments now.

**Comment by vaishnavk** [comment]
@matterai : The warning does not affect any upgrade. It is in no way related to application or application upgrade.

@vabgujral : What is the version of your cluster? In 5.7.x.x, we have increased the threshold for reporting warning. If you are 5.7.x.x and seeing this issue, let us know you cluster details and we can take a look.

**Comment by vabgujral** [comment]
Our cluster is running on 5.6.xxx.

**Comment by niravbhalodiya** [comment]
Hi,
@vaishnavk :
I am also facing similar issue while deploying the cluster properties changes through ARM template. 
My deployment is running since almost 2 hours and still not completed.

Please see below error in Upgrade Service

Error event: SourceId='UpgradeService.Primary', Property='SFRPPoll'.
Exception encountered: System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Fabric.UpgradeService.RestClientHelper.d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpGatewayClient.d__12`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpPackageRetriever.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.PaasCoordinator.d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.PaasCoordinator.d__18.MoveNext()

**Comment by slandsaw** [comment]
Having the same sort of issue with two different clusters, both running 5.7.198.9494.

Cluster # 1 (3 Node)

Error event: SourceId='UpgradeService.Primary', Property='SFRPPoll'. Exception encountered: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()    at System.Fabric.UpgradeService.RestClientHelper.d__1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.WrpGatewayClient.d__12`2.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.WrpPackageRetriever.d__4.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.PaasCoordinator.d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.PaasCoordinator.d__18.MoveNext()
--

Cluster # 2 (5 Node)

Error event: SourceId='UpgradeService.Primary', Property='SFRPStreamChannel'. Exception encountered: System.Fabric.UpgradeService.StreamChannelException: Exception of type 'System.Fabric.UpgradeService.StreamChannelException' was thrown.    at System.Fabric.UpgradeService.WrpStreamChannel.d__26.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.WrpStreamChannel.d__16`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.WrpStreamChannel.d__15.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Fabric.UpgradeService.PaasCoordinator.d__17.MoveNext()
--

I have a 3rd cluster (5 node) also running 5.7 that is not affected.

**Comment by srberard** [comment]
We're seeing something similar to this on our cluster as well.  We're on 5.7.198.9494.  

```
Error event: SourceId='UpgradeService.Primary', Property='SFRPPoll'.
Exception encountered: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Fabric.UpgradeService.RestClientHelper.d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpGatewayClient.d__12`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpPackageRetriever.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.PaasCoordinator.d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.PaasCoordinator.d__18.MoveNext()
```
We're not seeing this on our other clusters at the moment.  Those are running 5.6.x

**Comment by Krishna-teja** [comment]
We are seeing the same issues as well on our prod clusters.

**Comment by j-mendoza** [comment]
Seeing the same issues here.

While working on a Service Fabric\VM Scale Set issue, an Azure Support Escalation Engineer emailed me saying the Service Fabric team is working on an issue that is likely impacting me.

The Azure status page is still all green so hopefully they'll update it and keep us in the loop soon.
https://azure.microsoft.com/en-us/status/

**Comment by vaishnavk** [comment]
We had an outage yesterday in the EastUS region which caused the control plane service to go down. This impacted only control plane operations. Existing cluster were not impacted and there should be no impact on services hosted on the cluster. 

This issue has been mitigated now.

**Comment by slandsaw** [comment]
FYI - upgrade service seems to have recovered for me.

**Comment by slandsaw** [comment]
FYI - upgrade service seems to have recovered for me.

**Comment by rbeauchamp** [comment]
Seeing this today in our South Central US deployment: 

Error event: SourceId='UpgradeService.Primary', Property='SFRPStreamChannel'.
Exception encountered: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.get_EndOfStream()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpStreamReader.d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpStreamReader.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpStreamChannel.d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpStreamChannel.d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.ClusterCoordinator.d__16.MoveNext()

**Comment by ChackDan** [comment]
Closing due to lack of response.

**Comment by Mart-Bogdan** [comment]
WE are switched to Kubernates, and it works like a charm!

And deployments are WAYYY faster.
