### ISSUE TITLE
"The upgrade policy is not allowed" ClusterConfigurationUpgrade fails on Standalone Cluster

### ISSUE THREAD

**Issue by chiokejjones** [Azure/service-fabric-issues#349]
v5.6.220.9494 

I've been digging the last few hours trying to figure this out.  I'm receiving the following error when attempting a clusterconfigurationupgrade:

System.Fabric.FabricDeployer.ClusterManifestValidationException: Cluster manifest validation failed with exception System.ArgumentException: The upgrade policy is not allowed
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.CompareSettings(ClusterManifestType newClusterManifest, String nodeTypeNameFilter)
   at System.Fabric.FabricDeployer.FabricValidatorWrapper.CompareAndAnalyze(ClusterManifestType currentClusterManifest, ClusterManifestType targetClusterManifest, Infrastructure infrastructure, DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.FabricValidatorWrapper.CompareAndAnalyze(ClusterManifestType currentClusterManifest, ClusterManifestType targetClusterManifest, Infrastructure infrastructure, DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.Program.Main(String[] args)

I end of having to rollback the upgrade to recover two nodes.  If anyone could help point me in the right direction on resolving this error it'd be appreciated.

**Comment by rishirsinha** [comment]
Can you sanitize and attach the initial and final cluster configuration.

**Comment by rishirsinha** [comment]
@chiokejjones, is this still an issue?

**Comment by chiokejjones** [comment]
Hey @rishirsinha. Sorry for the slow response. The issue was resolved by rebuilding the cluster.  I've since deployed multiple new clusters and completed upgrades without issue.  Thanks for the response.
