### ISSUE TITLE
"System.Fabric.FabricServiceNotFoundException: Service does not exist." On startup.

### ISSUE THREAD

**Issue by jfloodnet** [Azure/service-fabric-issues#393]
Hi,
I'm getting this exception on each deployment.
```

System.Fabric.FabricServiceNotFoundException: Service does not exist. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071BCD
   at System.Fabric.Interop.NativeClient.IFabricServiceManagementClient6.EndResolveServicePartition(IFabricAsyncOperationContext context)
   at System.Fabric.FabricClient.ServiceManagementClient.ResolveServicePartitionEndWrapper(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Client.ServicePartitionResolver.<ResolveAsyncHelper>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Communication.Client.CommunicationClientFactoryBase`1.<GetClientAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.FabricTransport.Client.FabricTransportServiceRemotingClientFactory.<Microsoft-ServiceFabric-Services-Communication-Client-ICommunicationClientFactory<Microsoft-ServiceFabric-Services-Remoting-Client-IServiceRemotingClient>-GetClientAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient`1.<GetCommunicationClient>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient`1.<InvokeWithRetryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.Client.ServiceRemotingPartitionClient.<InvokeAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.<InvokeAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.<ContinueWith>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Ism.ServiceFabric.Actors.ActorRef.<Tell>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ism.TvcRecognition.Infra.Messaging.MessageFilter.<Route>d__4.MoveNext() in T:\TeamCity\buildAgent\work\d40fe32b82edaa91\Ism.TvcRecognition.Infra\Messaging\MessageFilter.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ism.TvcRecognition.Azure.QueueListener.SessionHandler.<OnMessageAsync>d__3.MoveNext() in T:\TeamCity\buildAgent\work\d40fe32b82edaa91\Ism.TvcRecognition.Azure\QueueListener.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceBus.Common.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

```

I have a stateless service that uses a CommunicationListener to register a session handler to Azure Service Bus on OpenAsync. Similar to the approach by loekd - https://github.com/loekd/ServiceFabric.ServiceBus

Note: that when I uses loekd's package I dont get this issue. 

Important differences between my impl. I am using multiple MessagingFactory instances to create multiple receivers. I do this by wiring up multiple CommunicationListeners (this may not be the right approach, not sure)

My code below:

ICommunicationListener implementation

```
   public class SubscriptionSessionHandlerListener : ICommunicationListener
    {
        private MessagingFactory messageingFactory;

        private string connectionString;
        private string topic;
        private string subscription;
        private ILogger log;
        private SubscriptionClient client;
        private SessionHandlerOptions options;
        private Func<IMessageSessionAsyncHandler> handlerFactory;

        public SubscriptionSessionHandlerListener(
            string connectionString, 
            string topic, 
            string subscription, 
            ILogger log, 
            MessagingFactory messageingFactory, 
            SessionHandlerOptions options, 
            Func<IMessageSessionAsyncHandler> handlerFactory)
        {
            this.connectionString = connectionString;
            this.messageingFactory = messageingFactory;
            this.topic = topic;
            this.subscription = subscription;
            this.log = log;
            this.handlerFactory = handlerFactory;
            this.options = options;
        }

        public void Abort()
        {
            client?.Abort();
        }

        public async Task CloseAsync(CancellationToken cancellationToken)
        {
            await client?.CloseAsync();
        }

        public async Task<string> OpenAsync(CancellationToken cancellationToken)
        {
            this.client = messageingFactory.CreateSubscriptionClient(topic, subscription);
            this.client.PrefetchCount = 200;

            await client.RegisterSessionHandlerFactoryAsync(
                new SessionHandlerFactory(log, handlerFactory), options);

            //trying this to see if it fixes the issue where we start up receiving messages before
            //the destination actor's partitions are up and we get handling errors.
            //loekd's package doesn't have this issue, and he also has this magic thread yield statement
            //after registering the session handler factory.??
            Thread.Yield();

            return connectionString;
        }
    }

    internal sealed class SessionHandlerFactory : IMessageSessionAsyncHandlerFactory
    {
        private readonly ILogger log;
        private readonly Func<IMessageSessionAsyncHandler> factory;
        private MessageSession session;

        public SessionHandlerFactory(ILogger log, Func<IMessageSessionAsyncHandler> factory)
        {
            this.log = log;
            this.factory = factory;
        }

        public IMessageSessionAsyncHandler CreateInstance(MessageSession session, BrokeredMessage message)
        {
            this.session = session;

            log.Information("Creating session handler for SessionId {SessionId}", session.SessionId);

            return factory();
        }

        public void DisposeInstance(IMessageSessionAsyncHandler handler)
        {
            log.Information("Closing session handler for SessionId {SessionId}", session.SessionId);
            (handler as IDisposable)?.Dispose();
        }
    }
```

Wirirng up in StatelessService

```
       protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            Func<MessagingFactory> messagingFactory = () => MessagingFactory.CreateFromConnectionString(_settings.ConnectionString);


            return Enumerable.Range(0, 4)
                .Select(i =>
                {
                    return new ServiceInstanceListener(ctx =>
                new SubscriptionSessionHandlerListener(
                    _settings.ConnectionString,
                    _settings.Topic,
                    _settings.Subscription,
                    _log,
                    messagingFactory(),
                     new SessionHandlerOptions()
                     {
                         AutoComplete = true,
                         MaxConcurrentSessions = 5,
                         AutoRenewTimeout = TimeSpan.FromSeconds(100),
                     },
                    () => new SessionHandler(_log, this)),
                    $"StatelessService-ServiceBusSubscriptionListener-Instance-{i}");
                });
        }

```
You will note that in the OpenAsync implmentation, just after RegisterSessionHandlerFactory... I call Thread.Yield. I've cargo culted that from loekd's implementation and this seems to have limited the occurance of these exceptions... but not elimintated them.. I have no idea what this does though :)

This could all be an issue with my approach above and I may have no idea what I'm doing.

Any suggestions on how to handle this exception, or possibly better strategy for listening to azure topics/queues would be appreciated.

Thanks

**Comment by vturecek** [comment]
Do you have multiple Default Services in one application that are attempting to connect to each other when  ICommunicationListener.OpenAsync is called? 

Looking at this stack trace, it looks like you are calling into an Actor service from one of your listeners but it's hard to tell without looking at the code:

```
   at Ism.ServiceFabric.Actors.ActorRef.<Tell>d__3.MoveNext()
   ...

   at Ism.TvcRecognition.Infra.Messaging.MessageFilter.<Route>d__4.MoveNext() in T:\TeamCity\buildAgent\work\d40fe32b82edaa91\Ism.TvcRecognition.Infra\Messaging\MessageFilter.cs:line 37
   ...

   at Ism.TvcRecognition.Azure.QueueListener.SessionHandler.<OnMessageAsync>d__3.MoveNext() in T:\TeamCity\buildAgent\work\d40fe32b82edaa91\Ism.TvcRecognition.Azure\QueueListener.cs:line 123
```

**Comment by jfloodnet** [comment]
Hi - yes that stack trace is routing messages to actors. The queue listener is taking messages off service bus and routing to actors.

**Comment by vturecek** [comment]
Does the exception only occur when you first deploy, or does it continue to occur during the lifetime of the application(s)?

**Comment by jfloodnet** [comment]
Only after first deploying, exceptions disappear after a short time.

**Comment by jfloodnet** [comment]
@vturecek  so more recent monitoring of this issue indicates that this is actually occuring on shutdown.

Would you be able to provide some guidance on how to gracefully handle shut down.. ?

**Comment by mvmurali5** [comment]
I am also facing similar issue where I am reading from EventHub Partition using StatelessService and passing it to the ActorService(Stateful), is your issue resolved?

**Comment by jfloodnet** [comment]
Hi @mvmurali5  it seems I was only receiving this error when the upgrade strategy was to remove the existing application and add the new version. Once I moved to rolling upgrades the issue disappeared, so it's likely only an issue upon shutting down the application in SF.

**Comment by mvmurali5** [comment]
@jfloodnet Great. I solved issue in my solution, I was referring to wrong serviceUri. I misplaced "." with "/" so Actorproxy trying to communicate to service which doesn't exist . It seems like same in your case as well when you upgrading the services it's not able to find the service that you are trying to communicate.
