### ISSUE TITLE
NodeAgentSFUtility crashed and node rebooted

### ISSUE THREAD

**Issue by enemaerke** [Azure/service-fabric-issues#434]
Just happened on our production cluster. Node 4 went missing but recovered after a reboot and the cluster rebalanced. From the EventLog we have the follow information:

Application: NodeAgentSFUtility.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at System.Fabric.Interop.NativeClient+IFabricQueryClient9.EndGetApplicationList2(IFabricAsyncOperationContext)
   at System.Fabric.FabricClient+QueryClient.GetApplicationListAsyncEndWrapper(IFabricAsyncOperationContext)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Finish(IFabricAsyncOperationContext, Boolean)

Exception Info: System.Fabric.FabricTransientException
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.ServiceFabric.PatchOrchestration.NodeAgentSFUtility.Helpers.CoordinatorServiceHelper+<GetApplicationDeployedStatusAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.ServiceFabric.PatchOrchestration.NodeAgentSFUtility.CommandProcessor+<GetApplicationDeployedStatusAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.ServiceFabric.PatchOrchestration.NodeAgentSFUtility.CommandProcessor+<ProcessArguments>d__5.MoveNext()

Exception Info: System.AggregateException
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
   at System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken)
   at Microsoft.ServiceFabric.PatchOrchestration.NodeAgentSFUtility.Program.Main(System.String[])

and

Faulting application name: NodeAgentSFUtility.exe, version: 0.0.0.0, time stamp: 0x591b5739
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18666, time stamp: 0x58f33794
Exception code: 0xe0434352
Fault offset: 0x00000000000095fc
Faulting process id: 0x318c
Faulting application start time: 0x01d3231d6ca8433c
Faulting application path: D:\PatchOrchestrationApplication\NodeAgentNTService\NodeAgentSFUtility.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: ae53eb0a-8f10-11e7-80ca-000d3a25bb7c
Faulting package full name: 
Faulting package-relative application ID:

**Comment by novino** [comment]
Version 1.2.0 of Patch Orchestration Application has the fix for NodeAgentSFUtility crash reported above. 
Would recommend moving to latest version of Patch Orchestration Application to remedy this issue.

**Comment by novino** [comment]
Version 1.2.0 can be downloaded from download link @ https://docs.microsoft.com/azure/service-fabric/service-fabric-patch-orchestration-application
