### ISSUE TITLE
Copy-ServiceFabricApplicationPackage requires re-authorization

### ISSUE THREAD

**Issue by NickDarvey** [Azure/service-fabric-issues#438]
**Repro**
```
Connect-ServiceFabricCluster -ConnectionEndpoint cluster:19000 -AzureActiveDirectory

# Interactive prompt for authorization occurs

Copy-ServiceFabricApplicationPackage -ApplicationPackagePath C:\applicationpackage -ImageStoreConnectionString fabric:ImageStore -ApplicationPackagePathInImageStore ReactorType 
```

**Expected**
Application package is copied to image store.

**Actual**
Interactive prompt for authorization occurs, again. 
If it's authorized, it continues to copy the application package. f it's not authorized (user cancels), or if the PowerShell script is running headless, or if inside the Visual Studio PowerShell Interactive Window; it fails with:
```
[ERROR] Copy-ServiceFabricApplicationPackage : Exception has been thrown by the target of an invocation.
```

and with `-Verbose`:
```
[VERBOSE] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.Fabric.Interop.Utility.RunInMTA(Action action)
   at System.Fabric.Management.ImageStore.NativeImageStoreClient.UploadContent(String remoteDestination, String localSource, IImageStoreProgressHandler progressHandler, TimeSpan timeout, CopyFlag imageCopyFlag, Boolean acquireSourceReaderLock)
   at System.Fabric.Management.ImageStore.NativeImageStoreClient.UploadContent(String remoteDestination, String localSource, TimeSpan timeout, CopyFlag imageCopyFlag, Boolean acquireSourceReaderLock)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Fabric.ImageStoreProxy.UploadContent(String sourceFullPath, String destinationRelativePathInImageStore, TimeSpan timeout)
   at System.Fabric.FabricClient.ImageStoreClient.Upload(String sourceFullPath, String destinationRelativePath, Boolean shouldOverwrite, TimeSpan timeout, IImageStoreProgressHandler progressHandler)
   at Microsoft.ServiceFabric.Powershell.CommonCmdletBase.UploadToImageStore(String imageStoreConnectionString, String src, String des, UploadProgressHandler progressHandler)
   at Microsoft.ServiceFabric.Powershell.CopyApplicationPackage.ProcessRecord()
```

**Comment by linggengmsft** [comment]
Hey @NickDarvey , thanks for reporting this issue. This is known bug of FabricClient which starts a new connection when communicating to FileStore service. We are fixing this.
However, please note the duplicate authentication window will only pop-up again on the first "Copy-ServiceFabricApplicationPackage" and will not require again in the followings.

**Comment by vturecek** [comment]
Keeping this open until it makes it into a release.

**Comment by ShaiNahum** [comment]
Any updates on this? We just faced it as well.
 We managed to avoid having the extra AAD pop up by using a SecurityToken, but we get the same error message if we try to deploy when the current directory is a read-only location

Suggested workaround to anyone else facing this: change the working directory before the deployment to a place where you have write permissions.

**Comment by stijnherreman** [comment]
Are you still working on this? Is it possible to work around this issue and publish from within Visual Studio?
