### ISSUE TITLE
Service Fabric Deployment failing due to XML Parsing issue of ApplicationManifest.xml

### ISSUE THREAD

**Issue by debstf** [Azure/service-fabric-issues#443]
Hi,

My Service Fabric Deployment is failing due to the below error -

**[error]Exception while parsing XML file: d:\a\_temp\TestApplicationPackage_2683537459\y2v5kdk3.uso\applicationpackage\ApplicationManifest.xml**

Found an workaround solution in -
https://github.com/Azure/service-fabric-issues/issues/209

As per the resolution, I have added  AddCorrelationIds as false, but still it's showing the error. 

Please find below the error desc -

`2017-09-07T16:34:14.4774525Z ##[debug]Join-Path "C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code" "ServiceFabricServiceModel.xsd"
2017-09-07T16:34:14.4834313Z ##[debug]C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code\ServiceFabricServiceModel.xsd
2017-09-07T16:34:14.4844313Z ##[debug]Length: 94
2017-09-07T16:34:14.4854334Z ##[debug]
2017-09-07T16:34:14.4874331Z ##[debug]Test-Path "C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code\ServiceFabricServiceModel.xsd"
2017-09-07T16:34:14.4914317Z ##[debug]True
2017-09-07T16:34:14.4924526Z ##[debug]
2017-09-07T16:34:14.9789828Z ##[debug]System.Fabric.Management.ImageBuilder.FabricImageBuilderValidationException: Exception while parsing XML file: d:\a\_temp\TestApplicationPackage_2636180577\scb1weq1.n5l\applicationpackage\ApplicationManifest.xml
2017-09-07T16:34:14.9799075Z ##[debug]FileName: d:\a\_temp\TestApplicationPackage_2636180577\scb1weq1.n5l\applicationpackage\ApplicationManifest.xml ---> System.InvalidOperationException: There is an error in XML document (19, 42). ---> System.Xml.Schema.XmlSchemaValidationException: The 'ServicePackageActivationMode' attribute is not declared.
2017-09-07T16:34:14.9809409Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(XmlSchemaValidationException e, XmlSeverityType severity)
2017-09-07T16:34:14.9819403Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(String code, String arg)
2017-09-07T16:34:14.9829167Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String lName, String ns, XmlValueGetter attributeValueGetter, String attributeStringValue, XmlSchemaInfo schemaInfo)
2017-09-07T16:34:14.9849153Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String localName, String namespaceUri, XmlValueGetter attributeValue, XmlSchemaInfo schemaInfo)
2017-09-07T16:34:14.9859075Z ##[debug]   at System.Xml.XsdValidatingReader.ValidateAttributes()
2017-09-07T16:34:14.9869096Z ##[debug]   at System.Xml.XsdValidatingReader.ProcessElementEvent()
2017-09-07T16:34:14.9879096Z ##[debug]   at System.Xml.XsdValidatingReader.Read()
2017-09-07T16:34:14.9889097Z ##[debug]   at System.Xml.XmlReader.MoveToContent()
2017-09-07T16:34:14.9899095Z ##[debug]   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read170_DefaultServicesType(Boolean isNullable, Boolean checkType)
2017-09-07T16:34:14.9909094Z ##[debug]   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read212_ApplicationManifestType(Boolean isNullable, Boolean checkType)
2017-09-07T16:34:14.9919175Z ##[debug]   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read395_ApplicationManifest()
2017-09-07T16:34:14.9939151Z ##[debug]   --- End of inner exception stack trace ---
2017-09-07T16:34:14.9949078Z ##[debug]   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
2017-09-07T16:34:14.9959150Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReader reader)
2017-09-07T16:34:14.9969151Z ##[debug]   --- End of inner exception stack trace ---
2017-09-07T16:34:14.9979076Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.TraceAndThrowValidationErrorWithFileName(Exception innerException, String type, String fileName, String format, Object[] args)
2017-09-07T16:34:14.9989076Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReader reader)
2017-09-07T16:34:14.9999152Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReaderSettings validatingXmlReaderSettings)
2017-09-07T16:34:15.0009179Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ParseApplicationPackageAsync>d__8.MoveNext()
2017-09-07T16:34:15.0019174Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2017-09-07T16:34:15.0029246Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-07T16:34:15.0039432Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-07T16:34:15.0059156Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ProvisionApplicationAsync>d__0.MoveNext()
2017-09-07T16:34:15.0503104Z ##[debug]Leaving D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.3.10\deploy.ps1.
2017-09-07T16:34:15.0623419Z ##[debug]Caught exception from task script.
2017-09-07T16:34:15.0653311Z ##[debug]Error record:
2017-09-07T16:34:15.1613083Z ##[debug]Test-ServiceFabricApplicationPackage : Exception while parsing XML file: d:\a\_temp\TestApplicationPackage_2636180577\scb1weq1.n5l\applicationpackage\ApplicationManifest.xml
2017-09-07T16:34:15.1623120Z ##[debug]FileName: d:\a\_temp\TestApplicationPackage_2636180577\scb1weq1.n5l\applicationpackage\ApplicationManifest.xml
2017-09-07T16:34:15.1633102Z ##[debug]At D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.3.10\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:138 char:38
2017-09-07T16:34:15.1643079Z ##[debug]+ ... tionSuccess = (Test-ServiceFabricApplicationPackage $AppPkgPathToUse)
2017-09-07T16:34:15.1653086Z ##[debug]+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2017-09-07T16:34:15.1653086Z ##[debug]    + CategoryInfo          : InvalidOperation: (:) [Test-ServiceFabricApplicationPackage], FabricImageBuilderValidati    onException
2017-09-07T16:34:15.1663090Z ##[debug]    + FullyQualifiedErrorId : TestApplicationPackageErrorId,Microsoft.ServiceFabric.Powershell.TestApplicationPackage
2017-09-07T16:34:15.1673088Z ##[debug] 
2017-09-07T16:34:15.1693097Z ##[debug]Script stack trace:
2017-09-07T16:34:15.1733091Z ##[debug]at Publish-NewServiceFabricApplication, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.3.10\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1: line 138
2017-09-07T16:34:15.1743090Z ##[debug]at <ScriptBlock>, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.3.10\deploy.ps1: line 151
2017-09-07T16:34:15.1753094Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-09-07T16:34:15.1763092Z ##[debug]at <ScriptBlock>, <No file>: line 22
2017-09-07T16:34:15.1773093Z ##[debug]at <ScriptBlock>, <No file>: line 18
2017-09-07T16:34:15.1793084Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-09-07T16:34:15.1803098Z ##[debug]Exception:
2017-09-07T16:34:15.1843091Z ##[debug]System.Fabric.Management.ImageBuilder.FabricImageBuilderValidationException: Exception while parsing XML file: d:\a\_temp\TestApplicationPackage_2636180577\scb1weq1.n5l\applicationpackage\ApplicationManifest.xml
2017-09-07T16:34:15.1893095Z ##[debug]FileName: d:\a\_temp\TestApplicationPackage_2636180577\scb1weq1.n5l\applicationpackage\ApplicationManifest.xml ---> System.InvalidOperationException: There is an error in XML document (19, 42). ---> System.Xml.Schema.XmlSchemaValidationException: The 'ServicePackageActivationMode' attribute is not declared.
2017-09-07T16:34:15.1893095Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(XmlSchemaValidationException e, XmlSeverityType severity)
2017-09-07T16:34:15.1893095Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(String code, String arg)
2017-09-07T16:34:15.1893095Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String lName, String ns, XmlValueGetter attributeValueGetter, String attributeStringValue, XmlSchemaInfo schemaInfo)
2017-09-07T16:34:15.1903079Z ##[debug]   at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String localName, String namespaceUri, XmlValueGetter attributeValue, XmlSchemaInfo schemaInfo)
2017-09-07T16:34:15.1913079Z ##[debug]   at System.Xml.XsdValidatingReader.ValidateAttributes()
2017-09-07T16:34:15.1923086Z ##[debug]   at System.Xml.XsdValidatingReader.ProcessElementEvent()
2017-09-07T16:34:15.1923086Z ##[debug]   at System.Xml.XsdValidatingReader.Read()
2017-09-07T16:34:15.1943082Z ##[debug]   at System.Xml.XmlReader.MoveToContent()
2017-09-07T16:34:15.1953086Z ##[debug]   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read170_DefaultServicesType(Boolean isNullable, Boolean checkType)
2017-09-07T16:34:15.1963090Z ##[debug]   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read212_ApplicationManifestType(Boolean isNullable, Boolean checkType)
2017-09-07T16:34:15.1973090Z ##[debug]   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read395_ApplicationManifest()
2017-09-07T16:34:15.1983091Z ##[debug]   --- End of inner exception stack trace ---
2017-09-07T16:34:15.1993086Z ##[debug]   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
2017-09-07T16:34:15.2003079Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReader reader)
2017-09-07T16:34:15.2013091Z ##[debug]   --- End of inner exception stack trace ---
2017-09-07T16:34:15.2023097Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.TraceAndThrowValidationErrorWithFileName(Exception innerException, String type, String fileName, String format, Object[] args)
2017-09-07T16:34:15.2033088Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReader reader)
2017-09-07T16:34:15.2033088Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.ReadXml[T](String fileName, XmlReaderSettings validatingXmlReaderSettings)
2017-09-07T16:34:15.2053099Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ParseApplicationPackageAsync>d__8.MoveNext()
2017-09-07T16:34:15.2063082Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2017-09-07T16:34:15.2073090Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-07T16:34:15.2073090Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-07T16:34:15.2083090Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ProvisionApplicationAsync>d__0.MoveNext()
2017-09-07T16:34:15.2363087Z ##[error]Exception while parsing XML file: d:\a\_temp\TestApplicationPackage_2636180577\scb1weq1.n5l\applicationpackage\ApplicationManifest.xml
FileName: d:\a\_temp\TestApplicationPackage_2636180577\scb1weq1.n5l\applicationpackage\ApplicationManifest.xml
2017-09-07T16:34:15.2363087Z ##[debug]Processed: ##vso[task.logissue type=error]Exception while parsing XML file: d:\a\_temp\TestApplicationPackage_2636180577\scb1weq1.n5l\applicationpackage\ApplicationManifest.xml%0D%0AFileName: d:\a\_temp\TestApplicationPackage_2636180577\scb1weq1.n5l\applicationpackage\ApplicationManifest.xml
2017-09-07T16:34:15.2383079Z ##[debug]Processed: ##vso[task.complete result=Failed]`

Here is my sfproj file -

`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" InitialTargets=";ValidateMSBuildFiles">
  <Import Project="..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props" Condition="Exists('..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.0\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" />
  <PropertyGroup Label="Globals">
    <ProjectGuid>5c1d457c-6d01-42ff-a54e-cc713b9319bc</ProjectGuid>
    <ProjectVersion>1.6</ProjectVersion>
    <MinToolsVersion>1.5</MinToolsVersion>
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
    <AddCorrelationIds>false</AddCorrelationIds>
  </PropertyGroup>
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|x64">
      <Configuration>Debug</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <ItemGroup>
    <None Include="ApplicationPackageRoot\ApplicationManifest.xml" />
    <None Include="ApplicationParameters\Cloud.xml" />
    <None Include="ApplicationParameters\Local.1Node.xml" />
    <None Include="ApplicationParameters\Local.5Node.xml" />
    <None Include="PublishProfiles\Cloud.xml" />
    <None Include="PublishProfiles\Local.1Node.xml" />
    <None Include="PublishProfiles\Local.5Node.xml" />
    <None Include="Scripts\Deploy-FabricApplication.ps1" />
  </ItemGroup>`

Thanks in advance for your help/suggesion.

Best,
Deb

**Comment by debstf** [comment]
Resolved the Issue. Resolution -
- Update the Visual Studio 2017 to 15.3.3.
- Clean the solution and Rebuild the solution.
- It removed the "Service Package Activation Mode" from Application Manifest.
- Re-Deployed it in Azure.

Thanks.

Best,
Deb
