### ISSUE TITLE
UpgradeOrchestrationService in Quorum Loss after failed 5.7 Upgrade

### ISSUE THREAD

**Issue by njtrentacoste** [Azure/service-fabric-issues#465]
My UpgradeOrchestrationService is in perpetual Quorum Loss after I performed an upgrade to 5.7 from 5.6.  The upgrade failed and was automatically rolled back.  I tried executing Repair-ServiceFabricPartition several times and still hasn't fixed it.  I tried rebooting one of the nodes but that doesn't seem to have fixed the issue.  Any guidance would be greatly appreciated.

I have the following in my event log:  

Application Error Event Details:
Faulting application name: FabricUOS.exe, version: 5.6.220.9494, time stamp: 0x592fc24b
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x80131623
Fault offset: 0x00007ffcb7e5e080
Faulting process id: 0x1f84
Faulting application start time: 0x01d33242408ea0c8
Faulting application path: C:\ServiceFabric\HVTestSvcFabric\Fabric\work\Applications\__FabricSystem_App4294967295\UOS.Code.Current\FabricUOS.exe
Faulting module path: unknown
Report Id: bdd59fc9-9e35-11e7-80de-00155dca6aa8
Faulting package full name: 
Faulting package-relative application ID: 

Accompanying .NET Runtime Event Details:
Application: FabricUOS.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: RunAsync failed due to an unhandled exception causing the host process to crash: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.ServiceFabric.ClusterManagementCommon.ClusterManifestBuilder.<>c.<SortClusterManifest>b__49_3(SettingsOverridesTypeSection section)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.ServiceFabric.ClusterManagementCommon.ClusterManifestBuilder.SortClusterManifest(ClusterManifestType clusterManifest)
   at Microsoft.ServiceFabric.ClusterManagementCommon.ClusterManifestBuilder.UpdateClusterManifest(Security security, ClusterManifestType existingClusterManifest, IEnumerable`1 nodeTypes, FabricSettingsMetadata settingsMetadata, String clusterManifestVersion, CertificateDescription fileStoreCert, List`1 whiteList)
   at Microsoft.ServiceFabric.ClusterManagementCommon.ClusterManifestBuilder.UpdateClusterManifest(ClusterManifestType existingClusterManifest, FabricSettingsMetadata existingSettingsMetadata)
   at Microsoft.ServiceFabric.ClusterManagementCommon.SimpleClusterUpgradeState.StartProcessing()
   at Microsoft.ServiceFabric.ClusterManagementCommon.ClusterUpgradeStateFactory.TryCreateUpgradeState(IUserConfig csmConfig, IAdminConfig wrpConfig, ClusterNodeConfig nodeConfig, ClusterUpgradeStateBase& clusterUpgradeState)
   at Microsoft.ServiceFabric.ClusterManagementCommon.ClusterResourceStateMachine.TryProcessUpgrade()
   at System.Fabric.UpgradeOrchestration.Service.FabricUpgradeOrchestrationService.<RunUpgradeOrchestrationHelperAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeOrchestration.Service.FabricUpgradeOrchestrationService.<RunAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.<ExecuteRunAsync>d__23.MoveNext()
Stack:
   at System.Environment.FailFast(System.String)
   at Microsoft.ServiceFabric.Services.Runtime.ServiceHelper.HandleRunAsyncUnexpectedException(System.Fabric.IServicePartition, System.Exception)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter+<ExecuteRunAsync>d__23.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(Boolean)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(Boolean)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter+<WaitForWriteStatusAsync>d__25.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Threading.Tasks.Task+DelayPromise.Complete()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by Liphi** [comment]
1. When does the error happen, before rollback begins, before rollback finishes, or after rollback begins but before Repair-ServiceFabricPartition, or after Repair-ServiceFabricPartition?
2. May I know how u performed 5.6->5.7 upgrade? Did u call Start-ServiceFabricClusterUpgrade?
3. What is the code upgrade path of ur cluster? Was it created at 5.6, or was it created at some prior version and upgraded to 5.6?
4. What is the config upgrade path of ur cluster? After the cluster is created, did u perform config upgrade? Is it possible to share the version of cluster config before 5.6->5.7 upgrade began, with sensitive info replaced with place holders?

**Comment by njtrentacoste** [comment]
See my answers below:

1.) To be honest I don't know the exact point it started.  I started the cluster upgrade, it succeeded on 1 node, then failed on the 2nd and rolled back.  After rollback completed, I noticed the error with the UpgradeOrchestrationService.  I've issued the Repair-ServiceFabricPartition command several times since it's been an issue and the problem does not resolve.
2.) I performed the upgrade from a separate machine I use to deploy applications to the cluster.  It is a Windows Server 2016 machine, not part of the cluster, with both SDK and Runtime v5.6 installed.  I used the powershell command you stated.  My cluster has internet connectivity so it had downloaded the updated runtime code package.
3.) My cluster was created at 5.6.  Full disclosure, it was originally a 5.5 cluster which I had errors upgrading to 5.6 so I tore it down and started fresh with 5.6.  This however is no longer an option as I have applications deployed to it and I'm looking for help in case this becomes an issue when upgrading my production cluster.
4.) I don't completely understand this question, however I've never performed a configuration upgrade on this cluster.  Being as I started with 5.6 this is the first upgrade I'm doing.  Please see the config attached.
[ClusterConfig.json.txt](https://github.com/Azure/service-fabric-issues/files/1337566/ClusterConfig.json.txt)

**Comment by Liphi** [comment]
Thx. Will investigate, and get back to u.

**Comment by taxiatms** [comment]
@njtrentacoste I tried to start a gmsa cluster and upgrade, can't repro the error. Could you let me know the exact command you used to upgrade your cluster?  Thanks.

**Comment by njtrentacoste** [comment]
@taxiatms I followed the docs, executed Get-ServiceFabricRegisteredClusterCodeVersion to get the full 5.7 version followed by Start-ServiceFabricClusterUpgrade -Code -CodePackageVersion 5.7.198.9494 -Monitored -FailureAction Rollback

At the moment, I'd really like to get the UpgradeOrchestrationService back up and running so I can retry the upgrade.  I tried upgrading while the UpgradeOrchestrationService was in QuorumLoss and it rolled back after failing on the 2nd node.

Please let me know if I can provide any more information to assist.

**Comment by taxiatms** [comment]
@njtrentacoste can you send me (taxi@microsoft.com) the trace logs under DeploymentTraces? it's in the same folder in the StandAlone package. We will take a look and try to get back to you.

**Comment by njtrentacoste** [comment]
@taxiatms I don't have any DeploymentTraces for this upgrade.  Is that because the code is already in the imagestore?

**Comment by taxiatms** [comment]
@njtrentacoste Could you take a look at "C:\\ServiceFabric\\Log" in one of the three machines you built the cluster as well?

**Comment by nahmed01** [comment]
Hi, I am also having similar issue.
I upgraded code version to 6.1.456 which went fine.then i had to remove and recreate my cluster.
after recreating the cluster, "upgradeorchestrationservice" is in quorum loss, not sure how to fix, any help will be appreciated
![image](https://user-images.githubusercontent.com/36216668/35896214-5439848e-0c0f-11e8-9bd8-d196b493ae40.png)

**Comment by rishirsinha** [comment]
@nahmed01. This seems to be a different issue. Can you open a new issue please?

**Comment by nahmed01** [comment]
ok will do thanks

**Comment by oanapl** [comment]
There has been no activity in a long time, so I will close this issue. Please open a new issue if there is any follow up needed.
