### ISSUE TITLE
Deleting application created via compose always fails with max retries.

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#469]
Hello Team,

Below command always fails. as with compose we cant upgrade currently. 

sfctl compose remove --application-id fabric:/ClaimContainerV1

Error occurred in request., RetryError: HTTPConnectionPool(host='XXXXX', port=19080): Max retries exceeded with url: /ComposeDeployments/fabric:/ClaimContainerV1/$/Delete?api-version=4.0-preview&timeout=60 (Caused by ResponseError('too many 500 error responses',))
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "c:\program files\python36\lib\site-packages\urllib3\connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "c:\program files\python36\lib\site-packages\urllib3\connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "c:\program files\python36\lib\site-packages\urllib3\connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "c:\program files\python36\lib\site-packages\urllib3\connectionpool.py", line 712, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "c:\program files\python36\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='XXXXX', port=19080): Max retries exceeded with url: /ComposeDeployments/fabric:/ClaimContainerV1/$/Delete?api-version=4.0-preview&timeout=60 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\msrest\service_client.py", line 189, in send
    **kwargs)
  File "c:\program files\python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\program files\python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "c:\program files\python36\lib\site-packages\requests\adapters.py", line 499, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPConnectionPool(host='XXXXX', port=19080): Max retries exceeded with url: /ComposeDeployments/fabric:/ClaimContainerV1/$/Delete?api-version=4.0-preview&timeout=60 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\knack\cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\program files\python36\lib\site-packages\knack\invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "c:\program files\python36\lib\site-packages\knack\commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "c:\program files\python36\lib\site-packages\knack\commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "c:\program files\python36\lib\site-packages\azure\servicefabric\service_fabric_client_ap_is.py", line 7751, in remove_compose_application
    response = self._client.send(request, header_parameters, **operation_config)
  File "c:\program files\python36\lib\site-packages\msrest\service_client.py", line 215, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "c:\program files\python36\lib\site-packages\msrest\exceptions.py", line 47, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "c:\program files\python36\lib\site-packages\msrest\service_client.py", line 189, in send
    **kwargs)
  File "c:\program files\python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\program files\python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "c:\program files\python36\lib\site-packages\requests\adapters.py", line 499, in send
    raise RetryError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPConnectionPool(host='XXXXX', port=19080): Max retries exceeded with url: /ComposeDeployments/fabric:/ClaimContainerV1/$/Delete?api-version=4.0-preview&timeout=60 (Caused by ResponseError('too many 500 error responses',))

**Comment by oanapl** [comment]
From the documentation:

 --application-id [Required]: The identity of the application. This is typically the full name of the application without the 'fabric:' URI scheme.

Can you try to remove fabric:/ from the application id?

**Comment by oanapl** [comment]
@nareshkhatri81, any update here?
I recommend you upgrade to our latest SF version, 6.0 and sfctl 2.0. New sfctl provides upgrade for compose deployments too (make sure you update SF, as sfctl doesn't work against older SF versions).

sfctl compose --help
Group
    sfctl compose: Create, delete and manage Docker Compose applications.

Commands:
    create        : Creates a Service Fabric compose deployment.
    list          : Gets the list of compose deployments created in the Service Fabric cluster.
    remove        : Deletes an existing Service Fabric compose deployment from cluster.
    status        : Gets information about a Service Fabric compose deployment.
    upgrade       : Starts upgrading a compose deployment in the Service Fabric cluster.
    upgrade-status: Gets details for the latest upgrade performed on this Service Fabric compose
                    deployment.

**Comment by oanapl** [comment]
@nareshkhatri81, we haven't heard back from you. I will close the issue hoping the suggestions were useful. Please re-open if you are still blocked.
