### ISSUE TITLE
FabricClient error on version 2.8.211

### ISSUE THREAD

**Issue by marvinvperez** [Azure/service-fabric-issues#476]
Hi,
I update my service fabric service project reference to the latest version
`<PackageReference Include="Microsoft.ServiceFabric.Services.Remoting" Version="2.8.211" />`
But now I'm getting exception when I try to use fabric client, e.g.
`var fc = new FabricClient("localhost:19000")`

I'm getting this error:
```
`Unhandled Exception: System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'IFabricClusterManagementClient10'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{A4ACEB4F-2E2B-4BE1-9D12-44FE8CB5FB20}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.Fabric.FabricClient.CreateNativeClient(IEnumerable`1 connectionStringsLocal)
   at System.Fabric.Interop.Utility.<>c__DisplayClass27_0.<WrapNativeSyncInvoke>b__0()
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   at System.Fabric.Interop.Utility.RunInMTA(Action action)
   at System.Fabric.FabricClient.InitializeFabricClient(SecurityCredentials credentialArg, FabricClientSettings newSettings, String[] hostEndpointsArg)
   at ASFClusterMaintenance.ASFClusterManager.CreateFabricClient()
   at ASFClusterMaintenance.ASFClusterManager..ctor(String clusterConnectionString, String sslThumbprint, String username, String password)
   at ASFClusterMaintenance.Program.Main(String[] args)`
```

**Comment by MikkelHegn** [comment]
You need to update the local cluster runtime to version 6.0. As a general guidance, you should not expect newer NuGet packages to work against "older" runtime versions. The 2.8 NuGet packages are released with the 6.0 runtime. You can get the local runtime update through Web Platform Installer.

**Comment by marvinvperez** [comment]
Thanks @MikkelHegn  we could close it now. cheers!

**Comment by ddobric** [comment]
Have same issue.
Using  SF SDK 2.8.232.. and SF 6.0.232.9494.

@MikkelHegn what does it mean 2.0? 2.8.0 or 2.8.*

Btw. I have installed newest bits on the fresh machine. There were not any upgrades in place.
It seems that currently publicly available bits including docs lead to the issue.
