### ISSUE TITLE
Installing Fabric Cluster results in unhealthy Fault Manager

### ISSUE THREAD

**Issue by tbertenshaw** [Azure/service-fabric-issues#479]
In the last 24 hours i have tried several times to create a Azure Service Fabric 5 node unsecured cluster.  Using the new Burstable Vm's (2cpu 8G ram, 8G HDD), with default options but also the faultanalysis service and DNS service.. And after over an hour of provisioning, the nodes are still in baseline upgrade with an error against the FaultAnalysis service. The first two times i got out of disk space errors. and this last time i have the below error. I initially tried using the Automatic Upgrade which gave me the new v6.0.211.9494 version but i suspected this had faults so tried the oldest v5.7.198.9494 which gives me the below error.  ( i have successfully created a similar cluster using the D series machines with a similar spec and had no disk space issues. 

```
Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false.
Replica had multiple failures in_burst_0 API call: IStatefulServiceReplica.Open(); Error = System.Fabric.FabricException (-2147024784)
An error occurred during this operation.  Please check the trace logs for more details.
System.Runtime.InteropServices.COMException (-2147024784)
There is not enough space on the disk. (Exception from HRESULT: 0x80070070)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.Data.Log.LogManager.d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.KtlLogManager.d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.KtlLogManager.d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.LoggingReplicator.d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.LoggingReplicator.d__135.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.d__109.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.TransactionalReplicator.d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Replicator.StatefulServiceReplica.d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.d__18.MoveNext()
```

**Comment by ChackDan** [comment]
Please follow the minimums as recommended in [https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-capacity#primary-node-type---capacity-guidance]

The failure just seems to indicate that _"There is not enough space on the disk."_ SF team is still validating the behavior of the new burstable VMs and will make a recommendation on its use (or not) at a later time.

**Comment by tbertenshaw** [comment]
Ok so that would imply that its the tempo storagesize which is the disk space issue the Standard_B2ms on [this](http://vmsizebrowser.azurewebsites.net/#/EastUS/2/2/0/32) lists as 16Gb. I think i chose a Standard_D2s_v3. It would be particularly useful if i could use one of the cheaper burstable machines. As then it would make evaluating SF on Azure more cost effective using Azure Credits (Visual Studio Subbscription)

**Comment by tbertenshaw** [comment]
I've just tried this again twice. Once using the same Standard_B2ms vms using windows 2016 with containers and also using windows 2016 core (to see if it was the container support was pushing the disk space over that available). This time the nodes all came up successfully. So seems like this has been rectified? maybe with a newer version of the service fabric runtime?

**Comment by tbertenshaw** [comment]
nah same issue again today with a new Standard_B2s 	using 2016-Datacenter-Server-Core. Would have expected more space as servercore has a smaller footprint?  Would be really helpful if there was a resolution to this as it makes evaluating Fabric cheaper

**Comment by tbertenshaw** [comment]
So after Inspecting the ARM template from an existing cluster, i can see that the SF extension defaults to the D drive (temp storage). In existing deployments of scalesets we have added an additional HDD via the template and then created the partition and formatted etc using a custom powershell extension. 

This would potentially be a good way for people to try SF out in azure by choosing a cheap VM sku (**Standard_B2S** 2vCPUs 4GB **£26.95**), but add an additional hdd to it and default the SF install to be on that drive. as the cost of an additional 32GB HDD (**£1.15** for standard managed) plus the cost of a cheap B series machine is significantly cheaper than an equivalent D series machine.

The only problem i can foresee is the issue with scaleset extensions running in parallel during deployment. And then potentially the HDD wouldn't be formatted by the time the SF extension was installed. 

Are there any known workarounds to that?

**Comment by SamirFarhat** [comment]
I'm encountering the same issue. T
You can modify the template and  make a dependeny on the SF extension to start after the custom script ends. I have done similar things on the past

**Comment by SamirFarhat** [comment]
Though, the Azure team shoul fix this problem, or remove these series from the portal

**Comment by tbertenshaw** [comment]
@SamirFarhat didn't know you could do that, Was pretty sure that extensions run in parallel on scalesets and thus you cannot be sure what order they run in.

**Comment by CRuppert** [comment]
@ChackDan  This is still a problem, and the portal STILL allows us to create them. I've lost half a day on this. :/ frustrating.

**Comment by ChackDan** [comment]
Thankyou for reporting this. sorry about the issues. 
Adding Alex and Tassaduq to follow up on this.
