### ISSUE TITLE
Docker Compose throws exception bad request.

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#504]
Hello Issue

Error while deploying to cluster with compose command.

Where can i find actual error whats wrong ? 

Command
--- sfctl compose create --name Claim1003 --file-path D:\ProjectsV1\sf-docker-compose.yml 

Error -
Operation returned an invalid status code 'Bad Request'
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\knack\cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\python27\lib\site-packages\knack\invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "c:\python27\lib\site-packages\knack\commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "c:\python27\lib\site-packages\knack\commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "c:\python27\lib\site-packages\sfctl\custom_compose.py", line 75, in create
    client.create_compose_deployment(desc, timeout=timeout)
  File "c:\python27\lib\site-packages\azure\servicefabric\service_fabric_client_ap_is.py", line 9200, in create_
deployment
    raise models.FabricErrorException(self._deserialize, response)
FabricErrorException: Operation returned an invalid status code 'Bad Request'

Below is compose file.
version: '3.0'

services:
  loss:
    image: lossv1
    ports:
      - "55589:84"
    build:
      context: .
      dockerfile: ClaimDockerfile

**Comment by samedder** [comment]
What version of Service Fabric runtime and sfctl are you using?

**Comment by nareshkhatri81** [comment]
It seems we have latest version of Sfctrl installed which targets latest runtime only.
I looked into documentation and it seems there is way to install older version of stfctrl.
Earlier only command to install service fabric runtime was pip install -I sfctl. I guess documentation is updated now.
I am going to try that and see if that issue is resolved.

**Comment by nareshkhatri81** [comment]
Moved back to older SDK of SF CLI and it worked. Thanks.
