### ISSUE TITLE
CodePackageActivationContext disposed during replica change role

### ISSUE THREAD

**Issue by NickDarvey** [Azure/service-fabric-issues#507]
We have a Service Fabric application and a stateful ASP.NET Core service that is crashing constantly because of a disposed CodePackageActivationContext.

We're using [SomethingSomethingConfig](https://github.com/NickDarvey/SomethingSomethingConfig) (which is based on [this Azure CAT article](https://blogs.msdn.microsoft.com/azurecat/2017/04/06/using-a-custom-service-fabric-configuration-provider-with-asp-net-core/)) to bring in configuration as `IOptions`. It looks like when a ChangeRole is happening, the service tries to start and `CodePackageActivationContext` is disposed, which `SomethingSomethingConfig.ServiceFabricConfigurationProvider` requires, causing it to crash, causing Service Fabric to ChangeRole on another replica.... and yeah, a loop of that.

The only other thing of note is that we also have an extra config package called `Templates` (we've added a folder to `PackageRoot` and defined it as config in `ServiceManifest.xml`.

- Is that method of loading config correct?
- What should we do when 'CodePackageActivationContext' is disposed?
- How do we load config when 'CodePackageActivationContext' is disposed?
- Alternatively, what question am I overlooking that would really solve my problem?

We don't see any logs for this, though we're capturing all the default events and our own.
(The only events we're seeing is Kestrel starting lots and lots, which I'm guessing happens every time SF tries to restart the service.)

The only errors we see are from SFX:
(At this point in time, `_default_8` was running the primary replica and was in error and 'in build'.)
```
Error event: SourceId='System.RA', Property='ReplicaChangeRoleStatus'.
Replica had multiple failures in_default_8 API call: IStatefulServiceReplica.ChangeRole(P); Error = System.ObjectDisposedException (-2146232798)
Cannot access a disposed object.
Object name: 'CodePackageActivationContext'.
   at System.Fabric.CodePackageActivationContext.ThrowIfDisposed()
   at System.Fabric.CodePackageActivationContext.GetConfigurationPackageObject(String packageName)
   at SomethingSomethingConfig.ServiceFabricConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at AtfCloud.Operators.TemplatesOperator.Startup..ctor(IHostingEnvironment env, StatefulServiceContext ctx)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at AtfCloud.Operators.TemplatesOperator.TemplatesService.<>c__DisplayClass2_0.b__1(String url, AspNetCoreCommunicationListener listener)
   at Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.d__19.MoveNext()
 


```

**Comment by harahma** [comment]
Hello @NickDarvey ,

Could you please share the code of your service that is using your utility? Also if you could share a quick sample that can reproduce this issue locally, that will help in investigating it quickly.

Thanks,
Hasibur

**Comment by masnider** [comment]
@NickDarvey Hi there - we haven't heard back from you on this. At this point we're going to close the issue. If you have more information about what you've tried that you can share with us, please just reopen the issue and let us know, or feel free to create a new issue if you prefer.  If you could reopen this with the repro that would be great.
