### ISSUE TITLE
V2 remoting serialization of Service Fabric types

### ISSUE THREAD

**Issue by jricke** [Azure/service-fabric-issues#515]
Getting the following error when using the default data contract provider:

Type 'Microsoft.ServiceFabric.Actors.Remoting.V2.ActorRemotingMessageHeaders' with data contract name 'ActorHeader:urn:actors' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer.

**Comment by jricke** [comment]
Similar issues: 

https://github.com/Azure/service-fabric-issues/issues/497
https://github.com/Azure/service-fabric-issues/issues/502

**Comment by suchiagicha** [comment]
@jricke 
Are you using V2 stack both on client and service side. ?
Here are the steps to do it correctly
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-platform#actor-using-remoting-v2-stack

Could you share the full stack trace for this error?

**Comment by jricke** [comment]
@suchiagicha 
I did not see the documentation for actors using the new V2 remoting. The documentation i was using is at https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/service-fabric/service-fabric-reliable-services-communication-remoting.md and it contains nothing about actors.

I'll try the attributes listed in the actor documentation and post a stack trace if it doesn't work.

Thanks,
Jason

**Comment by suchiagicha** [comment]
@jricke 

Did it worked for you. if yes, could we close  this issue?

**Comment by jricke** [comment]
Sorry. I got busy with other things. I will give it a try tomorrow.

**Comment by jricke** [comment]
I'm going to need to try again later.
Thank you for the link to the actors.

**Comment by pksorensen** [comment]
I tried this now, but something did not work after using v2.

```
The exception System.Runtime.Serialization.SerializationException was unhandled on the service and could not be serialized for transferring to the client.
Detailed Remote Exception Information: System.Runtime.Serialization.SerializationException: Type 'System.Collections.Generic.Dictionary`2[[Microsoft.ServiceFabric.Actors.ActorId, Microsoft.ServiceFabric.Actors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null],[System.DateTimeOffset, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' with data contract name 'ArrayOfKeyValueOfActorIdDateTimeOffsetOFdjZCwN:http://schemas.microsoft.com/2003/10/Serialization/Arrays' is not expected. Add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, Boolean verifyKnownType, RuntimeTypeHandle declaredTypeHandle, Type declaredType)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType(XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle objectTypeHandle, Type objectType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, Type declaredType)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize(XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerializeReference(XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle)
   at WritemsgResponseToXml(XmlWriterDelegator , Object , XmlObjectSerializerWriteContext , ClassDataContract )
   at System.Runtime.Serialization.ClassDataContract.WriteXmlValue(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)
   at Microsoft.ServiceFabric.Services.Remoting.V2.ServiceRemotingDataContractSerializationProvider.ServiceRemotingResponseMessageBodySerializer.Serialize(IServiceRemotingResponseMessageBody serviceRemotingResponseMessageBody)
   at Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Runtime.FabricTransportMessageHandler.CreateFabricTransportMessage(IServiceRemotingResponseMessage retval, Int32 interfaceId, Stopwatch stopwatch)
   at Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Runtime.FabricTransportMessageHandler.<RequestResponseAsync>d__7.MoveNext()
```

**Comment by pksorensen** [comment]
and 

```
The exception System.Runtime.Serialization.SerializationException was unhandled on the service and could not be serialized for transferring to the client.
Detailed Remote Exception Information: System.Runtime.Serialization.SerializationException: Element 'http://schemas.microsoft.com/2003/10/Serialization/:anyType' contains data of the 'urn:actors:ActorHeader' data contract. The deserializer has no knowledge of any type that maps to this contract. Add the type corresponding to 'ActorHeader' to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding it to the list of known types passed to DataContractSerializer.
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   at Microsoft.ServiceFabric.Services.Remoting.V2.ServiceRemotingMessageHeaderSerializer.DeserializeRequestHeaders(IMessageHeader messageHeader)
   at Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Runtime.FabricTransportMessageHandler.CreateRemotingRequestMessage(FabricTransportMessage fabricTransportMessage, Stopwatch stopwatch)
   at Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Runtime.FabricTransportMessageHandler.<RequestResponseAsync>d__7.MoveNext()
```

**Comment by VipulM-MSFT** [comment]
Can you provide your interface? @amanbha

**Comment by pksorensen** [comment]
I was able to get things working removing the attributes on the assembly and also updating my interface. Problem was that I used IDictionary<,> interface which do not work, changing to Dictionary<, > solved it.

**Comment by VipulM-MSFT** [comment]
We are aware of the interface breaks with V2 remoting, this resulted from the fact that method parameters are not wrapped now and data contract serializer behaves differently for the top level objects and wrapped data members for the collections. 

This issue is not blocking for you but some customers they cannot move from V1 to V2 as the previous interface cannot be remoted with V2. This is unfortunate; we are working on fixing this by introducing an option in the default serialization stack for wrapping the method parameters. The V1 stack will continued to be supported until we have resolved the migration issues.

**Comment by gmosuru** [comment]
calling parallel calls to service with httpclient is performing better than Remoting. Is there any work around for this .
