### ISSUE TITLE
Unable to connect to SF Cluster after certificate swap: FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched

### ISSUE THREAD

**Issue by rajaprad** [Azure/service-fabric-issues#517]
Am trying to swap the server certificate using the link [https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-security-update-certs-azure](url)

**Scenario:** 

1.Cluster has only primary Certificate, say CERT-PRI
2. Am trying to add secondary Certificate CERT-SEC and swap at the same time.
3. The deployment succeeds and the swap is visible from the portal.
4. At this point CERT-SEC is the primary and CERT-PRI is the secondary.
5. When i try connecting to the cluster using the primary cert am getting the below issue,
**[Continue reading below for step.6]**

WARNING: Failed to contact Naming Service. Attempting to contact Failover Manager Service...
WARNING: Failed to contact Failover Manager Service, Attempting to contact FMM...
VERBOSE: System.Fabric.FabricServerAuthenticationFailedException: FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched
---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C44
   at System.Fabric.Interop.NativeClient.IFabricQueryClient9.EndGetPartitionList2(IFabricAsyncOperationContext context)
   at System.Fabric.FabricClient.QueryClient.GetPartitionListAsyncEndWrapper(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean
expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
VERBOSE: System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   at System.Management.Automation.Cmdlet.ThrowTerminatingError(ErrorRecord errorRecord)
   at Microsoft.ServiceFabric.Powershell.CommonCmdletBase.TestClusterConnection(IClusterConnection clusterConnection, Boolean
testNetwork)
   at Microsoft.ServiceFabric.Powershell.ConnectCluster.ProcessRecord()
VERBOSE: System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   at System.Management.Automation.Cmdlet.ThrowTerminatingError(ErrorRecord errorRecord)
   at Microsoft.ServiceFabric.Powershell.ConnectCluster.ProcessRecord()
10/8/2017 11:17:13 PM: Exception while Provisioning/Upgrading SF Cluster
10/8/2017 11:17:13 PM:FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched

6. At this point am able to connect using the secondary certificate - CERT-PRI
7. When i attempt another swap, am able to connect to the next primary certificate - CERT-PRI

Update: Am unable to connect with the certificate which was swapped manually from the portal as well

**Comment by vaishnavk** [comment]
@rajaprad : The certificate with the farthest expiry date will be picked as the server certificate and presented to the client. Typically you should be set both the primary and secondary certificate thumbprints in the client allowed list since during adding/removing certs, depending on the node you connect to either one of the certs could be presented.

**Comment by rajaprad** [comment]
@vaishnavk, thanks and i was able to make this condition false by setting UseSecondaryIfNewer to false in cluster settings. I always want one certificate to be used for connection and frequently change the certificates for security purposes

**Comment by ottarhenanger** [comment]
@rajaprad, I'm having a similar problem but unable to figure out how to configure UseSecondaryIfNewer flag. Would it be possible for you to indicate where this configuration value can be modified?

**Comment by vaishnavk** [comment]
@ottarhenanger You specify it through FabricSettings in the cluster resource.
