### ISSUE TITLE
FabricDCA Fails to create container in blob storage, Exception occured while creating an object of type FabricDCA.AzureBlobEtwCsvUploader

### ISSUE THREAD

**Issue by kensykora** [Azure/service-fabric-issues#519]
As of the last few days I've started running into an issue when creating new service fabric cluster deployments to Azure. The nodes when they start up report unhealthy due to the fact that they cannot send logs to Azure storage. I'm fairly certain as early as last week I was not encountering this issue.

Service Fabric Version: `6.0.211.9494`

Please let me know if this is an inappropriate place for this, or if I should work with Azure support to remedy this instead.

Here is the unhealthy evaluation of the node message:

```
	Error event: SourceId='FabricDCA', Property='DataCollectionAgent'.
Exception occured while creating an object of type FabricDCA.AzureBlobEtwCsvUploader (assembly AzureFileUploader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) for creating consumer AzureBlobServiceFabricEtw.
Exception occured while creating an object of type FabricDCA.AzureTableQueryableEventUploader (assembly AzureTableUploader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) for creating consumer AzureTableServiceFabricEtwQueryable.
```

When i remote into the VM and go to the event viewer, I can find more detailed logs that seem to indicate it's a pretty deep exeception that's being thrown. I'm not confident if it's related to the data I'm configuring or not -- I've validated that the values I'm passing it are correct, so I don't think that is it.

The error messages indicate it can't convert base64 string to a byte array, but I'm unclear what the source of the data it's trying to convert is. I've checked the D:\SvcFab\clusterManifest.xml and D:\SvcFab\FabricHostSettings.xml -- both have proper StoreConnectionString parameters:

```
<Parameter Name="StoreConnectionString" Value="xstore:BlobEndpoint=https://skmskstglog.blob.core.windows.net/;TableEndpoint=https://skmskstglog.table.core.windows.net/;AccountName=skmskstglog;ProtectedAccountKeyName=StorageAccountKey1"/>
```

The protected settings for my VMSS have the StorageAccountKey1 set and as far as I can tell it's populated just fine (I put the same value into my ARM template output to verify the key is correct).

I'm not sure how to keep troubleshooting this, so hopefully you can help me figure out what's going on.

Event Viewer Logs from Application and Services Logs -> Microsoft-Service Fabric -> Admin:

These events all happen within 3 seconds of each other

## 1st Error:

```
Error creating container fabriclogs-cc636ce4-d115-41b4-bfd1-42c3fb0d00f2, account skmskstglog.
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64CharArray(Char[] inArray, Int32 offset, Int32 length)
   at System.Fabric.Dca.Utility.SecureStringToByteArray(SecureString secureString)
   at FabricDCA.AzureUtility.GetCloudStorageAccount(StorageConnection storageConnection, CloudStorageAccount& storageAccount)
   at FabricDCA.AzureFileUploader.CreateContainer(Object context)
   at System.Fabric.Dca.Utility.PerformWithRetries[T](Action`1 worker, T context, RetriableOperationExceptionHandler exceptionHandler, Int32 initialRetryIntervalMs, Int32 maxRetryCount, Int32 maxRetryIntervalMs)
   at FabricDCA.AzureFileUploader..ctor(ExtensionsEvents traceSource, String logSourceId, String folderName, String destinationPath, String workFolder, StorageConnection storageConnection, String containerName, TimeSpan uploadIntervalMinutes, TimeSpan fileSyncIntervalInMinutes, TimeSpan blobDeletionAgeMinutes, String fabricNodeInstanceName, String deploymentId)
```

## 2nd Error:

```
Exception occured while creating an object of type FabricDCA.AzureBlobEtwCsvUploader (assembly AzureFileUploader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) for creating consumer AzureBlobServiceFabricEtw. Exception information: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: AzureFileUploader could not be constructed. ---> System.InvalidOperationException: Error creating container fabriclogs-cc636ce4-d115-41b4-bfd1-42c3fb0d00f2, account skmskstglog. ---> System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64CharArray(Char[] inArray, Int32 offset, Int32 length)
   at System.Fabric.Dca.Utility.SecureStringToByteArray(SecureString secureString)
   at FabricDCA.AzureUtility.GetCloudStorageAccount(StorageConnection storageConnection, CloudStorageAccount& storageAccount)
   at FabricDCA.AzureFileUploader.CreateContainer(Object context)
   at System.Fabric.Dca.Utility.PerformWithRetries[T](Action`1 worker, T context, RetriableOperationExceptionHandler exceptionHandler, Int32 initialRetryIntervalMs, Int32 maxRetryCount, Int32 maxRetryIntervalMs)
   at FabricDCA.AzureFileUploader..ctor(ExtensionsEvents traceSource, String logSourceId, String folderName, String destinationPath, String workFolder, StorageConnection storageConnection, String containerName, TimeSpan uploadIntervalMinutes, TimeSpan fileSyncIntervalInMinutes, TimeSpan blobDeletionAgeMinutes, String fabricNodeInstanceName, String deploymentId)
   --- End of inner exception stack trace ---
   at FabricDCA.AzureFileUploader..ctor(ExtensionsEvents traceSource, String logSourceId, String folderName, String destinationPath, String workFolder, StorageConnection storageConnection, String containerName, TimeSpan uploadIntervalMinutes, TimeSpan fileSyncIntervalInMinutes, TimeSpan blobDeletionAgeMinutes, String fabricNodeInstanceName, String deploymentId)
   at FabricDCA.EtwCsvUploadWorker..ctor(EtwCsvUploadWorkerParameters initParam)
   --- End of inner exception stack trace ---
   at FabricDCA.EtwCsvUploadWorker..ctor(EtwCsvUploadWorkerParameters initParam)
   at FabricDCA.AzureBlobEtwCsvUploader..ctor(ConsumerInitializationParameters initParam)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at FabricDCA.ConsumerFactory.CreateConsumer(String consumerInstance, ConsumerInitializationParameters initParam, String moduleName, String typeName).
```

3rd Error:

```
Due to an error in table creation ETW traces will not be uploaded to Azure table storage.
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64CharArray(Char[] inArray, Int32 offset, Int32 length)
   at System.Fabric.Dca.Utility.SecureStringToByteArray(SecureString secureString)
   at FabricDCA.AzureUtility.GetCloudStorageAccount(StorageConnection storageConnection, CloudStorageAccount& storageAccount)
   at FabricDCA.AzureTableQueryableEventUploader.CreateTables()
   at FabricDCA.AzureTableQueryableEventUploader..ctor(ConsumerInitializationParameters initParam)
```

4th Error:
```
Exception occured while creating an object of type FabricDCA.AzureTableQueryableEventUploader (assembly AzureTableUploader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) for creating consumer AzureTableServiceFabricEtwQueryable. Exception information: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Due to an error in table creation ETW traces will not be uploaded to Azure table storage. ---> System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64CharArray(Char[] inArray, Int32 offset, Int32 length)
   at System.Fabric.Dca.Utility.SecureStringToByteArray(SecureString secureString)
   at FabricDCA.AzureUtility.GetCloudStorageAccount(StorageConnection storageConnection, CloudStorageAccount& storageAccount)
   at FabricDCA.AzureTableQueryableEventUploader.CreateTables()
   at FabricDCA.AzureTableQueryableEventUploader..ctor(ConsumerInitializationParameters initParam)
   --- End of inner exception stack trace ---
   at FabricDCA.AzureTableQueryableEventUploader..ctor(ConsumerInitializationParameters initParam)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at FabricDCA.ConsumerFactory.CreateConsumer(String consumerInstance, ConsumerInitializationParameters initParam, String moduleName, String typeName).
```

5th Error:
```
Kernel crash upload is configured but failed to get kernel crash dump folder.
```

6th Error:
```
Error creating container fabriccrashdumps-cc636ce4-d115-41b4-bfd1-42c3fb0d00f2, account skmskstglog.
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64CharArray(Char[] inArray, Int32 offset, Int32 length)
   at System.Fabric.Dca.Utility.SecureStringToByteArray(SecureString secureString)
   at FabricDCA.AzureUtility.GetCloudStorageAccount(StorageConnection storageConnection, CloudStorageAccount& storageAccount)
   at FabricDCA.AzureFileUploader.CreateContainer(Object context)
   at System.Fabric.Dca.Utility.PerformWithRetries[T](Action`1 worker, T context, RetriableOperationExceptionHandler exceptionHandler, Int32 initialRetryIntervalMs, Int32 maxRetryCount, Int32 maxRetryIntervalMs)
   at FabricDCA.AzureFileUploader..ctor(ExtensionsEvents traceSource, String logSourceId, String folderName, String destinationPath, String workFolder, StorageConnection storageConnection, String containerName, TimeSpan uploadIntervalMinutes, TimeSpan fileSyncIntervalInMinutes, TimeSpan blobDeletionAgeMinutes, String fabricNodeInstanceName, String deploymentId)
```

7th Error:
```
Failed to configure upload to Azure blob.  Storage account: skmskstglog, container: fabriccrashdumps-cc636ce4-d115-41b4-bfd1-42c3fb0d00f2, Local folder path: D:\SvcFab\Log\CrashDumps.
```

8th Error:
```
Error creating container fabriccounters-cc636ce4-d115-41b4-bfd1-42c3fb0d00f2, account skmskstglog.
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64CharArray(Char[] inArray, Int32 offset, Int32 length)
   at System.Fabric.Dca.Utility.SecureStringToByteArray(SecureString secureString)
   at FabricDCA.AzureUtility.GetCloudStorageAccount(StorageConnection storageConnection, CloudStorageAccount& storageAccount)
   at FabricDCA.AzureFileUploader.CreateContainer(Object context)
   at System.Fabric.Dca.Utility.PerformWithRetries[T](Action`1 worker, T context, RetriableOperationExceptionHandler exceptionHandler, Int32 initialRetryIntervalMs, Int32 maxRetryCount, Int32 maxRetryIntervalMs)
   at FabricDCA.AzureFileUploader..ctor(ExtensionsEvents traceSource, String logSourceId, String folderName, String destinationPath, String workFolder, StorageConnection storageConnection, String containerName, TimeSpan uploadIntervalMinutes, TimeSpan fileSyncIntervalInMinutes, TimeSpan blobDeletionAgeMinutes, String fabricNodeInstanceName, String deploymentId)
```

9th Error:
```
Failed to configure upload to Azure blob.  Storage account: skmskstglog, container: fabriccounters-cc636ce4-d115-41b4-bfd1-42c3fb0d00f2, Local folder path: D:\SvcFab\Log\PerformanceCounters_ServiceFabricPerfCounter.
```

**Comment by kensykora** [comment]
Hey guys,

Any idea on this? I think I am going to have to disable diagnostics which is really unfortunate. Should I open an Azure support ticket? How can I troubleshoot further (e.g., can I try to somehow get the SecureString that it's using which is causing the error to investigate the data itself?)

**Comment by mkosieradzki** [comment]
I have started to receive similar error after changing couple of things, including: OS image to Windows 2016 Server Core smalldisk, and storage definitions from 2015-06-15 api version to 2017-06-01. I will try to isolate the error tomorrow.

**Comment by mattrowmsft** [comment]
I think @mhatreabhay and I should be able to figure this out. I'll chat with him tomorrow and update thread.

**Comment by mkosieradzki** [comment]
I have managed to fix my issue by: changing back API version to 2015-06-15 in ARM, deleting logs and diag storage accounts, rerunning ARM template, restarting all nodes one by one in service fabric explorer. But it could have been any other issue.

**Comment by mkosieradzki** [comment]
I am afraid I was wrong. The problem is back :-(.

**Comment by masnider** [comment]
@mkosieradzki thanks for letting us know! Glad you got it sorted out.
