### ISSUE TITLE
Node not activating

### ISSUE THREAD

**Issue by jricke** [Azure/service-fabric-issues#523]
Getting the following errors and warnings in Windows Event Log. Not sure if these are why the node is not activating.
-----------------
Please contact SFRP team, Error: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.<PeriodicPollingStateMachine>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.<RunAsync>d__80.MoveNext() 
---------------
IOException writing to heartbeat file: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Packages\Plugins\Microsoft.Azure.ServiceFabric.ServiceFabricNode\1.0.0.36\Status\HeartBeat.Json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.UpdateHeartbeatFile(HandlerHeartbeat heartbeat)
--------------
Unhandled exception occurred:System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.<RunAsync>d__80.MoveNext()
-------------
C:\Packages\Plugins\Microsoft.Azure.ServiceFabric.ServiceFabricNode\1.0.0.37\UpgradeService\VERSION.txt doesnot exits
--------------
Error reading HandlerEnvironment from C:\Packages\Plugins\Microsoft.Azure.ServiceFabric.ServiceFabricNode\1.0.0.36\UpgradeService\..\HandlerEnvironment.json (Retry=1/10): System.IO.IOException: The process cannot access the file 'C:\Packages\Plugins\Microsoft.Azure.ServiceFabric.ServiceFabricNode\1.0.0.36\HandlerEnvironment.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Microsoft.Azure.ServiceFabric.Extension.Core.Models.HandlerEnvironmentFile.Parse(String fileName, Int32 maxRetry)

**Comment by mhatreabhay** [comment]
This is transient exception while accessing handler environment file. please ignore this error. It will not block cluster deployment. Please let me  know if you are seeing cluster deployment is stuck.
