### ISSUE TITLE
Service Fabric - Error occurred in request., ConnectionError: HTTPConnectionPool(host='ipaddress', port=port): Max retries exceeded with url:

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#622]
Hello Team,

Whenever i try to deploy apps to service fabric cluster using below command.
i am seeing below exception.

Command - sfctl cluster select --endpoint http://ipaddress:port
Error - 
Error occurred in request., ConnectionError: HTTPConnectionPool(host='ipaddrses', port=19000): Max retries exceeded
with url: / (Caused by ProtocolError('Connection aborted.', BadStatusLine('\x99\x00\x00\x00\x00\x00G\x00\x00\x00\x00\x00
\x03\x80 \x00\x00\x1f\x00\x00\x00\x00\x01\x00\x00\x1f\x0cd\xbf!$*\xab\xb4G\x8e\x19v\x88]\xf40\xc6\x08\x87j/?\x01\x80\x0e
\x00\x00\r\x00\x00\x00\x00\x01\x00\x00\x1f\t\x01/?\t\x80\r\x00\x00\x0c\x00\x00\x00\x00\x01\x00\x00\x1fB/?\x00E\x00\x00\x
00\x00\x00\x00\x00\x1f\x8d\x131\x000\x00.\x002\x005\x003\x00.\x001\x008\x006\x00.\x001\x001\x00:\x001\x009\x000\x000\x00
0\x00J\x0c\x03\xe7j\x1d\xbai\x89H\xa4l\xb5C\xbe\xcai\xc7/?',)))
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\knack\cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\python27\lib\site-packages\knack\invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "c:\python27\lib\site-packages\knack\commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "c:\python27\lib\site-packages\knack\commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "c:\python27\lib\site-packages\sfctl\custom_cluster.py", line 94, in select
    rest_client.send(rest_client.get('/')).raise_for_status()
  File "c:\python27\lib\site-packages\msrest\service_client.py", line 220, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "c:\python27\lib\site-packages\msrest\exceptions.py", line 48, in raise_with_traceback
    raise error
ClientRequestError: Error occurred in request., ConnectionError: HTTPConnectionPool(host='ipaddrses', port=19000): M
ax retries exceeded with url: / (Caused by ProtocolError('Connection aborted.', BadStatusLine('\x99\x00\x00\x00\x00\x00G
\x00\x00\x00\x00\x00\x03\x80 \x00\x00\x1f\x00\x00\x00\x00\x01\x00\x00\x1f\x0cd\xbf!$*\xab\xb4G\x8e\x19v\x88]\xf40\xc6\x0
8\x87j/?\x01\x80\x0e\x00\x00\r\x00\x00\x00\x00\x01\x00\x00\x1f\t\x01/?\t\x80\r\x00\x00\x0c\x00\x00\x00\x00\x01\x00\x00\x
1fB/?\x00E\x00\x00\x00\x00\x00\x00\x00\x1f\x8d\x131\x000\x00.\x002\x005\x003\x00.\x001\x008\x006\x00.\x001\x001\x00:\x00
1\x009\x000\x000\x000\x00J\x0c\x03\xe7j\x1d\xbai\x89H\xa4l\xb5C\xbe\xcai\xc7/?',)))

In SF Explorer, i am seeing all nodes are in healthy state as well System services like naming service, clustermanagerservice. image store service etc.

when i run above command, i am seeing above error.
In SF Explorer i am seeing nodes are getting down.
i also saw this exception in eventviewer in box.

Faulting application name: FabricHost.exe, version: 5.7.198.9494, time stamp: 0x597913e1
Faulting module name: FabricHost.exe, version: 5.7.198.9494, time stamp: 0x597913e1
Exception code: 0xc0000602
Fault offset: 0x000000000003af68
Faulting process id: 0x15c8
Faulting application start time: 0x01d359ce58708519
Faulting application path: C:\Program Files\Microsoft Service Fabric\bin\FabricHost.exe
Faulting module path: C:\Program Files\Microsoft Service Fabric\bin\FabricHost.exe
Report Id: b2777a7a-c1f3-4014-bd6a-cf0084991764
Faulting package full name: 
Faulting package-relative application ID: 

After sometime, nodes are becoming healthy but when i try it again. i am seeing same exception.

Thanks,
naresh Khatri

**Comment by nareshkhatri81** [comment]
This is what i see in event viewer when i run above command.

The Service Fabric Host Service service terminated unexpectedly.  It has done this 3 time(s).  The following corrective action will be taken in 5000 milliseconds: Restart the service.

After that i tried with below command to remove and clear and then recreated the cluster but issue still persist.

I have removed the cluster by running .\RemoveServiceFabricCluster.ps1 -ClusterConfigFilePath .\ClusterConfig.Unsecure.DevCluster.json -Force

i have also ran .\CleanFabric.ps1

**Comment by nareshkhatri81** [comment]
Putting it all together.

(1) Service fabric explorer shows everything green. i can see most of system service running fine in nodes as well with below command

Get-Process fab*

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    325      40    34856      45740       1.30   5624   0 Fabric
    273      35    30716      40276       0.81   7420   0 Fabric
    141    3144   709428      97292       0.22   8376   0 FabricApplicationGateway
    594      45   104528     120592       6.84   7608   0 FabricDCA
    418      47    38536      62876       2.41   6664   0 FabricFAS
    176     300    12424      22912       0.31   5928   0 FabricGateway
    159     328    11052      20756       0.17   6292   0 FabricGateway
    304      17     5620      15708       0.27   6856   0 FabricHost
    430      50    81908     106496       3.09   4864   0 FabricUOS

(2) i ran sfctl cluster select --endpoint http://ipaddress:port

its showing errors as pasted above.
Error occurred in request., ConnectionError: HTTPConnectionPool(host='ipaddress', port=port): Max retries exceeded with url

(3) i went to node and looked into process as well in event viewer.
i can see below error in eventviewer 
The Service Fabric Host Service service terminated unexpectedly.  It has done this 5 time(s).  The following corrective action will be taken in 5000 milliseconds: Restart the service.
Get-Process fab*

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    275      35    30704      39352       0.89    176   0 Fabric
    322      40    34812      44856       1.20   7368   0 Fabric
    141    3143   709396      97268       0.20   9000   0 FabricApplicationGateway
    594      45   103484     120052       6.88   2380   0 FabricDCA
    407      47    38128      62524       2.50   3876   0 FabricFAS
    184     319    12524      22772       0.28   6400   0 FabricGateway
    165     328    11068      20752       0.17   7436   0 FabricGateway
    315      17     5660      15708       0.31   8188   0 FabricHost
    435      50    82012     106548       3.09    324   0 FabricUOS

All services are now having different pid that means all crashed somehow and recreated again.

Let me know if there is any other way to troubleshoot and find out whats wrong.

**Comment by xunlu** [comment]
Do you see any dump files?

**Comment by nareshkhatri81** [comment]
yes there are crash dumb for FabricHost.exe.10884.

**Comment by nareshkhatri81** [comment]
Do we have pdb, source files of fabrichost somewhere so i can debug issue ?

**Comment by xunlu** [comment]
Could you provide the dump to RajeetN?  We will debug on our side.

**Comment by RajeetN** [comment]
This is a failfast. Please share traces in addition to the dump.

**Comment by nareshkhatri81** [comment]
I dont think we will be able to share dump files or traces file. I can speak with my manager still.
Is there way for us to investigate issue ?

**Comment by nareshkhatri81** [comment]
@RajeetN  Let me know email address where i can share dump files with you.

**Comment by Rohit-Stackroute** [comment]
Hey I crashed into similar problem after trying to install my node.js application package after creating cluster. I am using **Ubuntu 16.04**.

So when I ran this command `./install.sh` I can see my installation to complete but after few seconds I got this error.

`Error occurred in request., RetryError: HTTPSConnectionPool(host='nodecluster.eastus.cloudapp.azure.com', port=19080): Max retries exceeded with url: /ApplicationTypes/$/Provision?api-version=6.2&timeout=60 (Caused by ResponseError('too many 504 error responses',))
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/lib/python2.7/dist-packages/sfctl/custom_app_type.py", line 116, in provision_application_type
    request, header_parameters, body_content_sorted)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/home/ubuntu/.local/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/msrest/universal_http/requests.py", line 333, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/msrest/universal_http/requests.py", line 145, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/msrest/exceptions.py", line 54, in raise_with_traceback
    raise error
ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='nodecluster.eastus.cloudapp.azure.com', port=19080): Max retries exceeded with url: /ApplicationTypes/$/Provision?api-version=6.2&timeout=60 (Caused by ResponseError('too many 504 error responses',))
Uninstalling App as installation failed... Please try installation again.`
