### ISSUE TITLE
TestConfiguration.ps1 TypeLoad Exception

### ISSUE THREAD

**Issue by groogiam** [Azure/service-fabric-issues#652]
I am running into an issue with the latest version of the standalone package (http://go.microsoft.com/fwlink/?LinkId=730690). 

When running the following command.

```
PS C:\Users\horvathg\Desktop\Microsoft.Azure.ServiceFabric.WindowsServer.6.0.232.9494> .\TestConfiguration.ps1 -ClusterConfigFilePath .\ClusterConfig.Windows.MultiMachine.json
Test Config failed with exception: System.TypeLoadException: Could not load type 'ExtensionsEventsInternal' from assembly 'System.Fabric, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.ServiceFabric.DeploymentManager.SFDeployerTrace.WriteInfo(String format, Object[] args)
   at Microsoft.ServiceFabric.DeploymentManager.SFDeployerTrace.UpdateFileLocation(String traceFolder)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.BpaAnalyzeClusterSetup(String clusterConfigPath, String oldClusterConfigPath, String fabricPackagePath)
   at Microsoft.ServiceFabric.Powershell.ClusterCmdletBase.TestConfig(String clusterConfigPath, String oldClusterConfigPath, String fabricPackagePath)
   at System.Management.Automation.CommandProcessor.ProcessRecord()
PS C:\Users\horvathg\Desktop\Microsoft.Azure.ServiceFabric.WindowsServer.6.0.232.9494>
```

**Comment by rufio620** [comment]
Is anyone going to bother looking at this? I get type exceptions when loading any of the scripts in the referenced package? I have attempted to use with both windows 10 (which has the sdk installed) and with a fresh instance of server 2012 r2.  Am I perhaps missing a dependency that is not documented on the https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server page.

**Comment by rufio620** [comment]
Below is the error I get when attempting to run on a Server 2012 R2 box. The FabricCommon.dll is in the downloaded DeploymentComponents directory so I'm not quite sure what is going on.

`.\TestConfiguration.ps1 -ClusterConfigFilePath .\ClusterConfig.Unsecure.DevCluster.json`

```
Test Config failed with exception: System.Management.Automation.CommandNotFoundException: Argument 'Test-ServiceFabricConfiguration' is not recognized as a cmdlet: Unable to load DLL 'FabricCommon.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) ---> System.DllNotFoundException: Unable to load DLL 'FabricCommon.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Fabric.Interop.Utility.RunInMTA[TResult](Func`1 func)
   at Microsoft.ServiceFabric.Powershell.CommonCmdletBase.Ensure_IgnoreUpdateFailures()
   at Microsoft.ServiceFabric.Powershell.CommonCmdletBase..ctor()
   at lambda_method(Closure )
   at System.Management.Automation.CommandProcessor.Init(CmdletInfo cmdletInformation)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

**Comment by mcleanl** [comment]
I encountered the same issue with the 6.0.232 version.  6.0.291 works fine so sticking with that until fixed.

**Comment by dkkapur** [comment]
I think this was taken care of. Please let me know if you are still facing this!
