### ISSUE TITLE
EncryptionUtility.EncryptText error: Value does not fall within the expected range

### ISSUE THREAD

**Issue by raldaba** [Azure/service-fabric-issues#663]
I'm running into an exception when trying to encrypt a large string. This particular one is of length 5735. I've validated my cert and current configuration with a string of a smaller length (1540).

The particular scenario for my code involves encrypting these kind of string tokens, and as much as I want to avoid receiving such a large string, I'm afraid I don't have control over that.

Let me know if there's a workaround or if you guys decide to tackle this one.

Thanks!

The exception is:

System.ArgumentException occurred
  HResult=0x80070057
  Message=Value does not fall within the expected range.
  Source=System.Fabric
  StackTrace:
  at System.Fabric.Interop.NativeCommon.FabricEncryptText(IntPtr text, IntPtr certThumbPrint, IntPtr certStoreName, FABRIC_X509_STORE_LOCATION certStoreLocation, IntPtr algorithmOid)
   at System.Fabric.Security.EncryptionUtility.EncryptText(String textToEncrypt, String thumbprint, String storeName, StoreLocation storeLocation, String algorithmOid)
   at System.Fabric.Security.EncryptionUtility.EncryptText(String textToEncrypt, String thumbprint, String storeName)

**Comment by oanapl** [comment]
The max allowed size is 4096 characters. There is no workaround this limit as of now.
@leikong , can we make this limit configurable or increase it?

We will also improve the error message to include more details.

**Comment by leikong** [comment]
Adding Vaishnav

**Comment by stevshan** [comment]
Changed to use TRY_COM_PARSE_PUBLIC_LONG_STRING instead whose length can be configured via DLL config of FabricCommon.dll.

**Comment by stevshan** [comment]
The default length is 1024 * 1024.
