### ISSUE TITLE
SF - TestConfiguration.ps1 fails with error ExtensionsEventsInternal not found.

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#681]
PS D:\SF\Microsoft.Azure.ServiceFabric.WindowsServer.6.0.232.9494> .\TestConfiguration.ps1

cmdlet TestConfiguration.ps1 at command pipeline position 1
Supply values for the following parameters:
ClusterConfigFilePath: RFClusterConfig.Unsecure.MultiMachine.json
Test Config failed with exception: System.TypeLoadException: Could not load type 'ExtensionsEventsInternal' from assembl
y 'System.Fabric, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.ServiceFabric.DeploymentManager.SFDeployerTrace.WriteInfo(String format, Object[] args)
   at Microsoft.ServiceFabric.DeploymentManager.SFDeployerTrace.UpdateFileLocation(String traceFolder)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.BpaAnalyzeClusterSetup(String clusterConfigPat
h, String oldClusterConfigPath, String fabricPackagePath)
   at Microsoft.ServiceFabric.Powershell.ClusterCmdletBase.TestConfig(String clusterConfigPath, String oldClusterConfigP
ath, String fabricPackagePath)
   at System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by vavane-ms** [comment]
I see the same problem when adding a node.

**Comment by maburlik** [comment]
This is the reply I sent to Valentina:

Looks like a case of a mixed installation on the machine. Do you have a dev cluster set up, or have the SDK installed on this machine? If so, does the version of the cluster/installation differ from the standalone package? If so, just make sure you are using the same version otherwise you will have assembly binding conflicts against the assemblies in GAC.

**Comment by maburlik** [comment]
Similar to https://github.com/Azure/service-fabric-issues/issues/781

Seems this has been resolved offline. If not, feel free to create another item so we can actively track this.
