### ISSUE TITLE
HttpSys UrlPrefix conflict with Skype

### ISSUE THREAD

**Issue by ConX-Ryan** [Azure/service-fabric-issues#707]
```
Microsoft.AspNetCore.Server.HttpSys.HttpSysException (0x80004005): The process cannot access the file because it is being used by another process
   at Microsoft.AspNetCore.Server.HttpSys.UrlGroup.RegisterPrefix(String uriPrefix, Int32 contextId)
   at Microsoft.AspNetCore.Server.HttpSys.UrlPrefixCollection.RegisterAllPrefixes(UrlGroup urlGroup)
   at Microsoft.AspNetCore.Server.HttpSys.HttpSysListener.Start()
```

Under local debug when using an `HttpSysCommunicationListener` or `WebListener` and when using a UrlPrefix setup by netsh commands in a setup bat file, the above error is generated.

Interestingly enough i have the same issue in an azure cluster but it cant be skype right? I have an adjacent webapp with exactly the same startup method using a different UrlPrefix that works perfectly, they have previously worked side by side using this method, and it isn't one blocking another. Any ideas on this would be greatly apperciated.

**Comment by ylbillyli** [comment]
Any update on this issues? We seems to be getting this exact error message today where service fabric just keep retrying listening on the url. We don't have Skype installed though.

**Comment by ConX-Ryan** [comment]
@ylbillyli another thing that is likely to cause this is IIS running locally if you have it. just stop IIS using inetmgr and check.
