### ISSUE TITLE
libFabricCommon.so missing?

### ISSUE THREAD

**Issue by EtienneBruines** [Azure/service-fabric-issues#76]
I've done some searching, and I'm not sure if this is the right place to put this error. 
# Steps to reproduce

Following [this walkthrough](https://azure.microsoft.com/en-us/documentation/articles/service-fabric-get-started-linux/), when executing `/opt/microsoft/sdk/servicefabric/common/clustersetup/devclustersetup.sh`, it results in the error below. 
# What I've tried

Google has no clue (searching for `libFabricCommon.so` yields exactly 0 matches). 

(I have no idea what's related, or what's causing this. I'm happy to post any requested related info)
# The error log

```
Deploying service fabric scale min cluster
FabricDataRoot = /home/sfuser/sfdevcluster/data
FabricBinRoot = /opt/microsoft/servicefabric/bin
ClusterManifest = /opt/microsoft/sdk/servicefabric/common/clustersetup/nonsecure/servicefabric-scalemin.xml
InfraManifest =
Setting environment for FabricDeployer to run
mkdir: cannot create directory ‘/etc/servicefabric’: File exists
Deleting all old content in FabricDataRoot
Running FabricDeployer on /opt/microsoft/sdk/servicefabric/common/clustersetup/nonsecure/servicefabric-scalemin.xml
Exception during interop trace writing: System.DllNotFoundException: Unable to load DLL 'libFabricCommon.so': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at McgInterop.libFabricCommon_so_PInvokes.WriteManagedTrace(IntPtr taskName, IntPtr eventName, IntPtr id, UInt16 level, IntPtr text)
   at McgInterop.libFabricCommon_so.WriteManagedTrace(IntPtr taskName, IntPtr eventName, IntPtr id, UInt16 level, IntPtr text)
   at System.Fabric.Interop.NativeCommon.WriteManagedTrace(IntPtr taskName, IntPtr eventName, IntPtr id, UInt16 level, IntPtr text)
   at System.Fabric.Common.Tracing.TraceViaNative.Write(String taskName, String eventName, String id, UInt16 level, String text)
FabricDeployer, FabricDeployer_InfoText, 58370, 4, Deployer called with /operation:Create /fabricBinRoot:/opt/microsoft/servicefabric/bin /fabricDataRoot:/home/sfuser/sfdevcluster/data /cm:/opt/microsoft/sdk/servicefabric/common/clustersetup/nonsecure/servicefabric-scalemin.xml
Exception during interop trace writing: System.DllNotFoundException: Unable to load DLL 'libFabricCommon.so': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at McgInterop.libFabricCommon_so_PInvokes.WriteManagedTrace(IntPtr taskName, IntPtr eventName, IntPtr id, UInt16 level, IntPtr text)
   at McgInterop.libFabricCommon_so.WriteManagedTrace(IntPtr taskName, IntPtr eventName, IntPtr id, UInt16 level, IntPtr text)
   at System.Fabric.Interop.NativeCommon.WriteManagedTrace(IntPtr taskName, IntPtr eventName, IntPtr id, UInt16 level, IntPtr text)
   at System.Fabric.Common.Tracing.TraceViaNative.Write(String taskName, String eventName, String id, UInt16 level, String text)
FabricDeployer, FabricDeployer_ErrorText, 58368, 2, System.DllNotFoundException: Unable to load DLL 'libFabricCommon.so': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at McgInterop.libFabricCommon_so_PInvokes.FabricCreateFabricDeploymentSpecification(Guid* riid, Vtbl*** __value__retval)
   at McgInterop.libFabricCommon_so.FabricCreateFabricDeploymentSpecification(Guid& riid)
   at System.Fabric.Common.ImageModel.NativeImageModel.FabricCreateFabricDeploymentSpecification(Guid& riid)
   at System.Fabric.Common.ImageModel.FabricDeploymentSpecification.CreateHelper()
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   at System.Fabric.Common.ImageModel.FabricDeploymentSpecification.Create()
   at System.Fabric.FabricDeployer.DeploymentParameters..ctor(Boolean setBinRoot)
   at System.Fabric.FabricDeployer.DeploymentParameters..ctor()
   at System.Fabric.FabricDeployer.CommandLineInfo.Parse(String[] args)
   at System.Fabric.FabricDeployer.Program.Main(String[] args)
System.DllNotFoundException: Unable to load DLL 'libFabricCommon.so': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at McgInterop.libFabricCommon_so_PInvokes.FabricCreateFabricDeploymentSpecification(Guid* riid, Vtbl*** __value__retval)
   at McgInterop.libFabricCommon_so.FabricCreateFabricDeploymentSpecification(Guid& riid)
   at System.Fabric.Common.ImageModel.NativeImageModel.FabricCreateFabricDeploymentSpecification(Guid& riid)
   at System.Fabric.Common.ImageModel.FabricDeploymentSpecification.CreateHelper()
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   at System.Fabric.Common.ImageModel.FabricDeploymentSpecification.Create()
   at System.Fabric.FabricDeployer.DeploymentParameters..ctor(Boolean setBinRoot)
   at System.Fabric.FabricDeployer.DeploymentParameters..ctor()
   at System.Fabric.FabricDeployer.CommandLineInfo.Parse(String[] args)
   at System.Fabric.FabricDeployer.Program.Main(String[] args)
Error: FabricDeployer.exe failed
Error: Deploying cluster manifest failed. Check output for details
```
# Something maybe related?

```
➜ grep -r "libFabricCommon.so" /opt/microsoft 

Binary file /opt/microsoft/servicefabric/bin/Fabric/DCA.Code/System.Fabric.McgInterop.dll matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/DCA.Code/System.Fabric.McgInterop.pdb matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/DCA.Code/System.Fabric.dll matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/__FabricSystem_App4294967295/US.Code.Current/System.Fabric.McgInterop.dll matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/__FabricSystem_App4294967295/US.Code.Current/System.Fabric.McgInterop.pdb matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/__FabricSystem_App4294967295/US.Code.Current/System.Fabric.dll matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/__FabricSystem_App4294967295/FileStoreService.Code.Current/FileStoreService.exe matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/__FabricSystem_App4294967295/IS.Code.Current/System.Fabric.McgInterop.dll matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/__FabricSystem_App4294967295/IS.Code.Current/System.Fabric.McgInterop.pdb matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/__FabricSystem_App4294967295/IS.Code.Current/System.Fabric.dll matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/FabricTypeHost.exe matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/FabricGateway.exe matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/Fabric matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/libFabricCommon.so matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/System.Fabric.McgInterop.dll matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/libFabricImageStore.so matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/System.Fabric.McgInterop.pdb matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/libFabricRuntime.so matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/System.Fabric.dll matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/libFabricClient.so matches
Binary file /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/libFabricServiceCommunication.so matches
Binary file /opt/microsoft/servicefabric/bin/FabricHost matches
```

**Comment by mani-ramaswamy** [comment]
That is one of the libraries we ship and looks like something might have gone wrong in the install. Do you mind reinstalling the runtime & the SDK?

**Comment by mani-ramaswamy** [comment]
Also try doing a sudo apt-get -f install (to ensure all dependencies are being pulled in) before trying a reinstall.

**Comment by AndreaEruc** [comment]
Hi in my ServiceFabric Project I heave this error:
Exception in thread "main" java.lang.UnsatisfiedLinkError: /opt/microsoft/sdk/servicefabric/java/packages/lib/libjFabricRuntime.so: libFabricRuntime.so: cannot open shared object file: No such file or directory

Could you help me?

**Comment by AndreaEruc** [comment]
the exception is:

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jFabricRuntime in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at system.fabric.FabricRuntime.<clinit>(FabricRuntime.java:498)
	at microsoft.servicefabric.fabrictransport.FabricServiceConfig.tryGetConfigPackageObject(FabricServiceConfig.java:65)
	at microsoft.servicefabric.fabrictransport.FabricServiceConfig.getConfig(FabricServiceConfig.java:43)
	at microsoft.servicefabric.fabrictransport.FabricServiceConfigSection.initialize(FabricServiceConfigSection.java:28)
	at microsoft.servicefabric.fabrictransport.FabricTransportSettings.initializeSettingsFromConfig(FabricTransportSettings.java:505)
	at microsoft.servicefabric.fabrictransport.FabricTransportSettings.loadFrom(FabricTransportSettings.java:265)
	at microsoft.servicefabric.fabrictransport.FabricTransportSettings.tryLoadFrom(FabricTransportSettings.java:403)
	at microsoft.servicefabric.fabrictransport.FabricTransportSettings.getDefault(FabricTransportSettings.java:491)
	at microsoft.servicefabric.services.remoting.fabrictransport.FabricTransportRemotingSettings.getDefault(FabricTransportRemotingSettings.java:164)
	at microsoft.servicefabric.services.remoting.fabrictransport.FabricTransportRemotingSettings.getDefault(FabricTransportRemotingSettings.java:150)
	at microsoft.servicefabric.actors.FabricTransportActorRemotingProvider.createServiceRemotingClientFactory(FabricTransportActorRemotingProvider.java:33)
	at microsoft.servicefabric.actors.FabricActorProxyFactory.createServiceRemotingClientFactory(FabricActorProxyFactory.java:321)
	at microsoft.servicefabric.actors.FabricActorProxyFactory.getOrCreateServiceRemotingClientFactory(FabricActorProxyFactory.java:310)
	at microsoft.servicefabric.actors.FabricActorProxyFactory.createActorProxy(FabricActorProxyFactory.java:92)
	at microsoft.servicefabric.actors.FabricActorProxyFactory.createActorProxy(FabricActorProxyFactory.java:165)
	at microsoft.servicefabric.actors.ActorProxyBase.create(ActorProxyBase.java:197)
	at microsoft.servicefabric.actors.ActorProxyBase.create(ActorProxyBase.java:149)
	at microsoft.servicefabric.actors.ActorProxyBase.create(ActorProxyBase.java:107)
	at Main.main(Main.java:30)


Thanks best regards

**Comment by Jose-CF** [comment]
Same issue here.

**Comment by raunakpandya** [comment]
Are you seeing the issue while running your Java app? Which version of SDK and runtime are you using?

**Comment by Jose-CF** [comment]
Here using C#.
SDK:
```
ii  servicefabric                                      5.6.28.6                                   amd64        Service Fabric
ii  servicefabricsdkcommon                             0.9.0.0                                    amd64        Service Fabric SDK Common
ii  servicefabricsdkcsharp                             0.9.0.0                                    amd64        Service Fabric SDK Csharp
```

Runtime, tried everything available between 1.x and 2.0.0 - preview2

**Comment by raunakpandya** [comment]
I see you have opened a separate issue for tracking this.. Let's discuss on that one further as this one is for C# and I don't think this is the same issue.

**Comment by Jose-CF** [comment]
I agree. In case someone is experiencing this in C#:  #397
