### ISSUE TITLE
Reliable dictionary lost?

### ISSUE THREAD

**Issue by SndrSchnklshk** [Azure/service-fabric-issues#761]
Hi all,

I'm having troubles getting my reliable dictionary working correctly. The reliable dictionary I'm using is stored fine but once in a few hours it loses all information. It just drops it without any error or trace message! The dictionary just constain a few 'reliable-records' but they contain >40K plain list items each. 

For example: `relDic["val1"] = new List<MyRecord>();`

New data comes in approx. every second. These list items (MyRecord, value/datetime) need to be stored for max 12 hours. After that I dont need them any more and drop them by not adding them again to the list (see procedure below).

Currently I'm running 1 app, 5 nodes, 2 replicas (MinReplicaSize) on 1 partition. Every 5 minutes the app writes a trace message with the number of items in the dictionary (and the count of the value lists). These values are also reported via custom metrics (TrackMetric). Besides that it keeps track of role change, dataloss etc events.

Attached an image of my Azure dashboard chart. You will see a weird ZigZag pattern of the sizes of the dictionary. I expect to see a sort of straight line here:
![zigzag](https://user-images.githubusercontent.com/35453771/34941176-ece12626-f9f2-11e7-934c-70a188d4bae6.png)

The procedure I use to save my data is:
(1) Every time there new items need to be added: inside a statemanager transaction it tries to (2) get (TryGetValueAsync) the current items (10 re-tries), (3) create a new list (as value), clone the previous items and new ones and (4) save (SetAsync) the reliable dictionary. TimeoutException are catched with a retry of 10 times.

A nice idea was that my app saves an empty list once in a while; but why are are all all my keys in the dictionary gone at the same time. Besides that the pattern looks very repetitive...

- Do you have any idea what is going on?
- Is this a known issue? ... did I just touch the limits of it?
- Is there an event that tells me when there are issues in the StateManager or reliable dictionary?
- Are reliable collections the right way the to go for me? Should I move the another storage method? 

Thanks a lot!

**Comment by masnider** [comment]
Hi @SndrSchnklshk - thanks for reporting, let's try to figure out what's going on.

Can you share all the code where you interact with the dictionaries and the state manager? You shouldn't be hitting any limits and hitting any limits shouldn't cause the behavior that you're seeing.

**Comment by SndrSchnklshk** [comment]
Hi @masnider, Thanks for your reply. Hereby the code I'm running. Just to be clear the code works fine and generates no errors or have any issues besides that the dictionary is empty once in a while.

The following code is used where the measurement data comes in (~every second). The code is a bit messy because of the added some retry loops and delays.

The `measurementType` is the key of the dictionary and exits at the moment of 3 different strings (e.g A001). The variable `relDic` is of type `IReliableDictionary<string, List<MyRecord>>`
Everytime a new list is created, old clones and new items are added and the list is updated.

```
[...]
bool retry = false;
            int retryCounter = 0;
            do
            {
                try
                {
                    if (retryCounter > 10)
                        throw new Exception("Unable to store data, retry failed 10 times in a row");
var relDic= await this.StateManager.GetOrAddAsync<IReliableDictionary<string, List<MyRecord>>>("measurementData");
                    using (var tx = this.StateManager.CreateTransaction())
                    {
                        ConditionalValue<List<MyRecord>> result = new ConditionalValue<List<MyRecord>>(false, null);
                        int getValueCounter = 0;
                        do
                        {
                            result = await relDic.TryGetValueAsync(tx, measurementType, LockMode.Update);
                            getValueCounter++;
                            if (!result.HasValue)
                                Thread.Sleep(500);
                        }
                        while (result.HasValue == false && getValueCounter < 10);

                        var newList = new List<MyRecord>();
                        var currentList = new List<MyRecord>();
                        if (result.HasValue)
                            currentList = result.Value;
                        if (currentList == null)
                            currentList = new List<MyRecord>();

                        long keepTicksAfter = DateTime.UtcNow.AddHours(-12).Ticks; //Keep maximum 12 hours 
                        if (currentList != null)
                        {
                            foreach (var item in currentList)
                            {
                                var clone = item.Clone(); //this clone copies all values of the object
                                if (clone.Ticks > keepTicksAfter)
                                    newList.Add(clone);
                            }
                        }
                        if (e.NewData!= null)
                        {
                            foreach (var newItem in e.NewData)
                            {
                                newList.Add(newItem.Clone());
                            }
                        }
                        currentList.Clear();
                        currentList = null; //change
                        if (newList != null)
                        {
                            await relDic.SetAsync(tx, measurementType, newList);
                            await tx.CommitAsync();
                        }
                    }
                }
                catch (TimeoutException)
                {
                    await Task.Delay(100);
                    retry = true;
                    retryCounter++;
                }
                catch (Exception ex)
                {
                    error(ex, "Unable to handle save event, {0}", ex.ToString());
                    retry = false;
                }
            } while (retry);
```

Every 5 minutes the app writes a some metric data and updates the `statusMessage` to a seperate database. See code below:

```
int totalCount = 0;
            using (var tx = this.StateManager.CreateTransaction())
            {
                var relDic = await this.StateManager.GetOrAddAsync<IReliableDictionary<string, List<MyRecord>>>("measurementData");
                foreach (var measurementType in configSettings.MeasurementTypes)
                {
                    if (await relDic.ContainsKeyAsync(tx, measurementType))
                    {
                        var data = await relDic.TryGetValueAsync(tx, measurementType);
                        int count = 0;
                        DateTime since = DateTime.MaxValue;
                        if (data.HasValue)
                        {
                            count = data.Value.Count();
                            var first = data.Value.FirstOrDefault();
                            if (first != null)
                                since = first.CreateDate;
                        }

                        statusMessage += $" > {count} {measurementType}-records cached since {since.ToString()}{Environment.NewLine}";
                        if (data.HasValue)
                            telemetry.TrackMetric(new Microsoft.ApplicationInsights.DataContracts.MetricTelemetry($"Cache {measurementType}", 1, count, 0, count, count) { });

                        totalCount += count;
                    }
                    else
                    {
                        statusMessage += $" > No cache for {measurementType}{Environment.NewLine}";
                    }
                }
            }
```

The statusMessage output looks something like this:
```
> 9377 A001-records cached since 1/17/2018 7:05:09 AM
> 8070 A002-records cached since 1/17/2018 7:05:10 AM
> 5589 A003-records cached since 1/17/2018 7:05:10 AM
```

For this purpose I've modified some names to make it a bit more readable without the context of my code. Thanks in advance.

**Comment by SndrSchnklshk** [comment]
Any suggestions so far? Thanks.

**Comment by preethasubbarayalu** [comment]
Hi @SndrSchnklshk,  Are you seeing keys and values missing from the dictionary or is it your list count(dictionary value) that you don't see as expected?

**Comment by SndrSchnklshk** [comment]
Hi @preethasubbarayalu,

Thanks for your message. I've tested your suggestion by adding a metric for the dictionary count. It seems that the keys in the dictionary stay there but the values are dropped from time to time.

Besides that I changed the time I keep my records to 2 hours to see if maybe the dictionary values are getting to large... but no effect. The data is lost at 8:41:38 AM. See chart below for an hour view.

![datalost_perhour](https://user-images.githubusercontent.com/35453771/35321596-905ee428-00e7-11e8-8e7b-d80bcc66a3b0.png)

This chart shows the items in the cache and the second the keys in the dictionary (12 hours).
![datalost](https://user-images.githubusercontent.com/35453771/35321122-814b4bee-00e6-11e8-8855-e3201890afe0.png)

According my log the roles were changed at 01:24:18 to a new Primary role. Can someone explain that peak, is that only during change?

And still my question; any idea why the data is lost?

Thanks.

**Comment by preethasubbarayalu** [comment]
Hi @SndrSchnklshk
When you say the values are dropped - are you seeing null or empty values? Are you using your custom serializer? Could you check your serialization/deserialization code to see if it is consistent?

Thanks
Preetha

**Comment by SndrSchnklshk** [comment]
Hi @preethasubbarayalu again, 

Yes, with dropped I mean the value becomes null or -in my case- I cannot get the value from the dictionary (TryGetValueAsync) anymore. 

This happens very randomly to me. See chart above.

Is there something wrong in the way I interact with the reliable dictionary? Should I change the way I do it?

**Comment by preethasubbarayalu** [comment]
Hi @SndrSchnklshk , Are you using custom serializers?

**Comment by SndrSchnklshk** [comment]
No, Im not using any custom serializers.
________________________________

**Comment by preethasubbarayalu** [comment]
Hi @SndrSchnklshk, Could you please share the code for your value object?

Thanks
Preetha

**Comment by SndrSchnklshk** [comment]
Hi @preethasubbarayalu, sorry for my delayed response; I was not around for a while. This is the code of my class:

```
[DataContract]
[DebuggerDisplay("Value = {Value}")]
public class MyRecord
{
	public long Id { get; set; }
	public System.DateTime CreateDate { get; set; }
	public long Ticks { get; set; }
	public double Value { get; set; }

	public MyRecord Clone()
	{
		return Copy(this);
	}

	public MyRecord Copy(MyRecord source)
	{
		if (source == null)
			return null;
		MyRecord copy = new MyRecord()
		{
			Value = source.Value,
			CreateDate = source.CreateDate,
			Id = source.Id,
			Ticks = source.Ticks
		};
		return copy;
	}
}
```

**Comment by zuhairp** [comment]
Hey @SndrSchnklshk, can you try adding [DataMember] attributes to the members of your value object and see if the problem still persists?

**Comment by SndrSchnklshk** [comment]
Hi @zuhairp, I've now added DataMembers and update the service. I'm afraid this wouldn't solve it... but let's wait for now.

I'm still busy investigating the issue because I really need to fix it now. When I cannot make it work this way I have to move to another solution... 
My save event is triggered from multiple threads. What about thread safety of the objects? What happens to the StateManager or transaction?

Thanks.

**Comment by SndrSchnklshk** [comment]
After I added the DataMember attributes I had suddenly (i expect it's related to the change in the dictionary) lots of issue to get the application running again. It kept saying "InQuorumLoss" and even after updates (force restarts, or version number changes) I couldn't start the guys. Why is that?!

This morning I deleted the application and removed the application type, republished and it runs smooth again.

**Comment by zuhairp** [comment]
Just to clarify, after re-creating the application, are you able to see your values correctly?

**Comment by SndrSchnklshk** [comment]
@zuhairp uh, no I just discoved that one node (out of the 5) is stuck on disabled. And the roles keep changing... so, I dont have a clear picture right now, but I will get back here :)

That looks like the I have the same issue as: https://github.com/Azure/service-fabric-issues/issues/436

**Comment by SndrSchnklshk** [comment]
I've contacted the support team and the PG is investigating my 'node-stays-disabled' issue. Once everything is back online I can see how my reliable dictionary runs.

**Comment by SndrSchnklshk** [comment]
Yes, the PG team fixed my 'node-stays-disabled' issue and my application and nodes run again!

@zuhairp: The dictionary is still there (for 4 hours) but it's still hard to say if the dictionary remains but the role keeps changing all the time!

The problem is that my roles keep swapping... from primary to secondary (approx every 15 minutes).
I checked the logs and I noticed an error -_which I haven't seen before_- in the eventvwr.

See stack trace below:

```
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: unexpected exception System.InvalidOperationException
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at System.Fabric.Store.TStore`5+<CheckpointAsync>d__280[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.Fabric.Store.TStore`5+<CheckpointAsync>d__280[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<CheckpointAsync>d__280<System.__Canon,System.__Canon,System.__Canon,System.__Canon,System.__Canon> ByRef)
   at System.Fabric.Store.TStore`5[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CheckpointAsync(System.Threading.CancellationToken)
   at System.Fabric.Store.TStore`5+<Microsoft-ServiceFabric-Replicator-IStateProvider2-PerformCheckpointAsync>d__245[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.Fabric.Store.TStore`5+<Microsoft-ServiceFabric-Replicator-IStateProvider2-PerformCheckpointAsync>d__245[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<Microsoft-ServiceFabric-Replicator-IStateProvider2-PerformCheckpointAsync>d__245<System.__Canon,System.__Canon,System.__Canon,System.__Canon,System.__Canon> ByRef)
   at System.Fabric.Store.TStore`5[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Microsoft.ServiceFabric.Replicator.IStateProvider2.PerformCheckpointAsync(System.Threading.CancellationToken)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager+<PerformCheckpointStateProvidersAsync>d__155.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.ServiceFabric.Replicator.DynamicStateManager+<PerformCheckpointStateProvidersAsync>d__155, Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<PerformCheckpointStateProvidersAsync>d__155 ByRef)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.PerformCheckpointStateProvidersAsync()
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager+<PerformCheckpointAsync>d__117.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.ServiceFabric.Replicator.DynamicStateManager+<PerformCheckpointAsync>d__117, Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<PerformCheckpointAsync>d__117 ByRef)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.PerformCheckpointAsync()
   at Microsoft.ServiceFabric.Replicator.CheckpointManager+<PerformStateProviderCheckpointAsync>d__64.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.ServiceFabric.Replicator.CheckpointManager+<PerformStateProviderCheckpointAsync>d__64, Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<PerformStateProviderCheckpointAsync>d__64 ByRef)
   at Microsoft.ServiceFabric.Replicator.CheckpointManager.PerformStateProviderCheckpointAsync(Microsoft.ServiceFabric.Replicator.BeginCheckpointLogRecord)
   at Microsoft.ServiceFabric.Replicator.CheckpointManager+<PerformCheckpoint>d__62.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.ServiceFabric.Replicator.CheckpointManager+<PerformCheckpoint>d__62, Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<PerformCheckpoint>d__62 ByRef)
   at Microsoft.ServiceFabric.Replicator.CheckpointManager.PerformCheckpoint(System.Exception)
   at Microsoft.ServiceFabric.Replicator.CheckpointManager+<<InitiateCheckpoint>b__59_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.ServiceFabric.Replicator.CheckpointManager+<<InitiateCheckpoint>b__59_0>d, Microsoft.ServiceFabric.Data.Impl, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<InitiateCheckpoint>b__59_0>d ByRef)
   at Microsoft.ServiceFabric.Replicator.CheckpointManager.<InitiateCheckpoint>b__59_0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

What about thread safety? In my case I receive lot's of events (from multiple different threads) that create a `this.StateManager.CreateTransaction` and set some data using `SetAsync()` and `CommitAsync()` all to the same reliable dictionary. 

Could that be an issue?

Thanks.

**Comment by preethasubbarayalu** [comment]
Hi @SndrSchnklshk: Are you mutating your value object after you have inserted it into the dictionary? Concurrent transaction should not be causing any issue. But make sure you don't do operations concurrently within a transaction and you await on all the async calls. You should not be mutating the objects in memory after you have inserted it into the dictionary.

Thanks
Preetha

**Comment by SndrSchnklshk** [comment]
Hi @preethasubbarayalu, no I'm not changing the object (see my code above, it creates a clone every time) after insert.

As promised an update about my 'lost dictionary' issue. **It looks like the problem is solved!**

I have changed the following things:
1) Removed all the 'retry-loops' where I load and save the dictionary
2) Minimized the code inside the transaction using scope
3) Added the forgotten [DataMember] attributes to my data class. Thanks @zuhairp
4) Reduced the time to keep data in the dictionary down to 4 hours (instead of 12)
5) Changed the value of the dictionary to an Array instead of List<T> ... it just feels better :)
6) Last, but not least; Added a 3 second (instead every second) buffer delay where the measurement data come in. To prevent stacking of 'save' calls on the dictionary together with the first (1) item I think this was the major issue.

See chart of the last 24 hours, the data stays there as expected:
![cache_works](https://user-images.githubusercontent.com/35453771/36716882-3efaea1c-1b9c-11e8-9f3c-053a890c13ed.png)

Thanks for the support!

**Comment by preethasubbarayalu** [comment]
Thanks for updating.
