### ISSUE TITLE
Error after installing Service Fabric on 3-Node Windows Cluster

### ISSUE THREAD

**Issue by senj** [Azure/service-fabric-issues#77]
Hallo, this is the error we're getting:

`The Data Collection Agent (DCA) had an unhandled exception and will be stopped. Diagnostics information will be left uncollected if this continues to happen.`

any ideas?

**Comment by masnider** [comment]
Hi @senj - are you able to look at the event viewer or local traces on the machine and are there any obvious errors? If so can you provide them? Is this happening on all the machines or just some of them? Also can you share the configuration for this cluster?

**Comment by senj** [comment]
Thanks for your reply. In the error logs I can see the following:

```
Application: FabricDCA.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
Stack:
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.DriveInfo.get_AvailableFreeSpace()
   at FabricDCA.EtlRetentionManager.GetDiskSpaceToFree(UInt32[] ByRef, Boolean ByRef)
   at FabricDCA.EtlRetentionManager.DeleteOldLogsCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

So it has something to do with access rights. We deployed a Windows Secured Cluster.

For node-to-node authorization (ClusterIdentity), we tried to created a system user and added this user as admin to each of the node, but it didnt work.
Then we added one user for each node. 
This way we were able to build the cluster, but this error occors on every node after some minutes. The node then resets, is green for a short time and the error occors again. 

Is this correct or is there more to do?

This is the config

```
{
    "name": "QSCluster",
    "clusterConfigurationVersion": "1.0.0",
    "apiVersion": "2015-01-01-alpha",
    "nodes": [
        {
            "nodeName": "node1",
	    "iPAddress": "OurDNSName1",
            "nodeTypeRef": "NodeType0",
            "faultDomain": "fd:/local/dc1",
            "upgradeDomain": "UD0"
        },
        {
            "nodeName": "node2",
	    "iPAddress": "OurDNSName2",
            "nodeTypeRef": "NodeType0",
            "faultDomain": "fd:/local/dc1",
            "upgradeDomain": "UD1"
        },
        {
            "nodeName": "node3",
	    "iPAddress": "OurDNSName3",
            "nodeTypeRef": "NodeType0",
            "faultDomain": "fd:/local/dc2",
            "upgradeDomain": "UD2"
        }
    ],
    "properties": {
	"enableTelemetry": "false",
	"fabricClusterAutoupgradeEnabled": false,
        "diagnosticsStore": 
        {
            "metadata":  "Please replace the diagnostics file share with an actual file share accessible from all cluster machines.",
            "dataDeletionAgeInDays": "7",
            "storeType": "FileShare",
            "IsEncrypted": "false",
            "connectionstring": "D:\\SF\\DiagnosticsStore"
        },
        "security": {
            "ClusterCredentialType": "Windows",
            "ServerCredentialType": "Windows",
            "WindowsIdentities": {
                "ClusterIdentity": "Domain\\OurDNSName1User,Domain\\OurDNSName2User,Domain\\OurDNSName3User",
                "ClientIdentities": [
                    {
                        "Identity": "Domain\\user",
                        "IsAdmin": true
                    }
                ]
            }
        },
        "reliabilityLevel": "Bronze",
        "nodeTypes": [
            {
                "name": "NodeType0",
                "clientConnectionEndpointPort": "19000",
                "clusterConnectionEndpointPort": "19001",
                "leaseDriverEndpointPort": "19002",
                "serviceConnectionEndpointPort": "19003",
                "httpGatewayEndpointPort": "19080",
                "applicationPorts": {
                    "startPort": "30001",
                    "endPort": "30031"
                },
                "ephemeralPorts": {
                    "startPort": "30032",
                    "endPort": "30287"
                },
                "isPrimary": true
            }
        ],
        "fabricSettings": [
            {
                "name": "Setup",
                "parameters": [
                    {
                        "name": "FabricDataRoot",
                        "value": "E:\\SF"
                    },
                    {
                        "name": "FabricLogRoot",
                        "value": "D:\\SF\\Log"
                    }
                ]
            }
        ]
    }
}
```
