### ISSUE TITLE
Service Fabric - Removing Cluster giving error - Could not load type 'ExtensionsEventsInternal' from assembly 'System .Fabric, Version=6.0.0.0,

### ISSUE THREAD

**Issue by nareshkhatri81** [Azure/service-fabric-issues#781]
Hello Team,

PS D:\SF\Microsoft.Azure.ServiceFabric.WindowsServer.6.0.232.9494> .\RemoveServiceFabricCluster.ps1

Do you want to remove the cluster? [Y] Yes  [N] No (default is 'N'): Y
Removing Microsoft Azure Service Fabric Cluster...
Remove Cluster failed. Please make sure there is an existing cluster to remove. For more information please check traces
 in FabricLogRoot.
Remove Cluster failed. Please make sure there is an existing cluster to remove. For more information please check traces
 in FabricLogRoot.
Remove Cluster failed with exception: System.AggregateException: One or more errors occurred. ---> System.TypeLoadExcept
ion: Could not load type 'ExtensionsEventsInternal' from assembly 'System.Fabric, Version=6.0.0.0, Culture=neutral, Publ
icKeyToken=31bf3856ad364e35'.
   at Microsoft.ServiceFabric.DeploymentManager.SFDeployerTrace.WriteInfo(String format, Object[] args)
   at Microsoft.ServiceFabric.DeploymentManager.SFDeployerTrace.UpdateFileLocation(String traceFolder)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<RemoveClusterAsyncInternal>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManager.<RemoveClusterAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Powershell.ClusterCmdletBase.RemoveCluster(String clusterConfigurationFilePath, Boolean de
leteLog)
---> (Inner Exception #0) System.TypeLoadException: Could not load type 'ExtensionsEventsInternal' from assembly 'System
.Fabric, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.ServiceFabric.DeploymentManager.SFDeployerTrace.WriteInfo(String format, Object[] args)
   at Microsoft.ServiceFabric.DeploymentManager.SFDeployerTrace.UpdateFileLocation(String traceFolder)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<RemoveClusterAsyncInternal>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManager.<RemoveClusterAsync>d__3.MoveNext()<---

Thanks,
Naresh

**Comment by rishirsinha** [comment]
Naresh,

Can you try running this from a machine with full SF installed?

Thanks,
Rishi

**Comment by nareshkhatri81** [comment]
Yes we are running this command inside one of node in cluster where SF runtime is installed.

**Comment by rishirsinha** [comment]
I will follow up on this internally. Meanwhile can you try running it from outside the cluster and see if it succeeds? I would guess worst case an older version of the tools should solve this problem for you.

**Comment by maburlik** [comment]
It's possible this was caused due to a mismatch in version between the tools used to remove the cluster, and the version of the cluster. This can happen if running the tools on a machine where Service Fabric runtime and/or SDK is installed.
