### ISSUE TITLE
restoreContext.RestoreAsync times out

### ISSUE THREAD

**Issue by funrockstefan** [Azure/service-fabric-issues#831]
Currently when we trigger OnDataLossAsync, occationally some of the restore operations times out. Specifically it is the cancellation token in the following call that is notified of cancellation:
await restoreContext.RestoreAsync(restoreRescription, cancellationToken.

In our scenario we have 25 actor services with 20 partitions, running on node type with 5 nodes, and we trigger the data loss on all services and their partitions in parallel using fabricClient.TestManager.StartPartitionDataLossAsync. Not sure if this is supported or if we rather should do it sequential instead.

Exception stack:
Inner: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
...
Inner stacktrace:    at System.Fabric.Interop.NativeRuntime.IFabricKeyValueStoreReplica6.EndRestore(IFabricAsyncOperationContext context)
  at System.Fabric.KeyValueStoreReplica.RestoreEndWrapper(IFabricAsyncOperationContext context)
  at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context)
  at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)

**Comment by funrockstefan** [comment]
Update: Indeed when restoring each service in sequence ( though all partitions within each service in parallel) it succeeds.

**Comment by alexwun** [comment]
It's not related to performing the restores in parallel or sequentially per se, but the higher amount of replica building with parallel restores is probably causing some replica load balancing movement, cancelling some of the pending dataloss calls. Either try reducing the parallelism of restores as you've done or pass CancellationToken.None to avoid restore being cancelled.
