### ISSUE TITLE
UpgradeOrchestrationService in Quorum Loss after code version update

### ISSUE THREAD

**Issue by nahmed01** [Azure/service-fabric-issues#832]
Hi champs,
I upgraded code version to 6.1.456 which went fine.then i had to remove and recreate my cluster.
after recreating the cluster, "upgradeorchestrationservice" is in quorum loss, not sure how to fix, any help will be appreciated
![image](https://user-images.githubusercontent.com/36216668/35944479-abf5ade6-0cb0-11e8-98f4-c463c0ea32ac.png)

**Comment by rishirsinha** [comment]
Can you check on the nodes to see whether there are any crash reports? It looks like the UOS primary is crashing. If the SFX does not show anything, looking at the event log might help.

**Comment by nahmed01** [comment]
Thanks Rishi

Yes there are error reports in event log every 5 minutes, here is the dump:

Baseline upgrade JsonClusterConfigMetadata not found at C:\ProgramData\SF\ClusterConfigMetadata.json.-
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Fabric.Common.ReleaseAssert.Failfast(String format, Object[] args)
   at System.Fabric.UpgradeOrchestration.Service.FabricUpgradeOrchestrationService.InitClusterResource(NativeConfigStore configStore)
   at System.Fabric.UpgradeOrchestration.Service.FabricUpgradeOrchestrationService.<RunAsync>d__17.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at System.Fabric.UpgradeOrchestration.Service.DatalossHelper.<IsInDatalossStateAsync>d__0.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at System.Fabric.Common.FabricClientRetryHelper.<ExecuteFabricActionWithRetryAsync>d__15`1.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at System.Fabric.Common.FabricClientRetryHelper.<ExecuteFabricActionWithRetryAsync>d__17`1.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.TaskCompletionSource`1.TrySetResult(TResult result)
   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)

**Comment by butsona** [comment]
I have also experience this issue with a create install to 6.1. After checking other clusters the mentioned file doesn't exists.

**Comment by rakshitatandon** [comment]
Can you make sure you are using the right client binaries for deploying the cluster i.e. the one from http://go.microsoft.com/fwlink/?LinkId=730690 ?

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server

**Comment by nahmed01** [comment]
Thanks Rakshi,
will try your suggestions and get back to you

**Comment by pflynnexedal** [comment]
Any luck on this? We're experiencing the same issue.

**Comment by rakshitatandon** [comment]
#800

**Comment by nahmed01** [comment]
when you have multiple machines in the cluster, it can pick any machine as a source (not necessarily the one you are running the create cluster from).In my case the machine it was picking didn't have the correct binaries, after downloading correct binaries to that machine (in fact the easiest is to install it on each machine) it worked.
Thanks Rakshita for pointing that out

**Comment by barishamil** [comment]
I deleted DeploymentRuntimePackage folder, removed the cluster and created it again, still the same issue

**Comment by rakshitatandon** [comment]
You should delete the entire standalone package folder and download the latest one from here Download Link - Service Fabric Standalone Package - Windows Server (Microsoft.Azure.ServiceFabric.WindowsServer.6.1.472.9494).
