### ISSUE TITLE
Chaos Test on ASF standalone cluster and unresposibe application

### ISSUE THREAD

**Issue by dealboy** [Azure/service-fabric-issues#846]
Hi,

we have a .net application running as guest executable in our cluster.
We expose that application using ReverseProxy.

While doing a basic load test we initiate in parallel a chaos test.

Then we get Warning messages on the nodes like 

> Warning
>     Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false.
> Replica had multiple failures during open on MY-LA-SRV773. API call: IStatelessServiceInstance.Open(); Error = System.InvalidOperationException (-2146233079)
> Mapper already initialized. You must call Initialize once per application domain/process.
>    at AutoMapper.Mapper.set_Configuration(IConfigurationProvider value)
>    at AutoMapper.Mapper.Initialize(Action`1 config)
>    at Solution.Services.MyManager.Web.Composition.ConfigureModule.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IConfiguration configuration) in D:\vsts-agent_2\_work\91\s\Solution.Services.MyManager.Web\Composition\ConfigureModule.cs:line 91
>    at Solution.Services.MyManager.Web.ServiceFabricStartup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IApplicationLifetime applicationLifetime) in D:\vsts-agent_2\_work\91\s\Solution.Services.MyManager.Web\ServiceFabricStartup.cs:line 47
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at Solution.Services.MyManager.Web.Web.<>c__DisplayClass1_0.b__1(String url, AspNetCoreCommunicationListener listener) in D:\vsts-agent_2\_work\91\s\Solution.Services.MyManager.Web\Web.cs:line 34
>    at Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener.OpenAsync(CancellationToken cancellationToken)
>    at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__20.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__14.MoveNext()
> For more information see: http://aka.ms/sfhealth 
> 

and the application becomes unresponsive from ReverseProxy. 
Also, we wait for the app to recover but never does.

How can we ensure that the application dies immediately without waiting for timeouts?

kind regards
Yannis

**Comment by dealboy** [comment]
hi @masnider , @amanbha , @motanv 

do you have any updates on that?

Our core questions are:
How can we configure SF to kill/end an application without waiting for timeouts?
What is the root cause of getting error "Mapper already initialized. You must call Initialize once per application domain/process" when doing the chaos test? 
Is it that the application is not killed ?

kind regards
Yannis

**Comment by MikkelHegn** [comment]
Hi,

From the stack trace above, it looks like the application is crashing on start (Property='ReplicaOpenStatus') with this exception: Mapper already initialized. You must call Initialize once per application domain/process. at AutoMapper.Mapper.set_Configuration(IConfigurationProvider value). You should look at what is going on with the application at startup.

When SF wants to move (or upgrade) an application (guest executable) it sends a Ctrl+C command. If your application handles this command, you can react to the event, if not is should be terminated. There is a timeout SF waits for the process to exit, which is globally configurable in the cluster.
