### ISSUE TITLE
Unable to change open service manager handle because 5

### ISSUE THREAD

**Issue by HimanshuNimawat** [Azure/service-fabric-issues#849]
Unable to change open service manager handle because 5
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because 5
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Querying remote registry service on machine 192.168.5.131 resulted in exception: Unable to change open service manager handle because 5.
Unable to change open service manager handle because 5
Unable to query service configuration because System.InvalidOperationException: Unable to change open service manager handle because 5
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceStartupType(String machineName, String serviceName)
Querying remote registry service on machine 192.168.5.114 resulted in exception: Unable to change open service manager handle because 5.
Best Practices Analyzer determined environment has an issue. Please see additional BPA log output in DeploymentTraces folder.

**Comment by HimanshuNimawat** [comment]
I downloaded the sample standalone package from microsoft docs.....then enable other laptops remote registry services and then edited the unsecure.multimachine file in package....in that i just changed the ip address of other laptops....and then getting this error
