### ISSUE TITLE
FatalExecutionEngineError when Microsoft.ServiceBus throws an exception

### ISSUE THREAD

**Issue by NickDarvey** [Azure/service-fabric-issues#86]
We have a stateful service running as an Event Hub consumer and if it fails to get a connection (authorization issue, internet issue, etc.) the client library throws an exception.

The problem is we can't catch this in a Service Fabric local cluster environment and it causes a `FatalExecutionEngineError` which makes offline debugging excruciating.

I've seen others with the issue on [StackOverflow](http://stackoverflow.com/questions/38356407/service-fabric-stateless-service-behaviour).

The library is WindowsAzure.ServiceBus 3.4.0 and below is the exception. Let me know if I can provide any other information.

```
FatalExecutionEngineError occurred
  HResult=-2146233088
  IsTransient=true
  Message=An error occurred during communication with '40.127.83.321:10409'. Check the connection information, then retry.
  Source=Microsoft.ServiceBus
  StackTrace:
       at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
       at Microsoft.ServiceBus.Messaging.EventHubConsumerGroup.<>c.<CreateReceiverAsync>b__53_1(IAsyncResult r)
       at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at EventHubListenerLib.EventHubListenerPartitionReceiver.<CreateEventHubReceiverAsync>d__7.MoveNext() in C:\Users\Cat\Source\Repos\meow\IoTHubService\Libraries\EventHubListenerLib\EventHubListenerReceiver.cs:line 43
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at EventHubListenerLib.EventHubListenerPartitionReceiver.<StartAsync>d__10.MoveNext() in C:\Users\Cat\Source\Repos\meow\IoTHubService\Libraries\EventHubListenerLib\EventHubListenerReceiver.cs:line 104
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at EventHubListenerLib.EventHubListener.<StartAsync>d__12.MoveNext() in C:\Users\Cat\Source\Repos\meow\IoTHubService\Libraries\EventHubListenerLib\EventHubListener.cs:line 140
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at IoTHubService.IoTHubService.<RunAsync>d__4.MoveNext() in C:\Users\Cat\Source\Repos\meow\IoTHubService\IoTHubService.cs:line 175
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.<ExecuteRunAsync>d__f.MoveNext()
  InnerException: 
       ErrorCode=10060
       HResult=-2147467259
       Message=A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
       NativeErrorCode=10060
       Source=Microsoft.ServiceBus
       StackTrace:
            at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
            at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.OpenLinkAsyncResult.<>c.<GetAsyncSteps>b__35_11(OpenLinkAsyncResult thisPtr, IAsyncResult r)
            at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
       InnerException:
```

**Comment by jtaubensee** [comment]
@NickDarvey - Can you provide some reproduction steps for this? I am a PM on the Service Bus / Event Hubs team, and we want to make sure that this isn't a problem with our client. Thanks.

**Comment by jtaubensee** [comment]
Also it would be best to see if you can reproduce this error in a console app, to rule out Service Fabric.

**Comment by masnider** [comment]
Hi @NickDarvey - unless there's a good repro of this we're going to close down the incident. Please let us know if you can share code and steps that reproduce the issue.

**Comment by masnider** [comment]
Closing as no-repro. Please reopen if you can repro this or have further questions.
