### ISSUE TITLE
Unable to create/start local cluster on Windows 7 machine

### ISSUE THREAD

**Issue by ajeetcoolkarni** [Azure/service-fabric-issues#860]
We have windows 7 with VS 2015 Update 3 and **Service Fabric Runtime 6.1.456.9494** installed along with **Service Fabric SDK 3.0.456**. There are no errors while installing either the runtime or sdk, but still while setting up local cluster it fails with following errors, and this is happening in all the machines we are using.

**2>WARNING: Service Fabric Cluster is taking longer than expected to connect.
2>
2>Waiting for Naming Service to be ready. This may take a few minutes...
2>Connect-ServiceFabricCluster : No cluster endpoint is reachable, please check 
2>if there is connectivity/firewall/DNS issue.
2>At C:\Program Files\Microsoft SDKs\Service 
2>Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:620 char:12
2>+     [void](Connect-ServiceFabricCluster @connParams)
2>+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2>    + CategoryInfo          : InvalidOperation: (:) [Connect-ServiceFabricClus 
2>   ter], FabricException
2>    + FullyQualifiedErrorId : TestClusterConnectionErrorId,Microsoft.ServiceFa 
2>   bric.Powershell.ConnectCluster**

**Faulting application name: Fabric.exe, version: 6.1.456.9494, time stamp: 0x5a66710e
Faulting module name: FabricCommon.dll_unloaded, version: 0.0.0.0, time stamp: 0x5a666cec
Exception code: 0xc0000005
Fault offset: 0x000007febd3e6d31
Faulting process id: 0x2854
Faulting application start time: 0x01d3a64824f31fdc
Faulting application path: C:\SfDevCluster\Data\_Node_0\Fabric\Fabric.Code\Fabric.exe
Faulting module path: FabricCommon.dll
Report Id: 62dd8dbf-123b-11e8-bbb0-00505699504f**

I don't see anything useful in Trace logs either.
[CrashDump.zip](https://github.com/Azure/service-fabric-issues/files/1727397/CrashDump.zip)
[TraceLogs.zip](https://github.com/Azure/service-fabric-issues/files/1727400/TraceLogs.zip)

I tried resintalling **microsoft visual c++ 2012 redistributable package (x64)** , tried running cleanupfabric , cleanupcluster but still the issue persists. 
Also unisntalled and reinstalled service fabric runtime and sdk multiple times, still issue persists.

**Comment by rishirsinha** [comment]
Please reinstall VC 11 and VC 15 both.

**Comment by jrance** [comment]
I am facing the exact same issue. I have reinstalled all the VC packages, reinstalled SF tools and SDK, and I've even reinstalled Visual Studio 2017 with no luck. 

Version 6.1.467.9494 just got released so I was hoping that would fix the issue but I'm getting the same errors. I am dead in the water until I get this resolved.

It looks like others on Windows 7 machines are facing the same issue according to this stackoverflow thread.

https://stackoverflow.com/questions/48806240/unable-to-create-start-local-cluster-on-windows-7-machine

**Comment by jrance** [comment]
Some additional information. My sfdevcluster folder contains a number of dump files in the CrashDumps folder. When I open them up in VS, I see the following exception.

> 
> Exception Code: 0xC0000005
> Exception Information: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

In the ArchivedTraces folder, there are a number of fabricdeployer traces with the following exception in them.

> 2018/02/21-23:00:30.119,Warning,10004,FabricDeployer.FabricDeployer,Error getting feature state for feature Containers. This usually means that the platform doesn't support DISM APIs. Treating feature as not present and continuing. Exception: System.DllNotFoundException: Unable to load DLL 'DismApi': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
> 	   at System.Fabric.FabricDeployer.DismNativeMethods.DismInitialize(DismLogLevel logLevel, String logFilePath, String scratchDirectory)
> 	   at System.Fabric.FabricDeployer.DismHelper.Execute(Func`1 nativeFunc)
> 	   at System.Fabric.FabricDeployer.DismHelper.GetFeatureState(String featureName)
> 	   at System.Fabric.FabricDeployer.DockerDnsHelper.IsContainersFeaturePresent()
> 2018/02/21-23:00:30.135,Info,10004,FabricDeployer.FabricDeployer,Containers feature not present. Not continuing further
>

**Comment by joriente** [comment]
Having the same exact issue and I see these 4 recurring warnings in the SF logs
1. HostedServiceInstance:HostedService/_Node_0_Fabric terminated with exitcode 3221225477
2. HostedService: _Node_0 on node id bf865279ba277deb864a976fbf4c200e terminated unexpectedly with code 3221225477 and process name Fabric.exe
3. client-localhost:19000/[::1]:19000: error = 2147943625, failureCount=805. Filter by (type~Transport.St && ~"(?i)localhost:19000") to get listener lifecycle. Connect failure is expected if listener was never started, or listener/its process was stopped before/during connecting.
4. client-localhost:19000 : connect failed, having tried all addresses

**Comment by rishirsinha** [comment]
@joriente can you share the Fabric.exe dumps.

**Comment by joriente** [comment]
Do you want them all?  Is there a good way to get them to you,  Its 151MB compressed and this only supports 10MB.  Tried splitting and this didn't support then split file type?

**Comment by rishirsinha** [comment]
Send over email? rsinha@microsoft.com.

**Comment by AKozmanyan** [comment]
Hi @rishirsinha , I'm experiencing exactly the same issue. Fabric.exe fails to start with dump saying: "The thread tried to read from or write to a virtual address for which it does not have the appropriate access."
Windows 7, VS 2017
Module Name	Module Path	Module Version
-----------	-----------	--------------
Fabric.exe	C:\SfDevCluster\Data\_Node_0\Fabric\Fabric.Code\Fabric.exe	6.2.301.9494
ntd1l.dll	C:\WINDOWS\SYSTEM32\ntd1l.dll	0.0.0.0
kern3l32.dll	C:\WINDOWS\system32\kern3l32.dll	0.0.0.0
ntdll.dll	C:\Windows\System32\ntdll.dll	6.1.7601.24117
kernel32.dll	C:\Windows\System32\kernel32.dll	6.1.7601.24117
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	6.1.7601.24117
api-ms-win-core-synch-l1-2-0.dll	C:\Windows\System32\api-ms-win-core-synch-l1-2-0.dll	10.0.10586.1412
FabricZip.dll	C:\SfDevCluster\Data\_Node_0\Fabric\Fabric.Code\FabricZip.dll	6.2.301.9494
mscoree.dll	C:\Windows\System32\mscoree.dll	4.0.40305.0

Antivirus: SentinelOne - But I'm unable to disable it. Is that the reason?
