### ISSUE TITLE
Unable to connect to azure service fabric cluster linux

### ISSUE THREAD

**Issue by ushasm** [Azure/service-fabric-issues#861]
Hi Team,

I am trying to connect to azure fabric cluster (linux) but I always gets this error. The  https://jenkinscluster.westeurope.cloudapp.azure.com:19080/Explorer works through browser with same certificate but it fails when I try to connect it through my terminal with same certificate.

sfctl cluster select --endpoint https://jenkinscluster.westeurope.cloudapp.azure.com:19080/Explorer  --pem Certificates.p12
Error occurred in request., SSLError: HTTPSConnectionPool(host='jenkinscluster.westeurope.cloudapp.azure.com', port=19080): Max retries exceeded with url: /Explorer/ (Caused by SSLError(SSLError(336445449, '[SSL] PEM lib (_ssl.c:3337)'),))
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 327, in ssl_wrap_socket
    context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:3337)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='jenkinscluster.westeurope.cloudapp.azure.com', port=19080): Max retries exceeded with url: /Explorer/ (Caused by SSLError(SSLError(336445449, '[SSL] PEM lib (_ssl.c:3337)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/msrest/service_client.py", line 201, in send
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='jenkinscluster.westeurope.cloudapp.azure.com', port=19080): Max retries exceeded with url: /Explorer/ (Caused by SSLError(SSLError(336445449, '[SSL] PEM lib (_ssl.c:3337)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/usr/local/lib/python3.6/site-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/lib/python3.6/site-packages/sfctl/custom_cluster.py", line 95, in select
    rest_client.send(rest_client.get('/')).raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/msrest/service_client.py", line 227, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/usr/local/lib/python3.6/site-packages/msrest/exceptions.py", line 45, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/lib/python3.6/site-packages/msrest/service_client.py", line 201, in send
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., SSLError: HTTPSConnectionPool(host='jenkinscluster.westeurope.cloudapp.azure.com', port=19080): Max retries exceeded with url: /Explorer/ (Caused by SSLError(SSLError(336445449, '[SSL] PEM lib (_ssl.c:3337)'),))

**Comment by ushasm** [comment]
Tried using --no-verify and also the endpoint but the result is same :(
I am using a self signed certificate to authenticate.

**Comment by Thialala** [comment]
Hello,
I had the same issue. I converted the pfx certifcate to pem certificate using this : https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cli#tips-and-troubleshooting 

And it works.

**Comment by prasadker** [comment]
Yes you'll have to convert the pfx to pem file to use it for Linux cluster.

**Comment by mani-ramaswamy** [comment]
Thanks @Thialala and @prasadker. @ushasm let us knkow if that unblocked you.

**Comment by gheibia** [comment]
@ushasm whilst this issue is being investigated, you can always use cUrl to call SFC's APIs. For example: https://stackoverflow.com/questions/54089465/add-custom-header-to-all-responses-from-traefik-on-azures-service-fabric

**Comment by masnider** [comment]
Closing since as far as we know converting the cert did and should fix this issue.

**Comment by MattHartz** [comment]
Doesn't work for me. Converted pfx to pem.
