### ISSUE TITLE
Service fabric stateful application crash - Existing must be delete

### ISSUE THREAD

**Issue by somesh84** [Azure/service-fabric-issues#894]
Hi I have simple stateful application using reliable dictionary. It has high number of transaction. I have batch commit on my code to improve performance. But after sometime my application crashes with below exception

Errormsg=Existing must be delete Assert=System.Exception:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at Microsoft.ServiceFabric.Data.ReplicatedStore.DifferentialStore.RecoveryStoreComponent`5.AddOrUpdate(TKey inputKey, TVersionedItem`1 inputValue)
   at Microsoft.ServiceFabric.Data.ReplicatedStore.DifferentialStore.RecoveryStoreComponent`5.<MergeAsync>d__19.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at System.Fabric.Store.KeyCheckpointFileAsyncEnumerator`2.<MoveNextAsync>d__24.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at System.Fabric.Store.KeyCheckpointFileAsyncEnumerator`2.<ReadChunkAsync>d__25.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.IO.FileStream.EndReadTask(IAsyncResult iar)
   at System.IO.FileStreamAsyncResult.AsyncFSCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP) at Time=‎2018‎-‎02‎-‎22T06:57:22.683718400Z

Service fabric version – 6.0.232 (Set for auto upgrade)

**Comment by masnider** [comment]
@somesh84 - can you share the code? Particularly, what do you mean by "batch commit"? If you can provide more information about what operations are in each transaction (add, removes, updates, etc) that would be helpful.

**Comment by somesh84** [comment]
this is what I mean by batch commit, prefixesToUpdate to update is a dictionary. I also have lock held thru out this code
  
          using (var tx = StateManager.CreateTransaction())
                {
                    foreach (var prefix in prefixesToUpdate)
                    {
                        if (prefix.Value == Action.AddOrUpdate)
                        {
                            await persistedPrefixMap.AddOrUpdateAsync(
                                tx,
                                prefix.Key,
                                prefixMap[prefix.Key],
                                (key, value) => prefixMap[prefix.Key]);
                        }
                        else
                        {
                            await persistedPrefixMap.TryRemoveAsync(tx,
                                prefix.Key);
                        }
                    }

                    await tx.CommitAsync();
                }

**Comment by somesh84** [comment]
To add here the first error event I saw in SF before this issue started, attaching all events

Errormsg=Cannot add an item that already exist. Txn: 131644161079020579 CommitLSN: 143316 CheckpointLSN: 0 key: 1921084667203482050 RecordKind: InsertedVersion Assert=System.Exception:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Fabric.Store.TStore`5.OnApplyAdd(TransactionBase txn, MetadataOperationData metadataOperationData, RedoUndoOperationData operationRedoUndo, Boolean isIdempotent, String applyType)
   at System.Fabric.Store.TStore`5.<OnSecondaryApplyAsync>d__294.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Fabric.Store.TStore`5.OnSecondaryApplyAsync(Int64 sequenceNumber, TransactionBase replicatorTransaction, MetadataOperationData metadataOperationData, RedoUndoOperationData operationRedoUndo, Boolean isIdempotent)
   at System.Fabric.Store.TStore`5.<Microsoft-ServiceFabric-Replicator-IStateProvider2-ApplyAsync>d__237.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Fabric.Store.TStore`5.Microsoft.ServiceFabric.Replicator.IStateProvider2.ApplyAsync(Int64 sequenceNumber, TransactionBase replicatorTransaction, OperationData metadata, OperationData operationData, ApplyContext applyContext)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<OnApplyAsync>d__107.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.OnApplyAsync(Int64 lsn, TransactionBase transaction, OperationData metaData, OperationData actualData, ApplyContext applyContext, Int64 stateProviderId)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<OnApplyAsync>d__106.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.OnApplyAsync(Int64 lsn, TransactionBase transaction, OperationData metaData, OperationData data, ApplyContext applyContext)
   at Microsoft.ServiceFabric.Replicator.OperationProcessor.<ApplyCallback>d__36.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ServiceFabric.Replicator.OperationProcessor.ApplyCallback(LogRecord record)
   at Microsoft.ServiceFabric.Replicator.OperationProcessor.<ProcessLoggedRecordAsync>d__32.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ServiceFabric.Replicator.OperationProcessor.ProcessLoggedRecordAsync(LogRecord record)
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher.<ProcessTransaction>d__21.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher.ProcessTransaction(List`1 transaction)
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher.<SeparateTransactions>d__22.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher.SeparateTransactions()
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher.<ProcessLoggedRecords>d__18.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher.ProcessLoggedRecords()
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher.<StartProcessingLoggedRecords>d__23.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher.StartProcessingLoggedRecords()
  at Microsoft.ServiceFabric.Replicator.LogRecordsDispatcher.DispatchLoggedRecords(LoggedRecords loggedRecords)
   at Microsoft.ServiceFabric.Replicator.LoggingReplicator.FlushedRecordsCallback(LoggedRecords loggedRecords)
   at Microsoft.ServiceFabric.Replicator.PhysicalLogWriterCallbackManager.InvokeFlushedRecordsCallback(Object state)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch() at Time=‎2018‎-‎03‎-‎01T22:15:16.245398800Z

**Comment by preethasubbarayalu** [comment]
@somesh84- This can happen if there is an issue with your comparer:
1. What is your key type ?
2. Do you use data contract serializer or your own custom serializer.

**Comment by masnider** [comment]
@somesh84 - Hi there. We haven't heard from you in a while and usually this crash is what @preethasubbarayalu pointed out. We're going to close this issue down now. If you are still having this problem and can share the information about your comparer and think it's working fine, then feel free to reopen the issue. If you're having other issues or questions, please feel free to open a new issue. Thanks!
