### ISSUE TITLE
Getting error with Standalone CreateServiceFabricCluster.ps1 on 6.1.467.9494

### ISSUE THREAD

**Issue by jbarber2016** [Azure/service-fabric-issues#904]
When I run CreateServiceFabricCluster.ps1 with -Verbose, I get the following output.

VERBOSE: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors
occurred. ---> System.MissingMethodException: Method not found: 'System.String
System.Fabric.Strings.StringResources.get_Error_BPAMachineIsDomainController()'.
   at
Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.<>c__DisplayClass18_0.<CheckNoMachineIsDomainContro
ller>b__0(String machineName)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions
parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions
parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal,
Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at
Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.CheckNoMachineIsDomainController(IEnumerable`1
machineNames)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.AnalyzeClusterSetup(String configPath, String
 oldConfigPath, String cabPath, Boolean usingClusterManifest, FabricPackageType fabricPackageType, Boolean
isForcedRun)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManager.<CreateClusterAsync>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Powershell.ClusterCmdletBase.NewCluster(String clusterConfigurationFilePath, String
fabricPackageSourcePath, Boolean noCleanupOnFailure, Boolean force)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.MissingMethodException:
Method not found: 'System.String System.Fabric.Strings.StringResources.get_Error_BPAMachineIsDomainController()'.
   at
Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.<>c__DisplayClass18_0.<CheckNoMachineIsDomainContro
ller>b__0(String machineName)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions
parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions
parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal,
Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at
Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.CheckNoMachineIsDomainController(IEnumerable`1
machineNames)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.AnalyzeClusterSetup(String configPath, String
 oldConfigPath, String cabPath, Boolean usingClusterManifest, FabricPackageType fabricPackageType, Boolean
isForcedRun)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManager.<CreateClusterAsync>d__2.MoveNext()
---> (Inner Exception #0) System.MissingMethodException: Method not found: 'System.String
System.Fabric.Strings.StringResources.get_Error_BPAMachineIsDomainController()'.
   at
Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.<>c__DisplayClass18_0.<CheckNoMachineIsDomainContro
ller>b__0(String machineName)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #1) System.MissingMethodException: Method not found: 'System.String
System.Fabric.Strings.StringResources.get_Error_BPAMachineIsDomainController()'.
   at
Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.<>c__DisplayClass18_0.<CheckNoMachineIsDomainContro
ller>b__0(String machineName)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #2) System.MissingMethodException: Method not found: 'System.String
System.Fabric.Strings.StringResources.get_Error_BPAMachineIsDomainController()'.
   at
Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.<>c__DisplayClass18_0.<CheckNoMachineIsDomainContro
ller>b__0(String machineName)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
<---

**Comment by ashishnegi** [comment]
This problem usually occurs if you have older SF instances around on the machine.

Check your %PATH% for any folders which have older versions of Service Fabric runtime `Fabric.Code` folder.
Can you try this on a clean machine ?

**Comment by jbarber2016** [comment]
I try this on clean machine.  Now getting these errors:

PS F:\Temp\Microsoft.Azure.ServiceFabric.WindowsServer.6.1.467.9494> .\CreateServiceFabricCluster.ps1 -ClusterConfigFile
Path .\ClusterConfig.Unsecure.MultiMachine.SFProd.json -AcceptEULA -Verbose
Trace folder already exists. Traces will be written to existing trace folder: F:\Temp\Microsoft.Azure.ServiceFabric.Wind
owsServer.6.1.467.9494\DeploymentTraces
Creating Service Fabric Cluster...
If it's taking too long, please check in Task Manager details and see if Fabric.exe for each node is running. If not, please look at: 1. traces in DeploymentTraces directory and 2. traces in FabricLogRoot configured in ClusterConfig.json.
Trace folder already exists. Traces will be written to existing trace folder: F:\Temp\Microsoft.Azure.ServiceFabric.WindowsServer.6.1.467.9494\DeploymentTraces
Running Best Practices Analyzer...
Machine 'XX.XXX.XX.144' is not reachable on port 445. Check connectivity/open ports. Error: A connection attempt failed
because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond XX.XXX.XX.144:445.
Machine 'XX.XXX.XX.143' is not reachable on port 445. Check connectivity/open ports. Error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond XX.XXX.XX.143:445.
Best Practices Analyzer determined environment has an issue. Please see additional BPA log output in DeploymentTraces folder.
Cluster Setup cancelled due to validation error(s) found by Best Practices Analyzer. Inspect details in DeploymentTraces
 log folder local to executing location.
Create Cluster failed. For more information please look at traces in FabricLogRoot.
VERBOSE: System.AggregateException: One or more errors occurred. ---> System.Fabric.FabricValidationException: Cluster
Setup cancelled due to validation error(s) found by Best Practices Analyzer. Inspect details in DeploymentTraces log
folder local to executing location.
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManager.<CreateClusterAsync>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Powershell.ClusterCmdletBase.NewCluster(String clusterConfigurationFilePath, String
fabricPackageSourcePath, Boolean noCleanupOnFailure, Boolean force)
---> (Inner Exception #0) System.Fabric.FabricValidationException: Cluster Setup cancelled due to validation error(s)
found by Best Practices Analyzer. Inspect details in DeploymentTraces log folder local to executing location.
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManager.<CreateClusterAsync>d__2.MoveNext()<---

**Comment by jbarber2016** [comment]
Ok nevermind.  I had wrong IP address.
