### ISSUE TITLE
New Project - Misconfigured Stateless Services

### ISSUE THREAD

**Issue by DaemonTrey** [Azure/service-fabric-issues#907]
I've recently noticed that the service references in our sfproj are displaying as if they are in a warning state, despite no warnings being visible. While trying to figure out why they are displaying this way I thought to compare them to a brand new sfproj with a stateless service. It however has the same problem as seen here: https://www.screencast.com/t/scjN3eT2OGv  
In addition, attempts to re-add an existing service warns that the service is misconfigured. (Also seen in the video)

**This appears to be an issue for us because** we are troubleshooting a missing ApplicationManifest in our VSTS deploy step where the error reads: 
> ##[error]The BuildLayout of the application in C:\Users\VssAdministrator\AppData\Local\Temp\TestApplicationPackage_6695325864\3j0vgjqp.kum\a is invalid. File ApplicationManifest.xml is missing.

The error text of a SFProj add of an existing reference reads: 

> In order to successfully package the referenced service as part of the application, the file ~ApplicationManifest.xml may need to be updated (if the service is an Actor or Web service, ~ApplicationManifest.xml will be automatically updated the next time you build). See https://go.microsoft.com/fwlink/?Linkid=724312 for more information.

This makes me think that the default configuration of stateless services are misconfigured (and by extension our existing services). 

Is this the case? or are these services just erroneously flagged as misconfigured?

**Comment by dbreshears** [comment]
@DaemonTrey ,    the warnings triangles are known issue with compatibility of CPS (common project system) and our deployment project so that aspect can be ignored.

Can you please share the debug output of your VSTS build after setting the build variable  "System.Debug"  to true?

**Comment by DaemonTrey** [comment]
Hello @dbreshears -- Thank you for your interest.

Certainly:
> 2018-03-09T00:57:21.7296260Z ##[debug]Evaluating condition for step: 'Deploy Service Fabric Application'
2018-03-09T00:57:21.7297631Z ##[debug]Evaluating: succeeded()
2018-03-09T00:57:21.7298060Z ##[debug]Evaluating succeeded:
2018-03-09T00:57:21.7298809Z ##[debug]=> (Boolean) True
2018-03-09T00:57:21.7300016Z ##[debug]Expanded: True
2018-03-09T00:57:21.7301445Z ##[debug]Result: True
2018-03-09T00:57:21.7302130Z ##[section]Starting: Deploy Service Fabric Application
2018-03-09T00:57:21.7312330Z ==============================================================================
2018-03-09T00:57:21.7312792Z Task         : Service Fabric Application Deployment
2018-03-09T00:57:21.7313681Z Description  : Deploy a Service Fabric application to a cluster.
2018-03-09T00:57:21.7314650Z Version      : 1.7.1
2018-03-09T00:57:21.7314919Z Author       : Microsoft Corporation
2018-03-09T00:57:21.7315259Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=820528)
2018-03-09T00:57:21.7315760Z ==============================================================================
2018-03-09T00:57:22.4727661Z ##[debug]VstsTaskSdk 0.8.2 commit 
2018-03-09T00:57:22.7096251Z ##[debug]Entering D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\deploy.ps1.
2018-03-09T00:57:22.7111186Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\task.json
2018-03-09T00:57:22.8276189Z ##[debug]Loaded 52 strings.
2018-03-09T00:57:22.8336839Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-03-09T00:57:22.8396212Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\Strings\resources.resjson\en-US\resources.resjson
2018-03-09T00:57:22.9557469Z ##[debug]Loaded 52 strings.
2018-03-09T00:57:22.9622327Z ##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\ps_modules\ServiceFabricHelpers\ServiceFabricHelpers.psm1'.
2018-03-09T00:57:22.9677860Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\ps_modules\ServiceFabricHelpers\module.json
2018-03-09T00:57:22.9965580Z ##[debug]Loaded 11 strings.
2018-03-09T00:57:22.9998928Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-03-09T00:57:23.0024780Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\ps_modules\ServiceFabricHelpers\Strings\resources.resjson\en-US\resources.resjson
2018-03-09T00:57:23.0313529Z ##[debug]Loaded 11 strings.
2018-03-09T00:57:23.0549066Z ##[debug]Entering Find-VstsFiles.
2018-03-09T00:57:23.0687764Z ##[debug] LiteralDirectory: 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\ps_modules\ServiceFabricHelpers'
2018-03-09T00:57:23.0707790Z ##[debug] LegacyPattern: '*.ps1'
2018-03-09T00:57:23.1225482Z ##[debug]Entering Get-MatchingItems.
2018-03-09T00:57:23.1262097Z ##[debug] IncludePatterns: 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\ps_modules\ServiceFabricHelpers\*.ps1'
2018-03-09T00:57:23.1324361Z ##[debug] ExcludePatterns: ''
2018-03-09T00:57:23.1372425Z ##[debug] IncludeFiles: 'True'
2018-03-09T00:57:23.1392002Z ##[debug] IncludeDirectories: 'False'
2018-03-09T00:57:23.1416628Z ##[debug] Force: 'False'
2018-03-09T00:57:23.3717355Z ##[debug]Paths: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\ps_modules\ServiceFabricHelpers\
2018-03-09T00:57:23.3718598Z ##[debug] Connect-ServiceFabricClusterFromServiceEndpoint.ps1
2018-03-09T00:57:23.3719206Z ##[debug] Get-ServiceFabricEncryptedText.ps1
2018-03-09T00:57:23.3753276Z ##[debug]Leaving Get-MatchingItems.
2018-03-09T00:57:23.3867069Z ##[debug]Total found: 2
2018-03-09T00:57:23.3887692Z ##[debug]Leaving Find-VstsFiles.
2018-03-09T00:57:23.3907098Z ##[debug]Exporting function 'Connect-ServiceFabricClusterFromServiceEndpoint'.
2018-03-09T00:57:23.3924788Z ##[debug]Exporting function 'Get-ServiceFabricEncryptedText'.
2018-03-09T00:57:23.3943502Z ##[debug]Importing function 'Connect-ServiceFabricClusterFromServiceEndpoint'.
2018-03-09T00:57:23.3967200Z ##[debug]Importing function 'Get-ServiceFabricEncryptedText'.
2018-03-09T00:57:23.6013576Z ##[debug]Loading module from path 'D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\ps_modules\PowershellHelpers\PowershellHelpers.psm1'.
2018-03-09T00:57:23.6074389Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\ps_modules\PowershellHelpers\module.json
2018-03-09T00:57:23.6154316Z ##[debug]Loaded 2 strings.
2018-03-09T00:57:23.6189503Z ##[debug]SYSTEM_CULTURE: 'en-US'
2018-03-09T00:57:23.6211675Z ##[debug]Loading resource strings from: D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\ps_modules\PowershellHelpers\Strings\resources.resjson\en-US\resources.resjson
2018-03-09T00:57:23.6281336Z ##[debug]Loaded 2 strings.
2018-03-09T00:57:23.6328631Z ##[debug]Exporting function 'Invoke-ActionWithRetries'.
2018-03-09T00:57:23.6346035Z ##[debug]Importing function 'Invoke-ActionWithRetries'.
2018-03-09T00:57:23.6547457Z ##[debug]INPUT_PUBLISHPROFILEPATH: 'D:\a\1\s\**\PublishProfiles\Dev-Server.xml'
2018-03-09T00:57:23.6618720Z Searching for path: D:\a\1\s\**\PublishProfiles\Dev-Server.xml
2018-03-09T00:57:23.6656822Z ##[debug]Entering Find-VstsFiles.
2018-03-09T00:57:23.6673248Z ##[debug] LegacyPattern: 'D:\a\1\s\**\PublishProfiles\Dev-Server.xml'
2018-03-09T00:57:23.6699943Z ##[debug]Entering Get-MatchingItems.
2018-03-09T00:57:23.6717086Z ##[debug] IncludePatterns: 'D:\a\1\s\**\PublishProfiles\Dev-Server.xml'
2018-03-09T00:57:23.6733479Z ##[debug] ExcludePatterns: ''
2018-03-09T00:57:23.6751893Z ##[debug] IncludeFiles: 'True'
2018-03-09T00:57:23.6769464Z ##[debug] IncludeDirectories: 'False'
2018-03-09T00:57:23.6787767Z ##[debug] Force: 'False'
2018-03-09T00:57:25.7027121Z ##[debug]Path: D:\a\1\s\Projects\Daemon.Fabric\PublishProfiles\Dev-Server.xml
2018-03-09T00:57:25.7066919Z ##[debug]Leaving Get-MatchingItems.
2018-03-09T00:57:25.7089669Z ##[debug]Total found: 1
2018-03-09T00:57:25.7108609Z ##[debug]Leaving Find-VstsFiles.
2018-03-09T00:57:25.7340720Z ##[debug]Asserting leaf path exists: 'D:\a\1\s\Projects\Daemon.Fabric\PublishProfiles\Dev-Server.xml'
2018-03-09T00:57:25.7351476Z Found path: D:\a\1\s\Projects\Daemon.Fabric\PublishProfiles\Dev-Server.xml
2018-03-09T00:57:25.7890337Z ##[debug]INPUT_APPLICATIONPACKAGEPATH: 'D:\a\1\a'
2018-03-09T00:57:25.7899882Z Searching for path: D:\a\1\a
2018-03-09T00:57:25.7925955Z ##[debug]Entering Find-VstsFiles.
2018-03-09T00:57:25.7945357Z ##[debug] LegacyPattern: 'D:\a\1\a'
2018-03-09T00:57:25.7962564Z ##[debug] IncludeDirectories: 'True'
2018-03-09T00:57:25.7988546Z ##[debug]Entering Get-MatchingItems.
2018-03-09T00:57:25.8004859Z ##[debug] IncludePatterns: 'D:\a\1\a'
2018-03-09T00:57:25.8021439Z ##[debug] ExcludePatterns: ''
2018-03-09T00:57:25.8038249Z ##[debug] IncludeFiles: 'False'
2018-03-09T00:57:25.8054549Z ##[debug] IncludeDirectories: 'True'
2018-03-09T00:57:25.8069927Z ##[debug] Force: 'False'
2018-03-09T00:57:27.8321900Z ##[debug]Path: D:\a\1\a
2018-03-09T00:57:27.8343126Z ##[debug]Leaving Get-MatchingItems.
2018-03-09T00:57:27.8361238Z ##[debug]Total found: 1
2018-03-09T00:57:27.8382942Z ##[debug]Leaving Find-VstsFiles.
2018-03-09T00:57:27.8405607Z ##[debug]Asserting container path exists: 'D:\a\1\a'
2018-03-09T00:57:27.8418316Z Found path: D:\a\1\a
2018-03-09T00:57:27.8442841Z ##[debug]INPUT_SERVICECONNECTIONNAME: '11c1afb0-093c-4e31-968a-5ddb2fc0e8ab'
2018-03-09T00:57:27.8575357Z ##[debug]ENDPOINT_URL_11c1afb0-093c-4e31-968a-5ddb2fc0e8ab: 'tcp://daemon-dev.southcentralus.cloudapp.azure.com:19000/'
2018-03-09T00:57:27.8601759Z ##[debug]ENDPOINT_AUTH_11c1afb0-093c-4e31-968a-5ddb2fc0e8ab: '********'
2018-03-09T00:57:27.8626842Z ##[debug]ENDPOINT_DATA_11c1afb0-093c-4e31-968a-5ddb2fc0e8ab: '{}'
2018-03-09T00:57:27.8655969Z ##[debug]INPUT_COPYPACKAGETIMEOUTSEC (empty)
2018-03-09T00:57:27.8699407Z ##[debug]INPUT_REGISTERPACKAGETIMEOUTSEC (empty)
2018-03-09T00:57:27.8723902Z ##[debug]INPUT_COMPRESSPACKAGE: 'true'
2018-03-09T00:57:27.8786166Z ##[debug]INPUT_SKIPUPGRADESAMETYPEANDVERSION: 'false'
2018-03-09T00:57:27.8809329Z ##[debug]INPUT_SKIPPACKAGEVALIDATION: 'false'
2018-03-09T00:57:27.8833598Z ##[debug]INPUT_UNREGISTERUNUSEDVERSIONS: 'true'
2018-03-09T00:57:27.8856518Z ##[debug]INPUT_CONFIGUREDOCKERSETTINGS: 'false'
2018-03-09T00:57:27.9416732Z ##[debug]Entering Connect-ServiceFabricClusterFromServiceEndpoint.
2018-03-09T00:57:27.9451622Z ##[debug] ClusterConnectionParameters: 'System.Collections.Hashtable'
2018-03-09T00:57:27.9481435Z ##[debug] ConnectedServiceEndpoint: '@{Url=tcp://daemon-dev.southcentralus.cloudapp.azure.com:19000/; Data=; Auth=}'
2018-03-09T00:57:28.0586323Z Imported cluster client certificate with thumbprint '********'.
2018-03-09T00:57:28.0698751Z 
2018-03-09T00:57:28.0704053Z Thumbprint                                Subject                                                                      
2018-03-09T00:57:28.0705186Z ----------                                -------                                                                      
2018-03-09T00:57:28.0705919Z ********  CN=southcentralus.cloudapp.azure.com                                         
2018-03-09T00:57:32.0875380Z Successfully connected to cluster.
2018-03-09T00:57:32.0936247Z ##[debug]Leaving Connect-ServiceFabricClusterFromServiceEndpoint.
2018-03-09T00:57:32.1268378Z ##[debug]INPUT_APPLICATIONPARAMETERPATH: 'D:\a\1\s'
2018-03-09T00:57:32.1278003Z Searching for path: D:\a\1\s
2018-03-09T00:57:32.1299021Z ##[debug]Entering Find-VstsFiles.
2018-03-09T00:57:32.1316201Z ##[debug] LegacyPattern: 'D:\a\1\s'
2018-03-09T00:57:32.1344483Z ##[debug]Entering Get-MatchingItems.
2018-03-09T00:57:32.1362559Z ##[debug] IncludePatterns: 'D:\a\1\s'
2018-03-09T00:57:32.1382557Z ##[debug] ExcludePatterns: ''
2018-03-09T00:57:32.1399286Z ##[debug] IncludeFiles: 'True'
2018-03-09T00:57:32.1416715Z ##[debug] IncludeDirectories: 'False'
2018-03-09T00:57:32.1435311Z ##[debug] Force: 'False'
2018-03-09T00:57:34.1602352Z ##[debug]No paths.
2018-03-09T00:57:34.1622936Z ##[debug]Leaving Get-MatchingItems.
2018-03-09T00:57:34.1638540Z ##[debug]Total found: 0
2018-03-09T00:57:34.1656390Z ##[debug]Leaving Find-VstsFiles.
2018-03-09T00:57:34.1685298Z No items were found with search pattern D:\a\1\s.
2018-03-09T00:57:34.1739155Z ##[debug]Asserting leaf path exists: 'D:\a\1\s\Projects\Daemon.Fabric\PublishProfiles\..\ApplicationParameters\Dev-Server.xml'
2018-03-09T00:57:34.1765496Z ##[debug]INPUT_OVERRIDEPUBLISHPROFILESETTINGS: 'false'
2018-03-09T00:57:34.3675358Z ##[debug]INPUT_USEDIFFPACKAGE: 'false'
2018-03-09T00:57:43.5430508Z ##[debug]Join-Path "C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code" "ServiceFabricServiceModel.xsd"
2018-03-09T00:57:43.5490396Z ##[debug]C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\ServiceFabricServiceModel.xsd
2018-03-09T00:57:43.5504375Z ##[debug]Length: 94
2018-03-09T00:57:43.5515964Z ##[debug]
2018-03-09T00:57:43.5540692Z ##[debug]Test-Path "C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\ServiceFabricServiceModel.xsd"
2018-03-09T00:57:43.5796377Z ##[debug]True
2018-03-09T00:57:43.5810432Z ##[debug]
2018-03-09T00:57:52.0873908Z ##[debug]System.Fabric.Management.ImageBuilder.FabricImageBuilderValidationException: The BuildLayout of the application in C:\Users\VssAdministrator\AppData\Local\Temp\TestApplicationPackage_7234230284\3ta5hegv.q5m\a is invalid. File ApplicationManifest.xml is missing.
2018-03-09T00:57:52.0888694Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.TraceAndThrowValidationError(FabricErrorCode fabricErrorCode, String type, String format, Object[] args)
2018-03-09T00:57:52.0901138Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ParseApplicationPackageAsync>d__14.MoveNext()
2018-03-09T00:57:52.0913817Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2018-03-09T00:57:52.0925340Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-03-09T00:57:52.0937182Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-03-09T00:57:52.0948738Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ProvisionApplicationAsync>d__13.MoveNext()
2018-03-09T00:57:53.4363290Z ##[debug]Leaving D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\deploy.ps1.
2018-03-09T00:57:53.5403492Z ##[debug]Caught exception from task script.
2018-03-09T00:57:53.5432849Z ##[debug]Error record:
2018-03-09T00:57:53.6419579Z ##[debug]Test-ServiceFabricApplicationPackage : The BuildLayout of the application in C:\Users\VssAdministrator\AppData\Local\Temp\TestApplicationPackage_7234230284\3ta5hegv.q5m\a is invalid. File ApplicationManifest.xml is missing.
2018-03-09T00:57:53.6437298Z ##[debug]At D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\ServiceFabricSDK\Publish-UpgradedServiceFabricApplication.ps1:148 char:38
2018-03-09T00:57:53.6448874Z ##[debug]+ ... nSuccess = (Test-ServiceFabricApplicationPackage $AppPkgPathToUse -Im ...
2018-03-09T00:57:53.6461720Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-03-09T00:57:53.6473360Z ##[debug]    + CategoryInfo          : InvalidOperation: (:) [Test-ServiceFabricApplicationPackage], FabricImageBuilderValidati    onException
2018-03-09T00:57:53.6485684Z ##[debug]    + FullyQualifiedErrorId : TestApplicationPackageErrorId,Microsoft.ServiceFabric.Powershell.TestApplicationPackage
2018-03-09T00:57:53.6497273Z ##[debug] 
2018-03-09T00:57:53.6517428Z ##[debug]Script stack trace:
2018-03-09T00:57:53.6554357Z ##[debug]at Publish-UpgradedServiceFabricApplication, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\ServiceFabricSDK\Publish-UpgradedServiceFabricApplication.ps1: line 148
2018-03-09T00:57:53.6565503Z ##[debug]at <ScriptBlock>, D:\a\_tasks\ServiceFabricDeploy_c6650aa0-185b-11e6-a47d-df93e7a34c64\1.7.1\deploy.ps1: line 158
2018-03-09T00:57:53.6576697Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-03-09T00:57:53.6587839Z ##[debug]at <ScriptBlock>, <No file>: line 22
2018-03-09T00:57:53.6599719Z ##[debug]at <ScriptBlock>, <No file>: line 18
2018-03-09T00:57:53.6611728Z ##[debug]at <ScriptBlock>, <No file>: line 1
2018-03-09T00:57:53.6636117Z ##[debug]Exception:
2018-03-09T00:57:53.6684912Z ##[debug]System.Fabric.Management.ImageBuilder.FabricImageBuilderValidationException: The BuildLayout of the application in C:\Users\VssAdministrator\AppData\Local\Temp\TestApplicationPackage_7234230284\3ta5hegv.q5m\a is invalid. File ApplicationManifest.xml is missing.
2018-03-09T00:57:53.6697288Z ##[debug]   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.TraceAndThrowValidationError(FabricErrorCode fabricErrorCode, String type, String format, Object[] args)
2018-03-09T00:57:53.6708324Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ParseApplicationPackageAsync>d__14.MoveNext()
2018-03-09T00:57:53.6720594Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2018-03-09T00:57:53.6737078Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-03-09T00:57:53.6745111Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-03-09T00:57:53.6756746Z ##[debug]   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ProvisionApplicationAsync>d__13.MoveNext()
2018-03-09T00:57:53.7011829Z ##[error]The BuildLayout of the application in C:\Users\VssAdministrator\AppData\Local\Temp\TestApplicationPackage_7234230284\3ta5hegv.q5m\a is invalid. File ApplicationManifest.xml is missing.
2018-03-09T00:57:53.7013036Z ##[debug]Processed: ##vso[task.logissue type=error]The BuildLayout of the application in C:\Users\VssAdministrator\AppData\Local\Temp\TestApplicationPackage_7234230284\3ta5hegv.q5m\a is invalid. File ApplicationManifest.xml is missing.
2018-03-09T00:57:53.7018279Z ##[debug]Processed: ##vso[task.complete result=Failed]
2018-03-09T00:57:53.8105607Z ##[section]Finishing: Deploy Service Fabric Application

**Comment by dbreshears** [comment]
What is your Application package path set to in your Deploy Service Fabric Application task?   It seems it might be the issue.  It should be $(system.defaultworkingdirectory)/**/drop/applicationpackage

![e460e790](https://user-images.githubusercontent.com/3432571/37221998-8de04bc2-2380-11e8-9ca7-dac66116d199.png)

**Comment by NCarlsonMSFT** [comment]
@DaemonTrey slight clarification: $(system.defaultworkingdirectory)/**/drop/applicationpackage is the default and works in the majority of cases. If it doesn't work in your case use the "..." button next to Application Package to select the path to the application package in the appropriate artifact.

**Comment by DaemonTrey** [comment]
Changing the Application Package path didn't pan out.

I did have success after identifying that we erroneously had our deploy step as part of our build.

Revisiting and following this [tutorial](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-deploy-app-with-cicd-vsts#configure-continuous-delivery-with-vsts) had us create the deploy as a release step and everything seems to have worked out of the box. PEBKAC ;)

Thank you for your assistance and time.

Success! :)
