### ISSUE TITLE
Runtime upgrade troubleshooting

### ISSUE THREAD

**Issue by makar-sasha** [Azure/service-fabric-issues#929]
Hello

we are trying to upgrade runtime from 6.0 to 6.1 on Azure Service Fabric.
in our case it always results in timeout errors (nodes in first upgrade domain are down) after several hrs of work. Node restart or increasing upgrade timeout is not helpful.
could you describe any ways to analyse or overcome this issue?

Thanks!
Alex

**Comment by rishirsinha** [comment]
Can you check the number of registry key entries in the following key:
 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\FirewallRules

**Comment by makar-sasha** [comment]
hello

57896 entries are here. 
could it be the reason?

Thanks,
Alex

**Comment by rishirsinha** [comment]
We have a mitigation that you can apply so that upgrade can go through. Abhay can you provide Alex the mitigation.

**Comment by makar-sasha** [comment]
thanks @rishirsinha 
will wait for the help
Alex

**Comment by makar-sasha** [comment]
also there are a lot of these warning on the vm
ServiceFabricNodeBootstrapUpgradeAgent
Error reading HandlerEnvironment from C:\Packages\Plugins\Microsoft.Azure.ServiceFabric.ServiceFabricNode\1.0.0.38\UpgradeService\..\HandlerEnvironment.json (Retry=1/10): System.IO.IOException: The process cannot access the file 'C:\Packages\Plugins\Microsoft.Azure.ServiceFabric.ServiceFabricNode\1.0.0.38\HandlerEnvironment.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Microsoft.Azure.ServiceFabric.Extension.Core.Models.HandlerEnvironmentFile.Parse(String fileName, Int32 maxRetry)

**Comment by mhatreabhay** [comment]
You can ignore these warnings, they are transient errors. Bootstrap agent will write these warning when it is unable to access the file, when it is in use by another process. it back off and keep retrying. Eventually it will succeed.

**Comment by makar-sasha** [comment]
Thanks! 
the problem definitely was in firewall rules.
Alex
