### ISSUE TITLE
Calling a .NET Core 2.0 Reliable Actor from .NET Framework Stateless Service

### ISSUE THREAD

**Issue by codepic** [Azure/service-fabric-issues#934]
## Should the following scenario be supported?

> Or are there any workarounds to make the following work?

### Repro Steps

1. Create a new Service Fabric Project `net461` named `ServiceFabricApp`
2. Add `.NET Core 2.0` Reliable Actor named `Actor1`
3. Add `.NET Framework` Stateless Service named `Web1`
4. Reference `Actor1.Interfaces` in `Web1`
5. Unload `Actor1.Interfaces` and edit the project file to target `netstandard2.0`
6. Change the `GET: /api/values` method to following:

```cs
// GET api/values
[HttpGet]
public async Task<int> Get()
{
    IActor1 actor = ActorProxy.Create<IActor1>(ActorId.CreateRandom(), new Uri("fabric:/ServiceFabricApp/Actor1ActorService"));
    var retval = await actor.GetCountAsync(CancellationToken.None);
    return retval;
}
```

7. Start debugging (F5)
8. The GetCountAsync throws the following exception

```

System.Runtime.Serialization.SerializationException
  HResult=0x8013150C
  Message=Element 'http://schemas.microsoft.com/2003/10/Serialization/:anyType' contains data from a type that maps to the name 'urn:ServiceFabric.Communication:ServiceResponseMessageHeaders'. The deserializer has no knowledge of any type that maps to this name. Consider using a DataContractResolver if you are using DataContractSerializer or add the type corresponding to 'ServiceResponseMessageHeaders' to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding it to the list of known types passed to the serializer.
  Source=System.Runtime.Serialization
  StackTrace:
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate(XmlReaderDelegator xmlReader, Type declaredType, DataContract surrogateDataContract, String name, String ns)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at Microsoft.ServiceFabric.Services.Common.SerializationUtility.Deserialize(DataContractSerializer serializer, Byte[] buffer)
   at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.<InvokeAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.<ContinueWithResult>d__4`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Web1.Controllers.ValuesController.<Get>d__0.MoveNext() in c:\path\to\ValuesController.cs:line 21

```

**Comment by codepic** [comment]
Seems like Upgrading the below NuGets to `.472` build fixes the issue.

* Microsoft.ServiceFabric `v6.1.472`
* Microsoft.ServiceFabric.Actors `v3.0.472`
* Microsoft.ServiceFabric.AspNetCore.Kestrel `v3.0.472`
* Microsoft.ServiceFabric.Data `v3.0.472`
* Microsoft.ServiceFabric.Services `v3.0.472`

But the original question remains and maybe the Visual Studio projects templates should be upgraded?

**Comment by alexgman** [comment]
having the same issue here

**Comment by dbreshears** [comment]
Looks like this is resolved.    At times the templates in Visual Studio point to the previous released Nuget packages until the tooling can be updated after the SDK releases.  We are trying to improve this so the tooling support is ahead and available when the SDK releases.  Re-open if still having issues.

**Comment by raunakpandya** [comment]
@rakanc This doesnt sound related. Would recommend opening a new issue for this.
