### ISSUE TITLE
Copy-ServiceFabricApplicationPackage doesn't support long paths

### ISSUE THREAD

**Issue by OlegKarasik** [Azure/service-fabric-issues#935]
If you would try to run ```Copy-ServiceFabricApplicationPackage``` for the package directory that exceeded windows MAX_PATH then it would result in error:

```
VERBOSE: System.Fabric.FabricException: An error occurred during this operation.  Please check the trace logs for more
details. ---> System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM
component.
   at System.Fabric.Interop.NativeImageStore.ArchiveApplicationPackage(IntPtr appPackageRootDirectory,
IFabricNativeImageStoreProgressEventHandler progressEventHandler)
   at System.Fabric.Management.ImageStore.ImageStoreUtility.ArchiveApplicationPackageHelper(String
appPackageRootDirectory, IImageStoreProgressHandler progressHandler)
   at System.Fabric.Interop.Utility.<>c__DisplayClass27_0.<WrapNativeSyncInvoke>b__0()
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String
functionArgs)
   --- End of inner exception stack trace ---
   at System.Fabric.Interop.Utility.RunInMTA(Action action)
   at Microsoft.ServiceFabric.Powershell.CopyApplicationPackage.CompressOrUncompressIfNeeded(String sourcePath,
UploadProgressHandler progressHandler)
   at Microsoft.ServiceFabric.Powershell.CopyApplicationPackage.ProcessRecord()
```

Inside the trace logs there would be a message:
TryZipDirectory failed: 
```
src=<source folder> dest=<destination folder>\Code.zip error=System.IO.DirectoryNotFoundException: Could not find a part of the path '<name of the file will very long path>'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.DoCreateEntryFromFile(ZipArchive destination, String sourceFileName, String entryName, Nullable`1 compressionLevel)
   at System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
   at TryZipDirectory(Char* srcDirectoryPath, Char* destFileName, Char* errorMessageBuffer, Int32 errorMessageBufferSize)
```

**Comment by alexwun** [comment]
This is known as it currently uses the .NET compression library, which doesn't support long paths.

**Comment by alexwun** [comment]
Yes, of course - we'll improve the error message that comes back in the exception.

**Comment by OlegKarasik** [comment]
@alexwun 
Many thanks!

I have one small question: Are these cmdlets are open-sourced too now? Is there a way I can contribute to them?

**Comment by alexwun** [comment]
The open-sourced code on GitHub only supports building in Linux right now, so code that's specific to Windows (like the PowerShell cmdlet source) isn't there yet - though it's coming. We'll announce on our blog once the Windows specific code also makes it to GitHub:

https://blogs.msdn.microsoft.com/azureservicefabric/

We look forward to your contributions!

**Comment by iyyappam** [comment]
As mitigation, you could try upload without compression. We would provide a fix for this issue soon.

**Comment by GitTorre** [comment]
Working on this now.

**Comment by GitTorre** [comment]
The underlying compression code still uses System.IO.Compression APIs. The C++/CLI impl catches the managed exception (well, all managed exceptions that are not critical exceptions, so catch (Exception^ e)...), copies e->ToString() to supplied native error buffer location, which ends up back in managed in the Powershell client... 

In this case, I find it interesting that the exception details contain a DirectoryNotFoundException (DNFE) and not a PathTooLongException (PTLE), which is what the CLR is supposed to generate in the cases where Windows' MAX_PATH has been reached by some path string... There is no filtering going on that I can tell, so the error buffer *should* contain the PathTooLongException information, as nothing is removing it before it gets marshaled back into managed memory... 

Anyway, the current behavior is generally wrong: we should *not* always append a maybe-path-too-long message to output when TryUnzipDirectory fails for any reason, which is what is happening today (at least in the current builds). It's certainly the case that a DNFE makes sense if the directory path is too long since, well, but since there *is* a PathTooLongException that .NET's ZipFile.CreateFromDirectory method throws, it should be present in the error info we bubble back to the client. 

Anyway, I am going to the remove the maybe path too long message we now show all the time when this feature fails and figure out why we can't see the actual exception under the MAX_PATH_FAIL case...

**Comment by qmatto** [comment]
Omitting the -CompressPackage argument does not solve this for me. Are there any suggestions for a work around - other than a rename to shorten the path?
