### ISSUE TITLE
MSB4018	The "GetServiceProjectReferences" task failed unexpectedly

### ISSUE THREAD

**Issue by BrianMSFT** [Azure/service-fabric-issues#967]
New actor service added and it will not build, see below details.  It looks as though this error has been previously reported and resolved but perhaps it's back in the newer SDK or somewhere else?

**Windows Installed Components:**
- Microsoft Azure Service Fabric @ v6.1.467.9494
- Microsoft Azure Service Fabric SDK @ v3.0.467.9494

**CSProj Nuget Installed Components:**
- Microsoft.ServiceFabric @ v6.1.480
- Microsoft.ServiceFabric.Actors @ v3.0.480
- Microsoft.ServiceFabric.Data @ v3.0.480
- Microsoft.ServiceFabric.Diagnostics.Internal @ v3.0.480
- Microsoft.ServiceFabric.FabricTransport.Internal @ v3.0.480
- Microsoft.ServiceFabric.Services @ v3.0.480
- Microsoft.ServiceFabric.Services.Remoting @ v3.0.480

**SFProj Nuget Installed Components:**
- Microsoft.VisualStudio.Azure.Fabric.MSBuild @ v1.6.5

**Error List:**
> Severity	Code	Description	Project	File	Line	Suppression State
> Error		The command ""C:\src\sonar\i2\Packages\Microsoft.ServiceFabric.Actors.3.0.480\build\net45\\FabActUtil.exe" /spp:"PackageRoot" /t:manifest /sp:"WhitelistAnnotator" /in:"bin\x64\Debug\\WhitelistAnnotator.Exe" /arp:"C:\src\sonar\i2\Annotators\WhitelistAnnotator\bin\x64\Debug\\" " exited with code -1.	WhitelistAnnotator		

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	MSB4018	The "GetServiceProjectReferences" task failed unexpectedly.
> System.ArgumentNullException: Value cannot be null.
> Parameter name: source
>    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Microsoft.VisualStudio.Azure.Fabric.BuildTasks.ServiceModelServiceSlim.GetPrimaryCodePackage(ServiceManifestSlim serviceManifest)
>    at Microsoft.VisualStudio.Azure.Fabric.BuildTasks.GetServiceProjectReferences.SetMetadataForProjectReferences(PackageBehaviorOptions packageBehavior)
>    at Microsoft.VisualStudio.Azure.Fabric.BuildTasks.GetServiceProjectReferences.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Annotation	C:\src\sonar\i2\Packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.5\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets	94

**Comment by BrianMSFT** [comment]
Closing, this issue was caused by an overloaded interface method for the actor - it was in the build log :/

I would recommend trying to improve the error reported during build in the errors panel as it has nothing to do with the actor interface method being overloaded.
