### ISSUE TITLE
Upgrade of SF installed with HPC Pack to 6.1.480.9494 failed

### ISSUE THREAD

**Issue by crowbar27** [Azure/service-fabric-issues#968]
I have three-node SF cluster installed with HPC Pack 2016, which I have re-created for the third time now, because the first time, the upgrade from the version deployed with HPC Pack (5.4.164.9494 IIRC) to 6.1.480.9494 failed. The second time, I installed HPC Pack 2016 Update 1, which comes with a newer SF, but as the HPC installation failed this time, I re-installed again using the RTM version.

Given the failure the first time, I then upgraded SF version by version, ie from 5.4.164.9494 to 5.7.221.9494 and then to 6.1.472.9494, which is the current version. The final upgrade to 6.1.480.9494 failed and now I am stuck with a version that seems to be not upgradable. If I restart the upgrade, it always rolls back after some time. I get the following errors:

```posh
Get-ServiceFabricClusterHealth


AggregatedHealthState   : Error
UnhealthyEvaluations    :
                          System application is unhealthy.

                          Unhealthy deployed applications: 66% (2/3), MaxPercentUnhealthyDeployedApplications=0%.

                          Unhealthy deployed application: ApplicationName='fabric:/System', NodeName='vesta3', AggregatedHealthState='Error'.

                                Unhealthy deployed service packages: 33% (1/3).

                                Unhealthy deployed service package: ApplicationName='fabric:/System', ServiceManifestName='UOS', ServicePackageActivationId='', NodeName='vesta3', AggregatedHealthState='Error'.

                                        Error event: SourceId='System.Hosting', Property='CodePackageActivation:Code:EntryPoint'.

                          Unhealthy deployed application: ApplicationName='fabric:/System', NodeName='vesta2', AggregatedHealthState='Error'.

                                Unhealthy deployed service packages: 33% (1/3).

                                Unhealthy deployed service package: ApplicationName='fabric:/System', ServiceManifestName='UOS', ServicePackageActivationId='', NodeName='vesta2', AggregatedHealthState='Error'.

                                        Error event: SourceId='System.Hosting', Property='CodePackageActivation:Code:EntryPoint'.

NodeHealthStates        :
                          NodeName              : vesta2
                          AggregatedHealthState : Ok

                          NodeName              : vesta1
                          AggregatedHealthState : Ok

                          NodeName              : vesta3
                          AggregatedHealthState : Ok

ApplicationHealthStates :
                          ApplicationName       : fabric:/System
                          AggregatedHealthState : Error

HealthEvents            : None
HealthStatistics        :
                          Node                  : 3 Ok, 0 Warning, 0 Error
                          Application           : 0 Ok, 0 Warning, 0 Error
                          Service               : 0 Ok, 0 Warning, 0 Error
                          Partition             : 0 Ok, 0 Warning, 0 Error
                          Replica               : 0 Ok, 0 Warning, 0 Error
                          DeployedApplication   : 0 Ok, 0 Warning, 0 Error
                          DeployedServicePackage : 0 Ok, 0 Warning, 0 Error
```

If I interpret the following output correctly, I wants to tell me that the upgrade service itself is broken:
```posh
Get-ServiceFabricApplicationHealth fabric:/System


ApplicationName                 : fabric:/System
AggregatedHealthState           : Error
UnhealthyEvaluations            :
                                  Unhealthy services: 100% (1/1), ServiceType='UpgradeOrchestrationServiceType', MaxPercentUnhealthyServices=0%.

                                  Unhealthy service: ServiceName='fabric:/System/UpgradeOrchestrationService', AggregatedHealthState='Error'.

                                        Unhealthy partitions: 100% (1/1), MaxPercentUnhealthyPartitionsPerService=0%.

                                        Unhealthy partition: PartitionId='00000000-0000-0000-0000-000000006000', AggregatedHealthState='Error'.

                                                Error event: SourceId='System.FM', Property='State'.

ServiceHealthStates             :
                                  ServiceName           : fabric:/System/FailoverManagerService
                                  AggregatedHealthState : Ok

                                  ServiceName           : fabric:/System/UpgradeOrchestrationService
                                  AggregatedHealthState : Error

                                  ServiceName           : fabric:/System/FaultAnalysisService
                                  AggregatedHealthState : Ok

                                  ServiceName           : fabric:/System/NamingService
                                  AggregatedHealthState : Ok

                                  ServiceName           : fabric:/System/ClusterManagerService
                                  AggregatedHealthState : Ok

                                  ServiceName           : fabric:/System/ImageStoreService
                                  AggregatedHealthState : Ok

DeployedApplicationHealthStates :
                                  ApplicationName       : fabric:/System
                                  NodeName              : vesta1
                                  AggregatedHealthState : Warning

                                  ApplicationName       : fabric:/System
                                  NodeName              : vesta3
                                  AggregatedHealthState : Error

                                  ApplicationName       : fabric:/System
                                  NodeName              : vesta2
                                  AggregatedHealthState : Error

HealthEvents                    : None
HealthStatistics                :
                                  Replica               : 24 Ok, 0 Warning, 0 Error
                                  Partition             : 7 Ok, 0 Warning, 1 Error
                                  Service               : 5 Ok, 0 Warning, 1 Error
                                  DeployedServicePackage : 6 Ok, 1 Warning, 2 Error
                                  DeployedApplication   : 0 Ok, 1 Warning, 2 Error
```

Furthermore, I can see the following periodic errors in the event log

```
Application: FabricUOS.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: RunAsync failed due to an unhandled exception causing the host process to crash: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.ServiceFabric.ClusterManagementCommon.UserConfigVersion.Equals(Object other)
   at Microsoft.ServiceFabric.ClusterManagementCommon.ClusterUpgradeStateBase.IsUserInitiatedUpgrade()
   at Microsoft.ServiceFabric.ClusterManagementCommon.ClusterResourceStateMachine.TryInterruptPendingUpgrade()
   at System.Fabric.UpgradeOrchestration.Service.UpgradeOrchestrator.<StartUpgradeAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeOrchestration.Service.FabricUpgradeOrchestrationService.<RunAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.<ExecuteRunAsync>d__22.MoveNext()
Stack:
   at System.Environment.FailFast(System.String)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

and 
```
Faulting application name: FabricUOS.exe, version: 6.1.472.9494, time stamp: 0x5a99d900
Faulting module name: mscorlib.ni.dll, version: 4.7.2117.0, time stamp: 0x59cf513d
Exception code: 0x80131623
Fault offset: 0x000000000052d436
Faulting process id: 0x920
Faulting application start time: 0x01d3ccf78c564e73
Faulting application path: C:\ProgramData\SF\vesta1\Fabric\work\Applications\__FabricSystem_App4294967295\UOS.Code.Current\FabricUOS.exe
Faulting module path: C:\windows\assembly\NativeImages_v4.0.30319_64\mscorlib\6b278bb41b219b5d3ea584606329e448\mscorlib.ni.dll
Report Id: 234876bb-c075-40c5-af75-b82aefce8a39
Faulting package full name: 
Faulting package-relative application ID: 
```

The obvious question is: how do I fix that?

Thanks in advance,
Christoph

**Comment by rishirsinha** [comment]
The first and second failures are expected as we have had changes that prevent direct upgrade from 5.4 up. The issue with 6.1.480 should not be happening. If you can share the traces, we can take a look and see why it is failing.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-standalone-package-contents

The link above will explain how to collect logs.

**Comment by crowbar27** [comment]
I have looked at the link and I believe you are referring to the StandaloneLogCollector. I have tried running `.\StandaloneLogCollector.exe -StartUtcTime "$([DateTime]::UtcNow.ToString("u"))" -Output c:\tmp\logs`, but it seems that the "StorageConnectionString" parameter "provided by Microsoft support steam in the format of a SAS URL", which I do not have, is mandatory. However, I also have a lot of files in C:\ProgramData\SF\Log\Traces. There are also some starting "FabricInstallerService_6.1.480.9494" containing several warnings and errors (please tell me whether these are the logs you are looking for):

`2018-04-06 14:04:12.937,Warning ,7280,FabricInstallerService.FabricUpgradeManager,Error 0x8007050d while closing Fabric asset-holding processes before Uninstall (Best-effort).` (multiple times)

`2018-04-06 14:04:23.656,Error   ,7280,General.Directory@MoveFile,MoveFileEx from \\?\C:\Program Files\Microsoft Service Fabric\bin to \\?\C:\Program Files\Microsoft Service Fabric\bin.old failed: error=5` (retried very often)

I start the upgrade from a local admin Powershell on one of the nodes. Do I need to use a different account?

**Comment by rishirsinha** [comment]
@maburlik can you check what is happening here?

**Comment by maburlik** [comment]
Based on the tracking email thread this has been resolved offline and the customer was able to upgrade to the destination version by resetting the UOS data, using the steps below, and then updating to a more recent configuration API version.

1.	Start-serviceFabricPartitionDataLoss -OperationId <Unique GUID> -DataLossMode FullDataLoss -PartitionId 00000000-0000-0000-0000-000000006000 -ServiceName "fabric:/System/UpgradeOrchestrationService"
[Note : After this step, UOS should stop crashing. The customer may have to run the above multiple times till FUOS stops crashing)
 
2.	Start-ServiceFabricClusterConfigurationUpgrade  -ClusterConfigPath <Filepath for most recent JSON>
[Note : This will not trigger and cluster configuration, rather it will restore UOS state]
 
3.	Since customer hasn't done any config upgrade in the past, inside fabric data root [ C:\ProgramData\SF\[NodeName]\Fabric] there should be only 1 clustermanifest of name clustermanifest.0.xml. If there are more manifests like clustermanifest.1.xml, clustermanifest.2.xml, then that means there were upgrades done in the past. In that case, we will have to modify UOS metadata. Please ask the customer to run Get-ServiceFabricUpgradeOrchestrationServiceState and send us the output. Also, send us all the clustermanifests that you see.
