### ISSUE TITLE
Service Fabric SDK 3.0.480 installation error while installing Service Fabric Runtime 6.1.480

### ISSUE THREAD

**Issue by gumaflux** [Azure/service-fabric-issues#976]
Trying to install Service Fabric SDK 3.0.480 for VS 2017 I get the following error message in the PI installer log:

DownloadManager Error: 0 : **Exception installing 'Microsoft Azure Service Fabric Runtime - 6.1.480'. Exception: System.ComponentModel.Win32Exception: Unknown error (0xffffffff)**
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.Web.PlatformInstaller.ExeInstallCommand.Run(InstallManager installManager, InstallerContext installerContext)
   at Microsoft.Web.PlatformInstaller.InstallManager.DoInstall(InstallerContext currentInstall)

That is VS 2017 Enterprise 15.6.6

**Comment by dbreshears** [comment]
@gumaflux, sorry for delay on this.  Is this still an issue?  Have you tried installing 6.2 / 3.1 SDK from Web platform installer?
